engine/src/main/java/org/hibernate/validator/constraints/SafeHtml.java
Added `span` to `WhiteListType.BASIC`; `span` and `div` to `WhiteListType.RELAXED`.
=> HV-957 Updating SafeHtml.WhiteListType documentation

pom.xml
https://hibernate.atlassian.net/browse/HV-972
=> HV-972 Avoid dependency on ASM4 (upgrade groovy-jsr223)

engine/src/main/java/org/hibernate/validator/internal/constraintvalidators/hv/br/CPFValidator.java, engine/src/test/java/org/hibernate/validator/test/constraints/br/CPFValidatorTest.java
=> HV-979 Adding support for CPF format xxxxxxxxx-xx

cdi/pom.xml, pom.xml
- Upgrading maven bundle plugin
- Adding Imports and Exports for CDI module in maven bundle plugin
- Making CDI bundle a fragment of the main Validator bundle
=> HV-846 Adding OSGi metadata to cdi module

engine/src/main/java/org/hibernate/validator/internal/metadata/aggregated/BeanMetaDataImpl.java, engine/src/main/java/org/hibernate/validator/internal/metadata/aggregated/ExecutableMetaData.java, engine/src/main/java/org/hibernate/validator/internal/metadata/descriptor/BeanDescriptorImpl.java, engine/src/main/java/org/hibernate/validator/internal/metadata/raw/ExecutableElement.java, engine/src/main/java/org/hibernate/validator/internal/util/ExecutableHelper.java, engine/src/test/java/org/hibernate/validator/test/internal/engine/methodlevel/generic/MethodValidationInHierarchyTest.java, engine/src/test/java/org/hibernate/validator/test/internal/engine/methodlevel/generic/SimpleService.java, engine/src/test/java/org/hibernate/validator/test/internal/metadata/aggregated/ExecutableMetaDataTest.java, engine/src/test/java/org/hibernate/validator/test/internal/metadata/aggregated/JobRepository.java, engine/src/test/java/org/hibernate/validator/test/internal/metadata/aggregated/JobRepositoryImpl.java, engine/src/test/java/org/hibernate/validator/test/internal/metadata/aggregated/SpecialJobRepositoryImpl.java
@emmanuelbernard Seems like you are the only one left to merge it ;) Thx!
=> HV-1011: Allow executable validation by passing overridden super-type method

copyright.txt, documentation/src/main/asciidoc/ch03.asciidoc, documentation/src/main/asciidoc/ch11.asciidoc, engine/src/cfgtest/resources/META-INF/validation.xml, engine/src/main/java/org/hibernate/validator/HibernateValidatorConfiguration.java, engine/src/main/java/org/hibernate/validator/HibernateValidatorContext.java, engine/src/main/java/org/hibernate/validator/internal/engine/ConfigurationImpl.java, engine/src/main/java/org/hibernate/validator/internal/engine/MethodValidationConfiguration.java, engine/src/main/java/org/hibernate/validator/internal/engine/ValidatorContextImpl.java, engine/src/main/java/org/hibernate/validator/internal/engine/ValidatorFactoryImpl.java, engine/src/main/java/org/hibernate/validator/internal/engine/ValidatorImpl.java, engine/src/main/java/org/hibernate/validator/internal/metadata/BeanMetaDataManager.java, engine/src/main/java/org/hibernate/validator/internal/metadata/aggregated/BeanMetaDataImpl.java, engine/src/main/java/org/hibernate/validator/internal/metadata/aggregated/ExecutableMetaData.java, engine/src/main/java/org/hibernate/validator/internal/metadata/raw/ConstrainedExecutable.java, engine/src/test/java/org/hibernate/validator/cfgtest/ConfigurationFilePropertiesTest.java, engine/src/test/java/org/hibernate/validator/test/HibernateValidatorConfigurationTest.java, engine/src/test/java/org/hibernate/validator/test/internal/engine/methodvalidation/IllegalMethodParameterConstraintsTest.java, engine/src/test/java/org/hibernate/validator/test/internal/engine/methodvalidation/RelaxedMethodParameterConstraintsTest.java, engine/src/test/java/org/hibernate/validator/test/internal/engine/methodvalidation/subject/ConcreteClass.java, engine/src/test/java/org/hibernate/validator/test/internal/engine/methodvalidation/subject/Interface.java, engine/src/test/java/org/hibernate/validator/test/internal/engine/methodvalidation/subject/SubClass.java, engine/src/test/java/org/hibernate/validator/test/internal/engine/methodvalidation/subject/ValueObject.java, engine/src/test/java/org/hibernate/validator/test/internal/engine/methodvalidation/subject/ValueObjectSubClass.java
Finally got around taking a closer look at the problems with applying #421.
I cherry-picked the commits introducing the new functionality and fixed merged conflicts. This pull request applies to master and passes all tests.
TODO -  Documentation needs to be written. The pull request had changes to the obsolete docbook documentation which I ignored so far.
=> HV-872 Optional relaxation of parameter validation

engine/pom.xml, engine/src/main/java/org/hibernate/validator/internal/xml/ValidationXmlParser.java, engine/src/main/java/org/hibernate/validator/internal/xml/XmlMappingParser.java, engine/src/main/xjb/binding-customization.xjb, engine/src/main/xsd/validation-configuration-2.0.xsd, engine/src/main/xsd/validation-mapping-2.0.xsd, engine/src/test/java/org/hibernate/validator/test/internal/xml/XmlMappingTest.java, engine/src/test/resources/org/hibernate/validator/test/cfg/ConfigurationFilePropertiesTest_validation.xml, engine/src/test/resources/org/hibernate/validator/test/internal/xml/my-interface-impl-mapping-unsupported-version.xml, engine/src/test/resources/org/hibernate/validator/test/internal/xml/unsupported-validation.xml
https://hibernate.atlassian.net/browse/HV-1084
=> HV-1084 Adding XML schemas for BV 2.0

README.md, build-config/src/main/resources/checkstyle.xml, cdi/pom.xml, distribution/pom.xml, distribution/src/main/assembly/dist.xml, documentation/pom.xml, documentation/src/main/asciidoc/ch01.asciidoc, engine/pom.xml, engine/src/test/java/org/hibernate/validator/test/internal/engine/valuehandling/JavaFXClassLoadingTest.java, osgi/integrationtest/pom.xml, osgi/karaf-features/pom.xml, osgi/karaf-features/src/main/features/features.xml, performance/pom.xml, pom.xml, tck-runner/pom.xml
* https://hibernate.atlassian.net/browse/HV-1086
=> HV-1086 - Update dependencies

README.md, documentation/src/main/asciidoc/ch11.asciidoc, documentation/src/main/asciidoc/ch13.asciidoc, documentation/src/main/asciidoc/index-docinfo.xml, documentation/src/main/asciidoc/pr01.asciidoc, engine/src/main/java/org/hibernate/validator/HibernateValidatorConfiguration.java, engine/src/main/java/org/hibernate/validator/HibernateValidatorContext.java, engine/src/main/java/org/hibernate/validator/internal/engine/MethodValidationConfiguration.java, engine/src/main/java/org/hibernate/validator/internal/metadata/BeanMetaDataManager.java, engine/src/main/java/org/hibernate/validator/overview.html, tck-runner/pom.xml, tck-runner/readme.md, tck-runner/src/test/java/org/hibernate/validator/tckrunner/securitymanager/TckRunner.java, tck-runner/src/test/resources/tck-tests-jdk9.xml
* https://hibernate.atlassian.net/browse/HV-1046
* https://hibernate.atlassian.net/browse/HV-1090
* Update remaining references to BV 1.1
=> Update the TCK to 2.0.0-SNAPSHOT

.travis.yml, README.md, settings-example.xml
* https://hibernate.atlassian.net/browse/HV-1092
=> HV-1092 Provide a settings-example.xml

engine/src/main/java/org/hibernate/validator/internal/cfg/context/TypeConstraintMappingContextImpl.java, engine/src/main/java/org/hibernate/validator/internal/util/logging/Log.java, engine/src/test/java/org/hibernate/validator/test/cfg/MethodConstraintMappingTest.java
Small left-over from https://hibernate.atlassian.net/browse/HV-763.
=> HV-763 Removing redundant logging method

engine/src/main/java/org/hibernate/validator/internal/metadata/descriptor/ConstraintDescriptorImpl.java
* https://hibernate.atlassian.net/browse/HV-1108
=> HV-1108 Add @Repeatable to NON_COMPOSING_CONSTRAINT_ANNOTATIONS

engine/src/main/java/org/hibernate/validator/internal/engine/ValidatorImpl.java, engine/src/main/java/org/hibernate/validator/internal/engine/constraintvalidation/ConstraintTree.java, engine/src/test/java/org/hibernate/validator/test/internal/engine/typeannotationconstraint/SameElementContainedSeveralTimesInCollectionTest.java
* https://hibernate.atlassian.net/browse/HV-1110
=> HV-1110 Additional TYPE_USE related cleanup

README.md, pom.xml
* https://hibernate.atlassian.net/browse/HV-1125
=> HV-1125 Latest JDK9 previews changed -addmods to --add-modules

pom.xml
https://hibernate.atlassian.net/browse/HV-1128
https://hibernate.atlassian.net/browse/HV-1129
=> Enabling integration tests on WF@JDK9; WildFly Arquillian update

engine-jdk8-tests/pom.xml, engine/src/main/java/org/hibernate/validator/internal/engine/ConfigurationImpl.java, engine/src/main/java/org/hibernate/validator/internal/engine/ValidatorContextImpl.java, engine/src/main/java/org/hibernate/validator/internal/engine/messageinterpolation/ElTermResolver.java, engine/src/main/java/org/hibernate/validator/messageinterpolation/ResourceBundleMessageInterpolator.java, engine/src/test/java/org/hibernate/validator/test/internal/engine/ValidatorFactoryNoELBootstrapTest.java
=> Backport of HV-1131 for 5.3

documentation/pom.xml, documentation/src/test/java/org/hibernate/validator/referenceguide/chapter05/GroupTest.java
@gunnarmorling this one should be merged quickly as it will cause CI failures.
=> HV-1133 The order is not predictible so we'd better use assertj

pom.xml
* https://hibernate.atlassian.net/browse/HV-1146
=> HV-1146 Upgrade previous stable used by japicmp to 5.3.1.Final

annotation-processor/src/main/java/org/hibernate/validator/ap/checks/CrossParameterConstraintCheck.java, distribution/pom.xml, engine/src/main/java/org/hibernate/validator/constraints/pl/NIP.java, engine/src/main/java/org/hibernate/validator/constraints/pl/PESEL.java, engine/src/main/java/org/hibernate/validator/constraints/pl/REGON.java
* https://hibernate.atlassian.net/browse/HV-1149
* https://hibernate.atlassian.net/browse/HV-1150
* https://hibernate.atlassian.net/browse/HV-1144
=> Assorted fixes to the JavaDocs

engine/src/main/java/org/hibernate/validator/internal/util/logging/Log.java, engine/src/main/java/org/hibernate/validator/messageinterpolation/ResourceBundleMessageInterpolator.java, engine/src/test/java/org/hibernate/validator/test/internal/engine/ValidatorFactoryNoELBootstrapTest.java
* https://hibernate.atlassian.net/browse/HV-1153
=> HV-1153 Missing javax.el impl should throw a ValidationException

documentation/src/main/asciidoc/ch11.asciidoc, engine/src/main/java/org/hibernate/validator/internal/engine/ConfigurationImpl.java, engine/src/main/java/org/hibernate/validator/internal/engine/messageinterpolation/ElTermResolver.java, engine/src/main/java/org/hibernate/validator/internal/engine/messageinterpolation/el/SimpleELContext.java, engine/src/main/java/org/hibernate/validator/internal/util/privilegedactions/SetContextClassLoader.java, engine/src/main/java/org/hibernate/validator/messageinterpolation/ResourceBundleMessageInterpolator.java, engine/src/test/java/org/hibernate/validator/test/internal/engine/ValidatorFactoryNoELBootstrapTest.java, osgi/integrationtest/src/test/java/org/hibernate/validator/osgi/integrationtest/OsgiIntegrationTest.java, pom.xml
Hi @gsmet, it's largely based on your work, only changed some small bits. Most notably the it avoids the TCCL change for the bundle locators, in order to avoid any behavioral change here.
=> [5.3] HV-1155 - some refinements

engine/src/main/java/org/hibernate/validator/internal/engine/ConfigurationImpl.java, engine/src/main/java/org/hibernate/validator/internal/engine/messageinterpolation/ElTermResolver.java, engine/src/main/java/org/hibernate/validator/internal/engine/messageinterpolation/el/SimpleELContext.java, engine/src/main/java/org/hibernate/validator/internal/util/privilegedactions/SetContextClassLoader.java, engine/src/main/java/org/hibernate/validator/messageinterpolation/ResourceBundleMessageInterpolator.java, engine/src/test/java/org/hibernate/validator/test/internal/engine/ValidatorFactoryNoELBootstrapTest.java, osgi/integrationtest/src/test/java/org/hibernate/validator/osgi/integrationtest/OsgiIntegrationTest.java, pom.xml
* https://hibernate.atlassian.net/browse/HV-1155
Long story short...
=> HV-1155 Class loading issues in modular environments

performance/src/main/java/org/hibernate/validator/performance/TestRunner.java
* https://hibernate.atlassian.net/browse/HV-1160
Already fixed in 5.4 (did it when I made the code JDK6 compliant).
=> HV-1160 Fix minor typo in TestRunner

documentation/src/main/asciidoc/ch02.asciidoc
See docs.oracle.com/javaee/7/api/javax/validation/constraints/Pattern.html
=> Documentation: Fixed 'Pattern' constraint arguments

engine/src/main/java/org/hibernate/validator/internal/engine/ValidatorImpl.java, engine/src/main/java/org/hibernate/validator/internal/metadata/aggregated/ExecutableMetaData.java, engine/src/main/java/org/hibernate/validator/internal/metadata/facets/Cascadable.java, engine/src/main/java/org/hibernate/validator/internal/util/logging/formatter/ExecutableFormatter.java, engine/src/test/java/org/hibernate/validator/test/internal/util/ExecutableFormatterTest.java, engine/src/test/java/org/hibernate/validator/test/internal/util/ExecutableHelperTest.java
Just to get a CI run, I'll merge right after that.
=> Commits extracted from HV-1166

engine/src/main/java/org/hibernate/validator/internal/engine/ValidatorImpl.java, engine/src/main/java/org/hibernate/validator/internal/metadata/location/TypeArgumentConstraintLocation.java, engine/src/main/java/org/hibernate/validator/internal/metadata/provider/AnnotationMetaDataProvider.java, engine/src/main/java/org/hibernate/validator/internal/metadata/raw/ConstrainedExecutable.java, engine/src/main/java/org/hibernate/validator/internal/metadata/raw/ConstrainedField.java, engine/src/main/java/org/hibernate/validator/internal/metadata/raw/ConstrainedParameter.java, engine/src/main/java/org/hibernate/validator/internal/util/CollectionHelper.java, engine/src/main/java/org/hibernate/validator/internal/util/ReflectionHelper.java, engine/src/test/java/org/hibernate/validator/test/internal/engine/typeannotationconstraint/TypeAnnotationConstraintTest.java, engine/src/test/java/org/hibernate/validator/test/internal/util/ReflectionHelperTest.java
* https://hibernate.atlassian.net/browse/HV-1165
* https://hibernate.atlassian.net/browse/HV-1175
* https://hibernate.atlassian.net/browse/HV-1176
Better to validate commit by commit as they are quite unrelated.
=> Various fixes for type arguments support

documentation/src/main/asciidoc/ch11.asciidoc
* https://hibernate.atlassian.net/browse/HV-1122
Didn't think it was worth it to create a specific JIRA as HV-1122 has not been released yet.
=> HV-1122 Fix duplicated example id making the docbook processing fail

build-config/src/main/resources/checkstyle-documentation.xml, build-config/src/main/resources/checkstyle-junit.xml, build-config/src/main/resources/checkstyle.xml, engine/src/main/java/org/hibernate/validator/internal/metadata/aggregated/BeanMetaData.java, pom.xml
* https://hibernate.atlassian.net/browse/HV-1189
* https://hibernate.atlassian.net/browse/HV-1186
* https://hibernate.atlassian.net/browse/HV-1145
=> Various minor fixes

engine/src/main/java/org/hibernate/validator/internal/metadata/descriptor/ConstraintDescriptorImpl.java
Didn't think it was worth a JIRA. Can create it if need be.
=> Fix minor typo in javadoc

documentation/src/main/asciidoc/ch02.asciidoc
Note that we still need to update this paragraph as part of HV-1190
=> HV-1166 Fix a missing source include

documentation/src/test/java/org/hibernate/validator/referenceguide/chapter08/BootstrappingTest.java
* https://hibernate.atlassian.net/browse/HV-1194
A few examples are not testable but most of them are so we'd better test them.
=> HV-1194 Add @Test annotations to testable examples of BootstrappingTest

integration/pom.xml, integration/src/test/java/org/hibernate/validator/integration/wildfly/OptionalConstraintsIT.java, integration/src/test/modules/javax/money/api/main/module.xml, integration/src/test/modules/org/javamoney/moneta/main/module.xml, integration/src/test/resources/jboss-deployment-structure-optional-constraints.xml, modules/src/script/setupModules.groovy, osgi/integrationtest/src/test/java/com/example/money/ExternalClassLoaderJavaxMoneyServiceProvider.java, osgi/integrationtest/src/test/java/org/hibernate/validator/osgi/integrationtest/OsgiIntegrationTest.java
* https://hibernate.atlassian.net/browse/HV-1124
=> HV-1124 Add integration test for javax.money validation on WildFly

engine/src/main/java/org/hibernate/validator/constraints/Currency.java, engine/src/main/java/org/hibernate/validator/constraints/pl/NIP.java, engine/src/main/java/org/hibernate/validator/constraints/pl/PESEL.java, engine/src/main/java/org/hibernate/validator/constraints/pl/REGON.java, integration/pom.xml, pom.xml
https://hibernate.atlassian.net/browse/HV-1205
The second commit should be merged to master, too.
=> HV-1205 ("Don't use @Repeatable on some constraints")

engine/src/main/java/org/hibernate/validator/internal/util/CollectionHelper.java, engine/src/main/java/org/hibernate/validator/internal/util/ReflectionHelper.java
https://hibernate.atlassian.net/browse/HV-1222
This basically adds what was already added in Search: https://github.com/hibernate/hibernate-search/commit/1b3c001011f10b410b6f8b208e5ba58cf9b15fc9
I'm not sure the second commit is really necessary, but I added it anyway so you have the choice to merge it or not.
=> HV-1222 Update CollectionHelper.iteratorFromArray and add CollectionHelper.iterableFromArray

engine/src/main/java/org/hibernate/validator/internal/engine/ValidatorFactoryImpl.java, engine/src/main/java/org/hibernate/validator/internal/engine/constraintvalidation/ConstraintValidatorManager.java, engine/src/main/java/org/hibernate/validator/internal/util/stereotypes/Immutable.java, engine/src/main/java/org/hibernate/validator/internal/util/stereotypes/ThreadSafe.java
@gsmet Usually I wouldn't send a PR, but that backport caused quite some conflicts, so I wouldn't mind a second pair of eyes.
https://hibernate.atlassian.net/browse/HV-1088
=> HV-1088 - Backport to 5.4

documentation/src/main/asciidoc/index.asciidoc
https://hibernate.atlassian.net/browse/HV-1242
=> HV-1242 Hibernate Validator 5.4 implements JSR 349

engine/src/main/java/org/hibernate/validator/internal/engine/ValidatorImpl.java, engine/src/test/java/org/hibernate/validator/test/internal/engine/cascaded/CustomValueExtractorTest.java
* https://hibernate.atlassian.net/browse/HV-1243
=> HV-1243 Throw an exception if no value extractor is found during cascaded validation

documentation/src/main/asciidoc/ch04.asciidoc, documentation/src/main/asciidoc/ch09.asciidoc, engine/src/test/java/org/hibernate/validator/test/internal/engine/constraintvalidation/ConstraintValidatorResolutionTest.java, tck-runner/readme.md
* https://hibernate.atlassian.net/browse/HV-1089
=> HV-1089 Update links for the TCK and the API

engine/src/main/java/org/hibernate/validator/constraints/Currency.java, engine/src/main/java/org/hibernate/validator/constraints/pl/NIP.java, engine/src/main/java/org/hibernate/validator/constraints/pl/PESEL.java, engine/src/main/java/org/hibernate/validator/constraints/pl/REGON.java
* https://hibernate.atlassian.net/browse/HV-1253
=> HV-1253 Remove TYPE_USE target mistakenly added in 5.4 branch

pom.xml
* https://hibernate.atlassian.net/browse/HV-1251
=> HV-1251 Check that we don't use snapshot dependencies when we release

README.md
* https://hibernate.atlassian.net/browse/HV-1230
=> HV-1230 Update the groupId in the README.md file

engine/src/main/java/org/hibernate/validator/internal/cfg/context/ContainerElementConstraintMappingContextImpl.java, engine/src/main/java/org/hibernate/validator/internal/engine/cascading/ArrayElement.java, engine/src/main/java/org/hibernate/validator/internal/metadata/cascading/CascadingTypeParameter.java, engine/src/test/java/org/hibernate/validator/test/cfg/ProgrammaticContainerElementConstraintsForParameterTest.java, engine/src/test/java/org/hibernate/validator/test/cfg/ProgrammaticContainerElementConstraintsForReturnValueTest.java, engine/src/test/java/org/hibernate/validator/test/internal/engine/typeannotationconstraint/TypeAnnotationDefinedOnAGenericTypeArgumentTest.java
* https://hibernate.atlassian.net/browse/HV-1279
=> HV-1279 Ensure validating a constraint on a generic type argument throw a proper exception

performance/pom.xml, performance/src/main/java/org/hibernate/validator/performance/cascaded/CascadedValidation.java, performance/src/main/java/org/hibernate/validator/performance/simple/SimpleValidation.java, performance/src/main/java/org/hibernate/validator/performance/statistical/StatisticalValidation.java
* https://hibernate.atlassian.net/browse/HV-1286
=> HV-1286 Some improvements for the performance tests

build-config/pom.xml, engine/src/test/java/org/hibernate/validator/test/internal/engine/methodvalidation/returnvaluevalidation/ContactService.java, engine/src/test/java/org/hibernate/validator/test/internal/util/IdentitySetTest.java, pom.xml
The wrong equals() methods are a good spot indeed.
https://hibernate.atlassian.net/browse/HV-1287
=> HV-1287 Upgrading to CheckStyle 7.6

pom.xml
* https://hibernate.atlassian.net/browse/HV-1295
=> HV-1295 Upgrade validation-api to 2.0.0.Alpha2

tck-runner/pom.xml
https://hibernate.atlassian.net/browse/HV-1299
=> HV-1299 Upgrade TCK to 2.0.0.Alpha2

documentation/src/main/asciidoc/ch02.asciidoc
Updated the doc as discussed in https://github.com/hibernate/hibernate-validator/pull/713
=> HV-1292 Adding new BV constraints to documentation

annotation-processor/src/main/java/org/hibernate/validator/ap/checks/MultiValuedChecks.java, engine/src/main/java/org/hibernate/validator/internal/metadata/core/ConstraintHelper.java, engine/src/main/java/org/hibernate/validator/internal/metadata/provider/AnnotationMetaDataProvider.java
* https://hibernate.atlassian.net/browse/HV-1311
=> HV-1311 Ignore JDK annotations in constraints discovery

engine/src/main/java/org/hibernate/validator/internal/metadata/provider/AnnotationMetaDataProvider.java, engine/src/test/java/org/hibernate/validator/test/internal/engine/valuehandling/NestedTypeArgumentsValueExtractorTest.java
* https://hibernate.atlassian.net/browse/HV-1310
=> HV-1310 Add support for container element constraints for nested arrays

engine/src/main/java/org/hibernate/validator/internal/metadata/descriptor/ConstraintDescriptorImpl.java
* https://hibernate.atlassian.net/browse/HV-1309
=> HV-1309 Add @Deprecated to the list of annotations ignored as potential composing constraint annotations

engine/src/main/java/org/hibernate/validator/HibernateValidatorContext.java
https://hibernate.atlassian.net/projects/HV/issues/HV-1321
=> HV-1321 Adding BV 2.0 methods to HibernateValidatorContext

engine/src/main/java/org/hibernate/validator/internal/engine/ValidatorImpl.java, engine/src/test/java/org/hibernate/validator/test/internal/engine/cascaded/NestedCascadedConstraintsTest.java
* https://hibernate.atlassian.net/browse/HV-1326
=> HV-1326 Fail fast when the value is null during nested cascaded validation

engine/src/main/java/org/hibernate/validator/internal/cfg/context/ExecutableConstraintMappingContextImpl.java, engine/src/main/java/org/hibernate/validator/internal/metadata/cascading/CascadingTypeParameter.java, engine/src/main/java/org/hibernate/validator/internal/metadata/provider/AnnotationMetaDataProvider.java, engine/src/main/java/org/hibernate/validator/internal/metadata/raw/ConstrainedParameter.java, engine/src/main/java/org/hibernate/validator/internal/metadata/raw/ConstrainedType.java, engine/src/main/java/org/hibernate/validator/internal/xml/ConstrainedExecutableBuilder.java, engine/src/test/java/org/hibernate/validator/test/internal/engine/methodvalidation/AbstractMethodValidationTest.java
* https://hibernate.atlassian.net/browse/HV-1330
=> HV-1330 Fix the merge algorithm when dealing with non cascading CascadingTypeParameter

pom.xml
* https://hibernate.atlassian.net/browse/HV-1335
=> HV-1335 Upgrade assertj-core to 3.7.0 to be consistent with the TCK

engine/src/main/java/org/hibernate/validator/internal/engine/cascading/OptionalDoubleValueExtractor.java, engine/src/main/java/org/hibernate/validator/internal/engine/cascading/OptionalIntValueExtractor.java, engine/src/main/java/org/hibernate/validator/internal/engine/cascading/OptionalLongValueExtractor.java, engine/src/main/java/org/hibernate/validator/internal/engine/cascading/ValueExtractorDescriptor.java, engine/src/main/java/org/hibernate/validator/internal/engine/cascading/ValueExtractorManager.java, engine/src/main/java/org/hibernate/validator/internal/metadata/core/MetaConstraints.java, engine/src/main/java/org/hibernate/validator/internal/util/ReflectionHelper.java, engine/src/main/java/org/hibernate/validator/internal/util/logging/Log.java, engine/src/test/java/org/hibernate/validator/test/internal/engine/cascaded/CustomValueExtractorTest.java, engine/src/test/java/org/hibernate/validator/test/internal/engine/valuehandling/NonGenericContainerValueExtractorTest.java, engine/src/test/java/org/hibernate/validator/test/internal/engine/valuehandling/OptionalPrimitivesValueExtractorTest.java, pom.xml
* https://hibernate.atlassian.net/browse/HV-1339
Requires https://github.com/beanvalidation/beanvalidation-api/pull/107 to compile.
=> HV-1339 Add support for non parameterized type in value extraction

cdi/src/main/java/org/hibernate/validator/internal/cdi/ValidatorFactoryBean.java
* https://hibernate.atlassian.net/browse/HV-1333
Tests are in the TCK: https://github.com/beanvalidation/beanvalidation-tck/pull/101
=> HV-1333 Make value extractors defined in XML CDI enabled

engine/src/main/java/org/hibernate/validator/internal/engine/constraintvalidation/ConstraintValidatorContextImpl.java, engine/src/test/java/org/hibernate/validator/test/constraints/ConstraintValidatorContextImplTest.java, test-utils/src/main/java/org/hibernate/validator/testutil/ConstraintViolationAssert.java
* https://hibernate.atlassian.net/browse/HV-1340
=> HV-1340 Add container element nodes/information to the node builder API

cdi/src/main/java/org/hibernate/validator/internal/cdi/ValidationExtension.java
the CDI environment
* https://hibernate.atlassian.net/browse/HV-1342
=> HV-1342 Use the default ParameterNameProvider in the startup stage of

engine/src/main/java/org/hibernate/validator/internal/metadata/location/TypeArgumentConstraintLocation.java, engine/src/test/java/org/hibernate/validator/test/internal/engine/cascaded/MapExtractorTest.java
* https://hibernate.atlassian.net/browse/HV-1343
=> HV-1343 Fix equals/hashCode implementation of TypeArgumentConstraintLocation

engine/src/main/java/org/hibernate/validator/internal/metadata/aggregated/GroupConversionHelper.java, engine/src/main/java/org/hibernate/validator/internal/metadata/aggregated/MetaDataBuilder.java, tck-runner/pom.xml
* https://hibernate.atlassian.net/browse/HV-1348
=> HV-1348 Add a toString() for GroupConversionHelper

engine/src/test/java/org/hibernate/validator/test/cfg/ConstraintMappingTest.java, engine/src/test/java/org/hibernate/validator/test/cfg/MethodConstraintMappingTest.java, engine/src/test/java/org/hibernate/validator/test/constraints/ConstraintTest.java, engine/src/test/java/org/hibernate/validator/test/constraints/ValidatorResolutionTest.java, engine/src/test/java/org/hibernate/validator/test/internal/engine/methodvalidation/AbstractConstructorValidationTest.java, engine/src/test/java/org/hibernate/validator/test/internal/engine/methodvalidation/AbstractMethodValidationTest.java, engine/src/test/java/org/hibernate/validator/test/internal/engine/methodvalidation/MethodLevelValidationGroupSequenceTest.java, engine/src/test/java/org/hibernate/validator/test/internal/engine/methodvalidation/cascadedgroupvalidation/CascadedMethodLevelValidationGroupSequenceTest.java, test-utils/src/main/java/org/hibernate/validator/testutil/ConstraintViolationAssert.java
* https://hibernate.atlassian.net/browse/HV-1337
=> HV-1337 Test framework adjustments

modules/src/script/setupModules.groovy, tck-runner/pom.xml, tck-runner/src/script/updateStandaloneXml.groovy, tck-runner/src/test/modules/javafx/api/main/module.xml
* https://hibernate.atlassian.net/browse/HV-1354
=> HV-1354 Make JavaFX classes visible when running the TCK in incontainer mode

engine/src/test/java/org/hibernate/validator/test/internal/xml/containerelementtype/ContainerElementTypeConstraintsForFieldXmlMappingTest.java, engine/src/test/java/org/hibernate/validator/test/internal/xml/containerelementtype/ContainerElementTypeConstraintsForGetterXmlMappingTest.java, engine/src/test/java/org/hibernate/validator/test/internal/xml/containerelementtype/ContainerElementTypeConstraintsForParameterXmlMappingTest.java, engine/src/test/java/org/hibernate/validator/test/internal/xml/containerelementtype/ContainerElementTypeConstraintsForReturnValueXmlMappingTest.java
* https://hibernate.atlassian.net/browse/HV-1360
=> HV-1360 Fix various infelicities in container element constraints XML tests

engine/src/main/java/org/hibernate/validator/internal/metadata/descriptor/ConstraintDescriptorImpl.java, pom.xml
* https://hibernate.atlassian.net/browse/HV-1362
Linked with: https://github.com/beanvalidation/beanvalidation-tck/pull/118
=> HV-1362 Add support for @OverridesAttribute default name()

engine/src/main/java/org/hibernate/validator/internal/engine/cascading/ValueExtractorDescriptor.java, engine/src/main/java/org/hibernate/validator/internal/metadata/aggregated/AbstractConstraintMetaData.java, engine/src/main/java/org/hibernate/validator/internal/metadata/core/MetaConstraints.java, engine/src/main/java/org/hibernate/validator/internal/metadata/descriptor/ContainerElementTypeDescriptorImpl.java, engine/src/main/java/org/hibernate/validator/internal/metadata/descriptor/ParameterDescriptorImpl.java, engine/src/main/java/org/hibernate/validator/internal/metadata/descriptor/PropertyDescriptorImpl.java, engine/src/main/java/org/hibernate/validator/internal/metadata/descriptor/ReturnValueDescriptorImpl.java, engine/src/main/java/org/hibernate/validator/internal/metadata/location/TypeArgumentConstraintLocation.java, engine/src/main/java/org/hibernate/validator/internal/metadata/provider/AnnotationMetaDataProvider.java, engine/src/main/java/org/hibernate/validator/internal/util/TypeVariables.java
This will allow HV to be compiled against CR1 of the API.
* https://hibernate.atlassian.net/browse/HV-1383
* https://hibernate.atlassian.net/browse/HV-1385
=> HV-1385 Adjustments on the metadata API following BVAL-655

engine/src/main/java/org/hibernate/validator/internal/engine/ValidatorImpl.java, engine/src/main/java/org/hibernate/validator/internal/metadata/core/MetaConstraint.java, engine/src/main/java/org/hibernate/validator/internal/util/logging/Log.java
* https://hibernate.atlassian.net/browse/HV-1380
=> HV-1380 Wrap ValueExtractor#extractValues() exceptions in ValidationException

engine/src/main/java/org/hibernate/validator/internal/util/logging/Log.java, engine/src/main/java/org/hibernate/validator/internal/xml/ValidationXmlParser.java, engine/src/test/java/org/hibernate/validator/test/internal/engine/cascaded/CustomValueExtractorTest.java, engine/src/test/resources/org/hibernate/validator/test/internal/engine/cascaded/value-extractor-duplicated-validation.xml
- https://hibernate.atlassian.net/browse/HV-1366
=> HV-1366 Declaring the exact same value extractor twice in XML should throw an exception

documentation/src/main/asciidoc/ch07.asciidoc, documentation/src/main/asciidoc/ch11.asciidoc, documentation/src/test/resources/org/hibernate/validator/referenceguide/chapter07/rental-station-mapping.xml
* https://hibernate.atlassian.net/browse/HV-1393
=> HV-1393 Update schema coordinates in the documentation to use BV 2.0 schemas

tck-runner/pom.xml
* https://hibernate.atlassian.net/browse/HV-1394
=> HV-1394 Disable the access log of the security manager by default

engine/src/main/java/org/hibernate/validator/internal/engine/ValidatorImpl.java, engine/src/main/java/org/hibernate/validator/internal/engine/cascading/ValueExtractorHelper.java, engine/src/main/java/org/hibernate/validator/internal/engine/cascading/ValueExtractorManager.java, engine/src/main/java/org/hibernate/validator/internal/metadata/core/MetaConstraint.java, engine/src/main/java/org/hibernate/validator/internal/metadata/core/MetaConstraints.java, engine/src/main/java/org/hibernate/validator/internal/util/logging/Log.java, engine/src/test/java/org/hibernate/validator/test/internal/engine/valuehandling/UnwrappingTest.java
* https://hibernate.atlassian.net/browse/HV-1381
Test cases added in the TCK as part as: https://github.com/beanvalidation/beanvalidation-tck/pull/132
=> HV-1381 Fix value extraction resolution logic for forced and implicit unwrapping

documentation/src/main/asciidoc/index.asciidoc
- https://hibernate.atlassian.net/browse/HV-1399
And the updated PDF:
[hibernate_validator_reference.pdf](https://github.com/hibernate/hibernate-validator/files/1108838/hibernate_validator_reference.pdf)
=> HV-1399 Increase TOC depth for reference guide

engine/src/main/java/org/hibernate/validator/internal/metadata/core/MetaConstraint.java, engine/src/main/java/org/hibernate/validator/internal/metadata/core/MetaConstraints.java
* https://hibernate.atlassian.net/browse/HV-1403
=> HV-1403 Provide container class and type argument index information inthe case of implicit unwrapping

engine/src/main/java/org/hibernate/validator/internal/metadata/core/MetaConstraint.java
* https://hibernate.atlassian.net/browse/HV-1409
=> HV-1409 Fix ContainerClassTypeParameterAndExtractor toString()

engine/src/main/java/org/hibernate/validator/internal/metadata/core/MetaConstraints.java, engine/src/main/java/org/hibernate/validator/internal/metadata/descriptor/ConstraintDescriptorImpl.java, engine/src/main/java/org/hibernate/validator/internal/util/logging/Log.java
* https://hibernate.atlassian.net/browse/HV-1412
=> HV-1412 Take into account value unwrapping API changes

documentation/src/test/java/org/hibernate/validator/referenceguide/chapter07/RentalStation.java, documentation/src/test/java/org/hibernate/validator/referenceguide/chapter11/constraintapi/Car.java
Some cleanup for HV-1391. The build was not working at the time due to API changes...
=> HV-1391 Fix examples in the documentation

engine/src/main/java/org/hibernate/validator/internal/engine/path/NodeImpl.java, engine/src/main/java/org/hibernate/validator/internal/metadata/core/MetaConstraint.java, engine/src/main/java/org/hibernate/validator/path/ContainerElementNode.java, engine/src/test/java/org/hibernate/validator/test/internal/engine/path/NodeImplTest.java
* https://hibernate.atlassian.net/browse/HV-1419
Best reviewed commit per commit.
=> HV-1419 Introduce an HV specific ContainerElementNode with a getValue() method

documentation/src/main/asciidoc/ch13.asciidoc
* https://hibernate.atlassian.net/browse/HV-1248
=> HV-1248 Update the link to the spec now that it is published at a stable place

engine/src/main/java/org/hibernate/validator/internal/cfg/context/CascadableConstraintMappingContextImplBase.java, engine/src/main/java/org/hibernate/validator/internal/cfg/context/ContainerElementConstraintMappingContextImpl.java, engine/src/main/java/org/hibernate/validator/internal/metadata/cascading/CascadingTypeParameter.java, engine/src/main/java/org/hibernate/validator/internal/metadata/provider/AnnotationMetaDataProvider.java, engine/src/main/java/org/hibernate/validator/internal/util/logging/Log.java, engine/src/main/java/org/hibernate/validator/internal/xml/ContainerElementTypeConfigurationBuilder.java, engine/src/test/java/org/hibernate/validator/test/cfg/ProgrammaticContainerElementConstraintsForFieldTest.java, engine/src/test/java/org/hibernate/validator/test/cfg/ProgrammaticContainerElementConstraintsForGetterTest.java, engine/src/test/java/org/hibernate/validator/test/cfg/ProgrammaticContainerElementConstraintsForParameterTest.java, engine/src/test/java/org/hibernate/validator/test/cfg/ProgrammaticContainerElementConstraintsForReturnValueTest.java, engine/src/test/java/org/hibernate/validator/test/internal/engine/cascaded/NestedCascadedConstraintsTest.java, engine/src/test/java/org/hibernate/validator/test/internal/engine/methodvalidation/AbstractMethodValidationTest.java, engine/src/test/java/org/hibernate/validator/test/internal/engine/typeannotationconstraint/TypeAnnotationConstraintTest.java, engine/src/test/java/org/hibernate/validator/test/internal/engine/typeannotationconstraint/TypeAnnotationDefinedOnAGenericTypeArgumentTest.java, engine/src/test/java/org/hibernate/validator/test/internal/engine/valueextraction/NestedTypeArgumentsValueExtractorTest.java, engine/src/test/java/org/hibernate/validator/test/internal/xml/containerelementtype/ContainerElementTypeConstraintsForFieldXmlMappingTest.java, engine/src/test/java/org/hibernate/validator/test/internal/xml/containerelementtype/ContainerElementTypeConstraintsForGetterXmlMappingTest.java, engine/src/test/java/org/hibernate/validator/test/internal/xml/containerelementtype/ContainerElementTypeConstraintsForParameterXmlMappingTest.java, engine/src/test/java/org/hibernate/validator/test/internal/xml/containerelementtype/ContainerElementTypeConstraintsForReturnValueXmlMappingTest.java
* https://hibernate.atlassian.net/browse/HV-1315
* https://hibernate.atlassian.net/browse/HV-1384
=> HV-1315 Disable container element array support

engine/src/main/java/org/hibernate/validator/HibernateValidatorPermission.java, engine/src/main/java/org/hibernate/validator/internal/metadata/aggregated/FieldCascadable.java, engine/src/main/java/org/hibernate/validator/internal/metadata/aggregated/GetterCascadable.java, engine/src/main/java/org/hibernate/validator/internal/metadata/location/FieldConstraintLocation.java, engine/src/main/java/org/hibernate/validator/internal/metadata/location/GetterConstraintLocation.java, tck-runner/src/test/resources/test.policy
* https://hibernate.atlassian.net/browse/HV-1431
=> HV-1431 Clean up for constraint locations

engine/src/test/java/org/hibernate/validator/test/internal/engine/path/specexample/Author.java, engine/src/test/java/org/hibernate/validator/test/internal/engine/path/specexample/AvailableInStore.java, engine/src/test/java/org/hibernate/validator/test/internal/engine/path/specexample/Book.java, engine/src/test/java/org/hibernate/validator/test/internal/engine/path/specexample/Library.java, engine/src/test/java/org/hibernate/validator/test/internal/engine/path/specexample/NewPasswordsIdentical.java, engine/src/test/java/org/hibernate/validator/test/internal/engine/path/specexample/NonEmpty.java, engine/src/test/java/org/hibernate/validator/test/internal/engine/path/specexample/OldAndNewPasswordsDifferent.java, engine/src/test/java/org/hibernate/validator/test/internal/engine/path/specexample/Review.java, engine/src/test/java/org/hibernate/validator/test/internal/engine/path/specexample/SecurityChecking.java, engine/src/test/java/org/hibernate/validator/test/internal/engine/path/specexample/SpecExamplePropertyPathTest.java
* https://hibernate.atlassian.net/browse/HV-1371
=> HV-1371 Add missing examples to the specexample PropertyPath test

engine/src/main/java/org/hibernate/validator/internal/constraintvalidators/bv/EmailValidator.java
* https://hibernate.atlassian.net/browse/HV-1433
=> HV-1433 Don't apply regular expression for @Email if pattern() isn't given

engine/src/main/xsd/validation-mapping-2.0.xsd, pom.xml
* https://hibernate.atlassian.net/browse/HV-1434
=> HV-1434 Make order of <constraint> and <container-element-type> consistent

integration/pom.xml, integration/src/test/resources/arquillian.xml, modules/pom.xml, modules/src/main/modules/wildfly-current-patch.xml, modules/src/main/modules/wildfly-next-patch.xml, modules/src/script/setupModules.groovy, pom.xml
* https://hibernate.atlassian.net/browse/HV-1440
And also run the integration tests for WF 11.x.
=> HV-1440 Provide patch file for WF 11.x

documentation/src/main/asciidoc/ch11.asciidoc
* https://hibernate.atlassian.net/browse/HV-1420
=> HV-1420 Reference Marko's blog post about how to add constraints as external libraries

engine/src/main/java/org/hibernate/validator/internal/engine/ValidationContext.java
* https://hibernate.atlassian.net/browse/HV-1456
=> HV-1456 Fix comments mixed up by Eclipse refactorings

engine/src/main/java/org/hibernate/validator/internal/cfg/context/CascadableConstraintMappingContextImplBase.java, engine/src/test/java/org/hibernate/validator/test/cfg/CascadingWithConstraintMappingTest.java
* https://hibernate.atlassian.net/browse/HV-1442
=> HV-1442 Fix root cascading metadata for arrays in the programmatic API

engine/src/main/java/org/hibernate/validator/internal/engine/ValidatorImpl.java
* https://hibernate.atlassian.net/browse/HV-1455
Quick explanation: right now, we are a bit inconsistent about when the sanity checks are applied: sometimes it's after testing that there are no constraints, sometimes it's after. We should be consistent in 2 ways:
* for all the different methods
* for all the different types of sanity checks
=> HV-1455 Be more consistent about when sanity checks are applied

pom.xml
=> Add Marko to the developers declared in the root pom.xml

documentation/pom.xml, documentation/src/main/asciidoc/ch01.asciidoc, pom.xml
* https://hibernate.atlassian.net/browse/HV-1462
=> HV-1462 Provide patch file for WildFly 11 Beta1

engine/src/main/java/org/hibernate/validator/internal/engine/ValidatorImpl.java, engine/src/main/java/org/hibernate/validator/internal/engine/ValueContext.java, engine/src/main/java/org/hibernate/validator/internal/metadata/core/MetaConstraint.java, engine/src/test/java/org/hibernate/validator/test/internal/engine/valueextraction/UnwrapValidatedValueTest.java, engine/src/test/java/org/hibernate/validator/test/internal/engine/valueextraction/UnwrappingTest.java, engine/src/test/java/org/hibernate/validator/test/internal/engine/valueextraction/model/Company.java
* https://hibernate.atlassian.net/browse/HV-1471
=> HV-1471 Properly reset the context after constraint validation

build-config/src/main/resources/checkstyle.xml, pom.xml
- https://hibernate.atlassian.net/browse/HV-1476
=> HV-1476 Updating checkstyle version and config

engine/src/main/java/org/hibernate/validator/cfg/AnnotationDef.java, engine/src/main/java/org/hibernate/validator/cfg/ConstraintDef.java, engine/src/main/java/org/hibernate/validator/internal/util/privilegedactions/GetAnnotationParameters.java
* https://hibernate.atlassian.net/browse/HV-1486
=> HV-1486 Add a toString() to AnnotationParameters

engine/src/main/java/org/hibernate/validator/internal/engine/constraintvalidation/ConstraintValidatorDescriptor.java, engine/src/main/java/org/hibernate/validator/internal/metadata/descriptor/ConstraintDescriptorImpl.java, engine/src/test/java/org/hibernate/validator/test/internal/engine/serialization/ConstraintViolationSerializationTest.java, engine/src/test/java/org/hibernate/validator/test/internal/engine/serialization/SerializableClass.java
* https://hibernate.atlassian.net/browse/HV-1485
=> HV-1485 Make ConstraintViolationImpl serializable again

documentation/src/main/asciidoc/ch02.asciidoc, documentation/src/main/asciidoc/ch10.asciidoc, documentation/src/test/java/org/hibernate/validator/referenceguide/chapter10/Book.java, documentation/src/test/java/org/hibernate/validator/referenceguide/chapter10/Library.java, documentation/src/test/java/org/hibernate/validator/referenceguide/chapter10/LibraryTest.java
* https://hibernate.atlassian.net/browse/HV-1415
* https://hibernate.atlassian.net/browse/HV-1417
=> Some documentation improvements

pom.xml
* https://hibernate.atlassian.net/browse/HV-1488
=> HV-1488 Upgrade WildFly to 11.0.0.CR1

engine/src/main/java/org/hibernate/validator/internal/engine/ValidatorImpl.java
https://hibernate.atlassian.net/projects/HV/issues/HV-1492
=> HV-1492 Invoking log method with correct argument order

documentation/src/main/asciidoc/ch09.asciidoc, documentation/src/test/java/org/hibernate/validator/referenceguide/chapter09/BootstrappingTest.java, documentation/src/test/java/org/hibernate/validator/referenceguide/chapter09/MyFastTraversableResolver.java, documentation/src/test/java/org/hibernate/validator/referenceguide/chapter09/validation-DisableTraversableResolverResultCache.xml, engine/src/main/java/org/hibernate/validator/HibernateValidatorConfiguration.java, engine/src/main/java/org/hibernate/validator/HibernateValidatorContext.java, engine/src/main/java/org/hibernate/validator/internal/engine/ConfigurationImpl.java, engine/src/main/java/org/hibernate/validator/internal/engine/ValidatorContextImpl.java, engine/src/main/java/org/hibernate/validator/internal/engine/ValidatorFactoryImpl.java, engine/src/main/java/org/hibernate/validator/internal/engine/ValidatorImpl.java, engine/src/main/java/org/hibernate/validator/internal/engine/resolver/AbstractTraversableHolder.java, engine/src/main/java/org/hibernate/validator/internal/engine/resolver/CachingJPATraversableResolverForSingleValidation.java, engine/src/main/java/org/hibernate/validator/internal/engine/resolver/CachingTraversableResolverForSingleValidation.java, engine/src/main/java/org/hibernate/validator/internal/engine/resolver/JPATraversableResolver.java, engine/src/main/java/org/hibernate/validator/internal/engine/resolver/TraversableResolvers.java, engine/src/main/java/org/hibernate/validator/internal/engine/resolver/TraverseAllTraversableResolver.java, engine/src/test/java/org/hibernate/validator/test/internal/engine/traversableresolver/CachedTraversableResolverTest.java, engine/src/test/java/org/hibernate/validator/test/internal/engine/traversableresolver/JpaTraversableResolverTest.java, engine/src/test/resources/org/hibernate/validator/test/internal/engine/traversableresolver/validation-CachedTraversableResolverTest.xml
* https://hibernate.atlassian.net/browse/HV-1487
=>  HV-1487 Allow to disable the TraversableResolver result cache

documentation/src/main/asciidoc/ch01.asciidoc
https://hibernate.atlassian.net/browse/HV-1479
=> HV-1479 Adding note on issues with java.xml.ws.annotation module

engine/src/main/java/org/hibernate/validator/internal/engine/path/PathImpl.java
* https://hibernate.atlassian.net/browse/HV-1507
* https://hibernate.atlassian.net/browse/HV-1508
=> HV-1507 Avoid resetting the PathImpl.hashCode() when setting the property value

engine/src/main/java/org/hibernate/validator/internal/engine/constraintvalidation/ClassBasedValidatorDescriptor.java, engine/src/main/java/org/hibernate/validator/internal/engine/constraintvalidation/ConstraintValidatorDescriptor.java, engine/src/main/java/org/hibernate/validator/internal/engine/constraintvalidation/LambdaBasedValidatorDescriptor.java, engine/src/main/java/org/hibernate/validator/internal/util/logging/Log.java, engine/src/main/java/org/hibernate/validator/internal/xml/ValidationBootstrapParameters.java
* https://hibernate.atlassian.net/browse/HV-1509
=> HV-1509 Reference constraint validator factory consistently

engine/src/main/java/org/hibernate/validator/internal/engine/ValidatorFactoryImpl.java, engine/src/main/java/org/hibernate/validator/internal/util/logging/Log.java, engine/src/main/java/org/hibernate/validator/messageinterpolation/ParameterMessageInterpolator.java
* https://hibernate.atlassian.net/browse/HV-1323
=> HV-1323 Avoid the warn message when ParameterMessageInterpolator is used

annotation-processor/src/main/java/org/hibernate/validator/ap/internal/util/ConstraintHelper.java, engine/src/main/java/org/hibernate/validator/cfg/AnnotationDef.java, engine/src/main/java/org/hibernate/validator/internal/engine/ValidatorImpl.java, engine/src/main/java/org/hibernate/validator/internal/engine/groups/ValidationOrderGenerator.java, engine/src/main/java/org/hibernate/validator/internal/metadata/core/ConstraintHelper.java, engine/src/main/java/org/hibernate/validator/internal/metadata/descriptor/ConstraintDescriptorImpl.java, engine/src/main/java/org/hibernate/validator/internal/metadata/descriptor/ElementDescriptorImpl.java, engine/src/main/java/org/hibernate/validator/internal/metadata/provider/AnnotationMetaDataProvider.java, engine/src/main/java/org/hibernate/validator/internal/util/annotation/AnnotationProxy.java, engine/src/main/java/org/hibernate/validator/internal/xml/ContainerElementTypeConfigurationBuilder.java, engine/src/main/java/org/hibernate/validator/internal/xml/MetaConstraintBuilder.java, test-utils/src/main/java/org/hibernate/validator/testutil/ValidationInvocationHandler.java
Hi @gsmet here are a few cleanups here and there. Mostly around creating empty arrays or lists with one element. This probably wouldn't be a visible performance improvement though :smiley:
=> Making some code cleanups

engine/src/main/java/org/hibernate/validator/cfg/AnnotationDef.java, engine/src/test/java/org/hibernate/validator/test/internal/engine/messageinterpolation/TooBigMessageTest.java, jqassistant/rules.xml, pom.xml
* https://hibernate.atlassian.net/browse/HV-1519
=> HV-1519 Fix the jqassistant build

engine/src/main/java/org/hibernate/validator/internal/engine/ValidationContext.java
- https://hibernate.atlassian.net/browse/HV-1520
=> HV-1520 Update *ProcessUnit equals to compare to passed object class

engine/src/main/java/org/hibernate/validator/internal/engine/ValidationContext.java
- https://hibernate.atlassian.net/browse/HV-1527
=> HV-1527 Separate Group and Path processed units in ValidationContext

annotation-processor/src/main/java/org/hibernate/validator/ap/internal/util/ConstraintHelper.java, annotation-processor/src/main/java/org/hibernate/validator/ap/internal/util/TypeNames.java, annotation-processor/src/test/java/org/hibernate/validator/ap/ConstraintValidationProcessorTest.java, annotation-processor/src/test/java/org/hibernate/validator/ap/testmodel/ModelWithCodePointLengthConstraints.java
- https://hibernate.atlassian.net/browse/HV-1530
=> HV-1530 Adding CodePointLength to supported AP types

annotation-processor/src/test/java/org/hibernate/validator/ap/ConstraintValidationProcessorTest.java
These are the ones that were asked to be changed in https://github.com/hibernate/hibernate-validator/pull/893
=> Fix some minor formatting issues

engine/src/main/java/org/hibernate/validator/internal/engine/ValidatorImpl.java, engine/src/main/java/org/hibernate/validator/internal/engine/constraintvalidation/ConstraintTree.java, engine/src/main/java/org/hibernate/validator/internal/engine/messageinterpolation/LocalizedMessage.java
* https://hibernate.atlassian.net/browse/HV-1533
Found out while working with Marko on the benchmarking of this PR: https://github.com/hibernate/hibernate-validator/pull/889 .
+ a small change requested by John.
=> HV-1533 Some small performance improvements

engine/src/main/java/org/hibernate/validator/cfg/context/AnnotationProcessingOptions.java, engine/src/main/java/org/hibernate/validator/cfg/context/PropertyConstraintMappingContext.java, engine/src/main/java/org/hibernate/validator/cfg/context/TypeConstraintMappingContext.java, engine/src/main/java/org/hibernate/validator/internal/cfg/context/PropertyConstraintMappingContextImpl.java, engine/src/main/java/org/hibernate/validator/internal/cfg/context/TypeConstraintMappingContextImpl.java
This reverts commit 26ea075495457ee6d4e6ccf254cd26797c0d3a04.
* https://hibernate.atlassian.net/browse/HV-1546
=> HV-1546 Reintroduce AnnotationProcessingOptions for compatibility's sake

.travis.yml, pom.xml
https://hibernate.atlassian.net/browse/HV-1549
https://hibernate.atlassian.net/browse/HV-1550
=> Travis build improvements

engine/src/main/java/org/hibernate/validator/internal/engine/valueextraction/ValueExtractorDescriptor.java, engine/src/main/java/org/hibernate/validator/internal/util/TypeHelper.java, engine/src/test/java/org/hibernate/validator/test/constraints/annotations/SizeOnParameterizedAndNonParameterizedContainersTest.java
- https://hibernate.atlassian.net/browse/HV-1551
=> HV-1551 @Size annotation fails on not parametrized Map property

osgi/felixtest/pom.xml, pom.xml
We have some issues with one of our OSGi tests randomly failing. I hope this will help to fix the issue.
* https://hibernate.atlassian.net/browse/HV-1555
* https://hibernate.atlassian.net/browse/HV-1556
=>  HV-1555  HV-1556 Fixes related to OSGi testing

engine/src/main/java/org/hibernate/validator/internal/constraintvalidators/bv/notempty/NotEmptyValidatorForCollection.java, engine/src/main/java/org/hibernate/validator/internal/constraintvalidators/bv/notempty/NotEmptyValidatorForMap.java, engine/src/main/java/org/hibernate/validator/internal/constraintvalidators/bv/size/SizeValidatorForCollection.java, engine/src/main/java/org/hibernate/validator/internal/constraintvalidators/bv/size/SizeValidatorForMap.java, engine/src/main/java/org/hibernate/validator/internal/constraintvalidators/hv/UniqueElementsValidator.java, engine/src/main/java/org/hibernate/validator/internal/engine/constraintvalidation/ConstraintValidatorManager.java, engine/src/main/java/org/hibernate/validator/internal/util/TypeHelper.java, engine/src/test/java/org/hibernate/validator/test/internal/engine/constraintvalidation/ConstraintValidatorResolutionTest.java
* https://hibernate.atlassian.net/browse/HV-1551
Better reviewed commit per commit as some commits are just here to fix typos.
=> HV-1551 Proper fix

tck-runner/src/test/java/org/hibernate/validator/tckrunner/securitymanager/TckRunner.java, tck-runner/src/test/resources/test.policy
=> Added more info to the tck runner comments

pom.xml
* https://hibernate.atlassian.net/browse/HV-1573
=> HV-1573 Ignore the Maven wrapper directory in the license check

documentation/src/test/java/org/hibernate/validator/referenceguide/chapter02/containerelement/custom/Gear.java
https://hibernate.atlassian.net/browse/HV-1572
=> HV-1572 Make the custom container type value extractor example extra clear

pom.xml
* https://hibernate.atlassian.net/browse/HV-1570
=> HV-1570 Update JBoss Logging to 3.3.2.Final

documentation/pom.xml, documentation/src/main/asciidoc/ch01.asciidoc
* https://hibernate.atlassian.net/browse/HV-1565
=> HV-1565 Add missing security manager permissions to the documentation

cdi/pom.xml, cdi/src/test/java/org/hibernate/validator/test/cdi/internal/methodvalidation/inheritance/InvalidConfiguredClassInheritanceMethodValidationTest.java, distribution/pom.xml, documentation/pom.xml, documentation/src/main/asciidoc/ch01.asciidoc, engine/pom.xml, integration/pom.xml, integration/src/test/resources/arquillian.xml, modules/pom.xml, modules/src/main/modules/wildfly-current-patch.xml, modules/src/main/modules/wildfly-secondary-patch.xml, osgi/felixtest/pom.xml, pom.xml
* https://hibernate.atlassian.net/browse/HV-1576
and then:
* https://hibernate.atlassian.net/browse/HV-1581
* https://hibernate.atlassian.net/browse/HV-1582
Better reviewed commit per commit, especially because the first one rejiggers things around.
=> HV-1576 Upgrade the integration tests and the base WildFly version to WildFly 12

README.md, documentation/pom.xml, documentation/src/main/asciidoc/ch01.asciidoc, pom.xml
* https://hibernate.atlassian.net/browse/HV-1583
=> HV-1583 Update javax.el dependency to 3.0.1-b09

tck-runner/pom.xml
* https://hibernate.atlassian.net/browse/HV-1576
* https://hibernate.atlassian.net/browse/HV-1584
=> Build fixes

modules/pom.xml
* https://hibernate.atlassian.net/browse/HV-1580
=> HV-1580 Fix the path of the setupModules.groovy script

osgi/integrationtest/src/test/java/org/hibernate/validator/osgi/integrationtest/KarafFeaturesAreInstallableTest.java, osgi/integrationtest/src/test/java/org/hibernate/validator/osgi/integrationtest/OsgiIntegrationTest.java, osgi/karaf-features/src/main/features/features.xml, pom.xml
* https://hibernate.atlassian.net/browse/HV-1593
* https://hibernate.atlassian.net/browse/HV-1594
=>  HV-1593  HV-1594 Assorted Karaf features improvements

engine/src/main/java/org/hibernate/validator/internal/engine/ValidationContext.java, engine/src/main/java/org/hibernate/validator/internal/metadata/aggregated/BeanMetaData.java, engine/src/main/java/org/hibernate/validator/internal/metadata/aggregated/BeanMetaDataImpl.java, engine/src/main/java/org/hibernate/validator/internal/metadata/aggregated/ExecutableMetaData.java, engine/src/main/java/org/hibernate/validator/internal/metadata/aggregated/ReturnValueMetaData.java, engine/src/main/java/org/hibernate/validator/internal/metadata/aggregated/ValidatableParametersMetaData.java, engine/src/main/java/org/hibernate/validator/internal/metadata/facets/Validatable.java
@gunnarmorling so you were right on this one.
I thought I could pave the way to being more clever in the future with how I did things but it's not possible so let's keep it simple and remove the unnecessary code.
=> HV-1587 Simplify how already validated bean tracking is disabled/enabled

documentation/src/main/asciidoc/ch06.asciidoc, documentation/src/test/java/org/hibernate/validator/referenceguide/chapter06/constraintvalidatorpayload/ZipCodeValidator.java, engine/src/main/java/org/hibernate/validator/constraintvalidation/HibernateConstraintValidatorContext.java, engine/src/main/java/org/hibernate/validator/constraintvalidation/HibernateConstraintValidatorInitializationContext.java, engine/src/main/java/org/hibernate/validator/internal/engine/ValidationContext.java, engine/src/main/java/org/hibernate/validator/internal/engine/ValidatorFactoryImpl.java, engine/src/main/java/org/hibernate/validator/internal/engine/constraintvalidation/ComposingConstraintTree.java, engine/src/main/java/org/hibernate/validator/internal/engine/constraintvalidation/ConstraintValidatorContextImpl.java, engine/src/main/java/org/hibernate/validator/internal/engine/constraintvalidation/HibernateConstraintValidatorInitializationContextImpl.java, engine/src/main/java/org/hibernate/validator/internal/engine/constraintvalidation/SimpleConstraintTree.java, engine/src/test/java/org/hibernate/validator/test/constraints/ConstraintValidatorContextImplTest.java, engine/src/test/java/org/hibernate/validator/test/constraintvalidator/ConstraintValidatorPayloadTest.java, engine/src/test/java/org/hibernate/validator/test/internal/engine/constraintvalidation/ConstraintValidatorManagerTest.java, engine/src/test/java/org/hibernate/validator/testutils/ConstraintValidatorInitializationHelper.java, engine/src/test/java/org/hibernate/validator/testutils/ValidatorUtil.java
https://hibernate.atlassian.net/browse/HV-1595
@gsmet @marko-bekhta Like promised. That one should be easy.
=> HV-1595 Move ConstraintValidatorPayload to ConstraintValidatorContext

pom.xml
* https://hibernate.atlassian.net/browse/HV-1578
=> HV-1578 Disable the generation of @Generated annotation for JBoss Logging

pom.xml
* https://hibernate.atlassian.net/browse/HV-1622
=> HV-1622 Make WildFly 13 our default WildFly target

engine/src/main/java/org/hibernate/validator/internal/metadata/provider/AnnotationMetaDataProvider.java, engine/src/main/java/org/hibernate/validator/internal/properties/javabean/JavaBeanParameter.java
* https://hibernate.atlassian.net/browse/HV-1636
=> HV-1636 Avoid instantiating unnecessary objects during constraint metadata creation

engine/src/main/resources/org/hibernate/validator/ValidationMessages_de.properties, engine/src/main/resources/org/hibernate/validator/ValidationMessages_nl.properties
* https://hibernate.atlassian.net/browse/HV-1637
=> HV-1637 Fix variable name in @DecimalMax error message for German and Dutch

engine/src/main/java/org/hibernate/validator/internal/engine/ServiceLoaderBasedConstraintMappingContributor.java, engine/src/main/java/org/hibernate/validator/internal/metadata/core/ConstraintHelper.java, engine/src/main/java/org/hibernate/validator/internal/metadata/core/MetaConstraints.java, engine/src/main/java/org/hibernate/validator/internal/util/logging/Log.java, engine/src/main/java/org/hibernate/validator/internal/xml/config/ValidationXmlParser.java, engine/src/main/java/org/hibernate/validator/internal/xml/mapping/MappingXmlParser.java
* https://hibernate.atlassian.net/browse/HV-1652
=> HV-1652 Fix a few theoretical null pointer dereference issues

pom.xml
* https://hibernate.atlassian.net/browse/HV-1659
=> HV-1659 Upgrade WildFly to 14.0.1 - 6.0

engine/src/main/java/org/hibernate/validator/internal/metadata/core/ConstraintHelper.java
* https://hibernate.atlassian.net/browse/HV-1668
* https://hibernate.atlassian.net/browse/HV-1669
* https://hibernate.atlassian.net/browse/HV-1671
=> Assorted minor changes related to constraints registration

engine/src/main/java/org/hibernate/validator/resourceloading/PlatformResourceBundleLocator.java
=> Typo in PlatformResourceBundleLocator

engine/src/main/java/org/hibernate/validator/internal/util/logging/Log.java
* https://hibernate.atlassian.net/browse/HV-1687
@gunnarmorling interested in your feedback on this one. Rationale explained in the issue.
=> HV-1687 Reduce bootstrap log verbosity

distribution/pom.xml, integration/pom.xml, pom.xml
* https://hibernate.atlassian.net/browse/HV-1693
=> HV-1693 Ensure compatibility with JDK 12

build-config/src/main/resources/checkstyle.xml, pom.xml
https://hibernate.atlassian.net//browse/HV-1702
=> HV-1702 Upgrade to checkstyle 8.18 and maven-checkstyle-plugin 3.0.0

engine/src/main/java/org/hibernate/validator/internal/engine/PredefinedScopeValidatorContextImpl.java, engine/src/test/java/org/hibernate/validator/test/predefinedscope/PredefinedScopeValidatorFactoryTest.java
* https://hibernate.atlassian.net/browse/HV-1719
=> HV-1719 Accept setting per-validator TraversableResolver with PredefinedScopeValidatorFactoryImpl

.travis.yml, engine/src/main/java/org/hibernate/validator/internal/engine/ValidatorFactoryConfigurationHelper.java, engine/src/test/java/org/hibernate/validator/test/predefinedscope/PredefinedScopeConstraintDefinitionContributorTest.java
https://hibernate.atlassian.net/browse/HV-1721
=> HV-1721 Take into account HV-specific config with predefined scope VF

engine/src/main/java/org/hibernate/validator/PredefinedScopeHibernateValidatorFactory.java, engine/src/main/java/org/hibernate/validator/internal/engine/PredefinedScopeValidatorFactoryImpl.java
* https://hibernate.atlassian.net/browse/HV-1726
I think I have been too pedantic on this one.
=> HV-1726 Make PredefinedScopeHibernateValidatorFactory extend HibernateValidatorFactory

pom.xml
https://hibernate.atlassian.net/browse/HV-1728
=> HV-1728 Upgrade to WildFly 17.0.1.Final

pom.xml
* https://hibernate.atlassian.net/browse/HV-1724
=> HV-1724 Update to OpenJFX 11.0.2

pom.xml
https://hibernate.atlassian.net/browse/HV-1727
=> HV-1727 Update Jackson Databind test dependency to 2.9.9.2

engine/src/test/java/org/hibernate/validator/test/predefinedscope/PredefinedScopeValidatorFactoryTest.java
* https://hibernate.atlassian.net/browse/HV-1733
=> HV-1733 Fix locale settings of PredefinedScopeValidatorFactoryTest

pom.xml
* https://hibernate.atlassian.net/browse/HV-1738
=> HV-1738 Update Jackson test dependency to 2.9.10

documentation/pom.xml, documentation/src/main/asciidoc/index.asciidoc, pom.xml
https://hibernate.atlassian.net/browse/HV-1744
=> HV-1744 Use auto-expanding entries in the documentation TOC

osgi/integrationtest/pom.xml, osgi/integrationtest/src/test/java/org/hibernate/validator/osgi/integrationtest/KarafFeaturesAreInstallableTest.java, osgi/integrationtest/src/test/java/org/hibernate/validator/osgi/integrationtest/OsgiIntegrationTest.java, pom.xml
https://hibernate.atlassian.net/browse/HV-1753
=> HV-1753 Force Karaf and Pax-Exam to use https for Maven Central

engine/src/main/java/org/hibernate/validator/internal/metadata/provider/AnnotationMetaDataProvider.java, engine/src/main/java/org/hibernate/validator/internal/util/ExecutableHelper.java, engine/src/main/java/org/hibernate/validator/parameternameprovider/ParanamerParameterNameProvider.java, test-utils/src/main/java/org/hibernate/validator/testutil/PrefixableParameterNameProvider.java
See https://hibernate.atlassian.net/browse/HV-1762
=> HV-1762 Avoid cloning overhead from Method.getParameterTypes()

engine/src/main/resources/org/hibernate/validator/ValidationMessages_de.properties
https://hibernate.atlassian.net/browse/HV-1771
=> HV-1771 Fix DecimalMin message German translation

engine/src/main/java/org/hibernate/validator/internal/engine/AbstractConfigurationImpl.java, engine/src/test/java/org/hibernate/validator/test/internal/bootstrap/ConfigurationReuseHibernateValidatorTest.java
* https://hibernate.atlassian.net/browse/HV-1772
=> HV-1772 Allow overriding MessageInterpolator when config is reused

engine/src/main/java/org/hibernate/validator/internal/engine/resolver/TraversableResolvers.java
Signed-off-by: Gaurav Gupta <gaurav.gupta@payara.fish>
https://hibernate.atlassian.net/browse/HV-1781
=> HV-1781 Fix Jakarta Persistence class presence test

pom.xml, tck-runner/src/test/java/org/hibernate/validator/tckrunner/securitymanager/arquillian/LocalSecurityManagerTestingExecutionEvent.java
https://hibernate.atlassian.net/browse/HV-1783
=> HV-1783 Upgrade to Arquillian 1.7.0.Alpha1

annotation-processor/src/main/java/org/hibernate/validator/ap/internal/util/ConstraintHelper.java, annotation-processor/src/main/java/org/hibernate/validator/ap/internal/util/TypeNames.java, annotation-processor/src/test/java/org/hibernate/validator/ap/ConstraintValidationProcessorTest.java, annotation-processor/src/test/java/org/hibernate/validator/ap/testmodel/ModelWithNormalizedConstraints.java, documentation/src/main/asciidoc/ch02.asciidoc, engine/src/main/java/org/hibernate/validator/cfg/defs/NormalizedDef.java, engine/src/main/java/org/hibernate/validator/constraints/Normalized.java, engine/src/main/java/org/hibernate/validator/internal/constraintvalidators/hv/NormalizedValidator.java, engine/src/main/java/org/hibernate/validator/internal/metadata/core/BuiltinConstraint.java, engine/src/main/java/org/hibernate/validator/internal/metadata/core/ConstraintHelper.java, engine/src/main/resources/org/hibernate/validator/ValidationMessages.properties, engine/src/test/java/org/hibernate/validator/test/internal/constraintvalidators/MessagePropertiesTest.java, engine/src/test/java/org/hibernate/validator/test/internal/constraintvalidators/PredefinedScopeAllConstraintsTest.java, engine/src/test/java/org/hibernate/validator/test/internal/constraintvalidators/hv/NormalizedValidatorTest.java
https://hibernate.atlassian.net/browse/HV-1780
Port of https://github.com/hibernate/hibernate-validator/pull/1099 to master.
=> HV-1780 Add @Normalized contraint that validates unicode normalization form

pom.xml
* https://hibernate.atlassian.net/browse/HV-1792
=> HV-1792 Upgrade to Bean Validation TCK 3.0.0

distribution/pom.xml
https://hibernate.atlassian.net/browse/HV-1795
=> HV-1795 Remove link to JavaMoney javadoc

Jenkinsfile, engine/src/test/java/org/hibernate/validator/test/internal/engine/methodvalidation/AbstractMethodValidationTest.java, engine/src/test/java/org/hibernate/validator/test/internal/engine/methodvalidation/AnnotationBasedMethodValidationTest.java, osgi/felixtest/pom.xml, osgi/felixtest/src/test/java/org/hibernate/validator/osgi/felix/FelixCDIIT.java, osgi/integrationtest/pom.xml, osgi/integrationtest/src/test/java/org/hibernate/validator/osgi/integrationtest/KarafFeaturesAreInstallableTest.java, osgi/integrationtest/src/test/java/org/hibernate/validator/osgi/integrationtest/OsgiIntegrationTest.java, pom.xml, tck-runner/pom.xml, tck-runner/src/test/java/org/hibernate/validator/tckrunner/securitymanager/arquillian/LocalSecurityManagerTestingExecutionEvent.java, tck-runner/src/test/resources/test.policy
* [HV-1810](https://hibernate.atlassian.net/browse/HV-1810): Upgrade to Arquillian 1.6
* [HV-1809](https://hibernate.atlassian.net/browse/HV-1809): Upgrade to TestNG 6.14.3
* [HV-1807](https://hibernate.atlassian.net/browse/HV-1807): Add Maven profile to improve contributor experience on Intellij IDEA
* [HV-1806](https://hibernate.atlassian.net/browse/HV-1806): Use the local repository from the Maven build in OSGi/WildFly integration tests
* [HV-1805](https://hibernate.atlassian.net/browse/HV-1805): Add a Jenkinsfile to test multiple JDKs from a single job
This is mostly a backport of #1129. The main difference is that this upgrades to Arquillian 1.6: we were using 1.1 on this branch, and 1.7.Alpha1 on master.
=> [Branch 6.1] HV-1805 + HV-1806 + HV-1807 + HV-1809 + HV-1810  Jenkinsfile + various build improvements

engine/src/main/resources/org/hibernate/validator/ValidationMessages_zh_CN.properties
https://hibernate.atlassian.net/browse/HV-1815
=> HV-1815 Fix DecimalMax and DecimalMin in zh_CN translation

engine/src/test/java/org/hibernate/validator/test/internal/constraintvalidators/hv/ScriptAssertValidatorTest.java, pom.xml
https://hibernate.atlassian.net/browse/HV-1817
So that DependaBot stops spamming us.
=> HV-1817 Upgrade to checkstyle 8.38

engine/src/main/java/org/hibernate/validator/internal/engine/ValidatorFactoryConfigurationHelper.java, engine/src/test/java/org/hibernate/validator/test/cfg/NonHibernateValidatorConfigTest.java
It was supported before and got broken. It stayed unnoticed because we
didn't have a test for that so adding a proper test too.
=> HV-1821 Support using a non-Hibernate Validator configuration class - master

engine/src/main/java/org/hibernate/validator/internal/engine/ValidatorFactoryConfigurationHelper.java, engine/src/test/java/org/hibernate/validator/test/cfg/NonHibernateValidatorConfigTest.java
It was supported before and got broken. It stayed unnoticed because we
didn't have a test for that so adding a proper test too.
=> HV-1821 Support using a non-Hibernate Validator configuration class - 6.2

engine/src/main/java/org/hibernate/validator/internal/engine/ValidatorFactoryImpl.java, engine/src/test/java/org/hibernate/validator/test/cfg/NonHibernateValidatorConfigTest.java
It was supported before and got broken. It stayed unnoticed because we
didn't have a test for that so adding a proper test too.
=> HV-1821 Support using a non-Hibernate Validator configuration class - 6.0

engine/src/main/java/org/hibernate/validator/internal/engine/ValidatorFactoryConfigurationHelper.java, engine/src/test/java/org/hibernate/validator/test/cfg/NonHibernateValidatorConfigTest.java
It was supported before and got broken. It stayed unnoticed because we
didn't have a test for that so adding a proper test too.
=> HV-1821 Support using a non-Hibernate Validator configuration class - 6.1

engine/src/main/java/org/hibernate/validator/internal/constraintvalidators/AbstractEmailValidator.java, engine/src/main/java/org/hibernate/validator/internal/util/DomainNameUtil.java, engine/src/test/java/org/hibernate/validator/test/internal/constraintvalidators/hv/EmailValidatorTest.java
https://hibernate.atlassian.net/browse/HV-1833
=> HV-1833 DomainNameUtil issues java.lang.StackOverflowError on very large error (@Email validation)

engine/src/main/java/org/hibernate/validator/resourceloading/AggregateResourceBundle.java, engine/src/main/java/org/hibernate/validator/resourceloading/AggregateResourceBundleLocator.java, engine/src/main/java/org/hibernate/validator/resourceloading/PlatformResourceBundleLocator.java, engine/src/test/java/org/hibernate/validator/resourceloading/AggregateResourceBundleTest.java, engine/src/test/resources/org/hibernate/validator/resourceloading/AggregateResourceBundleTestBundle1.properties, engine/src/test/resources/org/hibernate/validator/resourceloading/AggregateResourceBundleTestBundle2.properties
https://hibernate.atlassian.net/browse/HV-1828
Supersedes https://github.com/hibernate/hibernate-validator/pull/1152 .
@jpep-in could you have a look at my changes? I think it should make things a bit better. I also fixed a couple of preexisting issues.
=> HV-1828 ContributorValidationMessages compatible with UTF-8 properties

engine/src/main/java/org/hibernate/validator/resourceloading/AggregateResourceBundle.java, engine/src/main/java/org/hibernate/validator/resourceloading/AggregateResourceBundleLocator.java, engine/src/main/java/org/hibernate/validator/resourceloading/PlatformResourceBundleLocator.java, engine/src/test/java/org/hibernate/validator/resourceloading/AggregateResourceBundleTest.java, engine/src/test/resources/org/hibernate/validator/resourceloading/AggregateResourceBundleTestBundle1.properties, engine/src/test/resources/org/hibernate/validator/resourceloading/AggregateResourceBundleTestBundle2.properties
https://hibernate.atlassian.net/browse/HV-1828
=> HV-1828 for 6.2

CONTRIBUTING.md, Jenkinsfile, README.md, documentation/src/main/asciidoc/ch01.asciidoc, documentation/src/main/asciidoc/ch11.asciidoc, documentation/src/main/asciidoc/ch14.asciidoc, engine/src/test/java/org/hibernate/validator/test/constraints/boolcomposition/AllowedSSN.java, engine/src/test/java/org/hibernate/validator/test/constraints/boolcomposition/BoolCompositeConstraintTest.java, engine/src/test/java/org/hibernate/validator/test/constraints/boolcomposition/ExcludedSSNList.java, engine/src/test/java/org/hibernate/validator/test/constraints/boolcomposition/Person.java, engine/src/test/java/org/hibernate/validator/test/constraints/boolcomposition/SSN.java, engine/src/test/java/org/hibernate/validator/test/internal/engine/valueextraction/CascadedOptionalTest.java, performance/README.md
https://hibernate.atlassian.net/browse/HV-1837
=> HV-1837 Language rework initiative

CONTRIBUTING.md, Jenkinsfile, README.md, documentation/src/main/asciidoc/ch01.asciidoc, documentation/src/main/asciidoc/ch11.asciidoc, documentation/src/main/asciidoc/ch14.asciidoc, engine/src/test/java/org/hibernate/validator/test/constraints/boolcomposition/AllowedSSN.java, engine/src/test/java/org/hibernate/validator/test/constraints/boolcomposition/BoolCompositeConstraintTest.java, engine/src/test/java/org/hibernate/validator/test/constraints/boolcomposition/ExcludedSSNList.java, engine/src/test/java/org/hibernate/validator/test/constraints/boolcomposition/Person.java, engine/src/test/java/org/hibernate/validator/test/constraints/boolcomposition/SSN.java, engine/src/test/java/org/hibernate/validator/test/internal/engine/valueextraction/CascadedOptionalTest.java, performance/README.md
https://hibernate.atlassian.net/browse/HV-1837
=> HV-1837 Language rework initiative - 6.2

README.md, pom.xml
* https://hibernate.atlassian.net/browse/HV-1844
=> HV-1844 Upgrade Jakarta EL to 4.0.1

Jenkinsfile
https://hibernate.atlassian.net/browse/HV-1848
=> HV-1848 Set up SSH config as part of the Jenkinsfile

Jenkinsfile
https://hibernate.atlassian.net/browse/HV-1848
Backport of #1179
=> Backport HV-1848 to branch 6.2 - Set up SSH config as part of the Jenkinsfile

Jenkinsfile
https://hibernate.atlassian.net/browse/HV-1848
Backport of #1179
=> Backport HV-1848 to branch 6.1 - Set up SSH config as part of the Jenkinsfile

pom.xml
https://hibernate.atlassian.net/browse/HV-1858
=> HV-1858 Deploy artifacts to OSSRH instead of JBoss repository

Jenkinsfile
https://hibernate.atlassian.net/browse/HV-1860
=> HV-1860 Add GitHub SSH keys to SSH agent during Jenkinsfile release

Jenkinsfile
https://hibernate.atlassian.net/browse/HV-1860
Backport of #1189
=> Backport HV-1860 to branch 6.2 - Add GitHub SSH keys to SSH agent during Jenkinsfile release

Jenkinsfile
https://hibernate.atlassian.net/browse/HV-1860
Backport of #1189
=> Backport HV-1860 to branch 6.1 - Add GitHub SSH keys to SSH agent during Jenkinsfile release

pom.xml
see https://hibernate.atlassian.net/browse/HV-1861
=> HV-1861 Switch to the nexus-staging-maven-plugin

Jenkinsfile, build-config/pom.xml, distribution/pom.xml, documentation/pom.xml, integration/pom.xml, osgi/felixtest/pom.xml, osgi/integrationtest/pom.xml, performance/pom.xml, pom.xml, tck-runner/pom.xml
https://hibernate.atlassian.net/browse/HV-1871
=> HV-1871 Sign published artifacts

pom.xml
https://hibernate.atlassian.net/browse/HV-1872
Follow-up on #1204 
Let's run CI on JDK19 this time...
=> HV-1872 Follow-up: fix JDK19 tests

Jenkinsfile, build-config/pom.xml, distribution/pom.xml, documentation/pom.xml, integration/pom.xml, osgi/felixtest/pom.xml, osgi/integrationtest/pom.xml, performance/pom.xml, pom.xml, tck-runner/pom.xml
https://hibernate.atlassian.net/browse/HV-1871
Backport of #1200
=> Backport HV-1871 to branch 6.2 - Sign published artifacts

Jenkinsfile, build-config/pom.xml, distribution/pom.xml, documentation/pom.xml, integration/pom.xml, osgi/felixtest/pom.xml, osgi/integrationtest/pom.xml, performance/pom.xml, pom.xml, tck-runner/pom.xml
https://hibernate.atlassian.net/browse/HV-1871
Backport of #1200
=> Backport HV-1871 to branch 6.1 - Sign published artifacts

Jenkinsfile, cdi/src/test/java/org/hibernate/validator/test/cdi/internal/methodvalidation/getter/DeliveryService.java, documentation/src/test/java/org/hibernate/validator/referenceguide/chapter02/containerelement/map/Car.java, documentation/src/test/java/org/hibernate/validator/referenceguide/chapter02/containerelement/nested/Car.java, documentation/src/test/java/org/hibernate/validator/referenceguide/chapter02/containerelement/set/Car.java, documentation/src/test/java/org/hibernate/validator/referenceguide/chapter03/parameterscriptassert/Car.java, documentation/src/test/java/org/hibernate/validator/referenceguide/chapter09/FixedClockProvider.java, documentation/src/test/java/org/hibernate/validator/referenceguide/chapter12/context/MyFutureValidator.java, documentation/src/test/java/org/hibernate/validator/referenceguide/chapter12/context/MyFutureValidatorMessageParameter.java, documentation/src/test/java/org/hibernate/validator/referenceguide/chapter12/nodenameprovider/PersonSerializationTest.java, integration/pom.xml, pom.xml
https://hibernate.atlassian.net/browse/HV-1864
=> HV-1864 Prepare for JDK 17 releasing - 6.2

pom.xml
https://hibernate.atlassian.net/browse/HV-1874
=> HV-1874 Bump Log4j test dependency to 2.17.1

pom.xml
https://hibernate.atlassian.net/browse/HV-1874
=> HV-1874 Bump Log4j test dependency to 2.17.1 - 6.2

Jenkinsfile, cdi/src/test/java/org/hibernate/validator/test/cdi/internal/methodvalidation/getter/DeliveryService.java, documentation/src/test/java/org/hibernate/validator/referenceguide/chapter02/containerelement/map/Car.java, documentation/src/test/java/org/hibernate/validator/referenceguide/chapter02/containerelement/nested/Car.java, documentation/src/test/java/org/hibernate/validator/referenceguide/chapter02/containerelement/set/Car.java, documentation/src/test/java/org/hibernate/validator/referenceguide/chapter03/parameterscriptassert/Car.java, documentation/src/test/java/org/hibernate/validator/referenceguide/chapter09/FixedClockProvider.java, documentation/src/test/java/org/hibernate/validator/referenceguide/chapter12/context/MyFutureValidator.java, documentation/src/test/java/org/hibernate/validator/referenceguide/chapter12/context/MyFutureValidatorMessageParameter.java, documentation/src/test/java/org/hibernate/validator/referenceguide/chapter12/nodenameprovider/PersonSerializationTest.java, pom.xml
https://hibernate.atlassian.net/browse/HV-1864
https://hibernate.atlassian.net/browse/HV-1875
https://hibernate.atlassian.net/browse/HV-1876
=> HV-1864 HV-1875 HV-1876 Prepare for JDK 17 releasing

Jenkinsfile, jenkins/release.groovy
https://hibernate.atlassian.net/browse/HV-1877
Backport of #1209
=> Backport HV-1877 to branch 6.1 - Move the release job to a separate Jenkinsfile

Jenkinsfile, jenkins/release.groovy
https://hibernate.atlassian.net/browse/HV-1877
Backport of #1209
=> Backport HV-1877 to branch 6.2 - Move the release job to a separate Jenkinsfile

Jenkinsfile, build-config/pom.xml, distribution/pom.xml, documentation/pom.xml, engine/src/test/java/org/hibernate/validator/test/internal/engine/methodvalidation/AbstractMethodValidationTest.java, engine/src/test/java/org/hibernate/validator/test/internal/engine/methodvalidation/AnnotationBasedMethodValidationTest.java, integration/pom.xml, jenkins/release.groovy, osgi/felixtest/pom.xml, osgi/felixtest/src/test/java/org/hibernate/validator/osgi/felix/FelixCDIIT.java, osgi/integrationtest/pom.xml, osgi/integrationtest/src/test/java/org/hibernate/validator/osgi/integrationtest/KarafFeaturesAreInstallableTest.java, osgi/integrationtest/src/test/java/org/hibernate/validator/osgi/integrationtest/OsgiIntegrationTest.java, performance/pom.xml, pom.xml, tck-runner/pom.xml, tck-runner/src/test/java/org/hibernate/validator/tckrunner/securitymanager/arquillian/LocalSecurityManagerTestingExecutionEvent.java, tck-runner/src/test/resources/test.policy
* [HV-1879](https://hibernate.atlassian.net/browse/HV-1879): Backport Jenkinsfiles to 6.0
* [HV-1877](https://hibernate.atlassian.net/browse/HV-1877): Move the release job to a separate Jenkinsfile
* [HV-1871](https://hibernate.atlassian.net/browse/HV-1871): Sign published artifacts
=> Backport HV-1871 + HV-1877 + HV-1879 to branch 6.0 : introduce Jenkinsfile + artifact signing

engine/src/main/java/org/hibernate/validator/internal/constraintvalidators/bv/time/future/FutureValidatorForDate.java, engine/src/main/java/org/hibernate/validator/internal/constraintvalidators/bv/time/futureorpresent/FutureOrPresentValidatorForDate.java, engine/src/main/java/org/hibernate/validator/internal/constraintvalidators/bv/time/past/PastValidatorForDate.java, engine/src/main/java/org/hibernate/validator/internal/constraintvalidators/bv/time/pastorpresent/PastOrPresentValidatorForDate.java, engine/src/test/java/org/hibernate/validator/test/internal/constraintvalidators/bv/time/ClockProviderFutureTest.java, engine/src/test/java/org/hibernate/validator/test/internal/constraintvalidators/bv/time/ClockProviderPastTest.java, engine/src/test/java/org/hibernate/validator/test/internal/constraintvalidators/bv/time/FixedClockProvider.java, engine/src/test/java/org/hibernate/validator/test/internal/constraintvalidators/bv/time/JavaSqlDateTest.java
https://hibernate.atlassian.net/browse/HV-1878
=> HV-1878 Bring back java.sql.Date support - 6.0

engine/src/main/java/org/hibernate/validator/internal/constraintvalidators/AbstractEmailValidator.java, engine/src/main/java/org/hibernate/validator/internal/util/DomainNameUtil.java, engine/src/test/java/org/hibernate/validator/test/internal/constraintvalidators/hv/EmailValidatorTest.java
https://hibernate.atlassian.net/browse/HV-1833
=> HV-1833 DomainNameUtil issues java.lang.StackOverflowError on very large error (@Email validation) - 6.0

.gitignore, .mvn/jvm.options
https://hibernate.atlassian.net/browse/HV-1864
Not tested, we'd need a release for that.
=> HV-1864 Follow-up - Make sure we can release with JDK 17

.gitignore, .mvn/jvm.options
https://hibernate.atlassian.net/browse/HV-1864
Backport of #1221
Not tested, we'd need a release for that.
=> Backport HV-1864 follow-up to branch 6.2 - Make sure we can release with JDK 17

documentation/pom.xml, pom.xml
https://hibernate.atlassian.net/browse/HV-1883
=> HV-1883 Upgrade to asciidoctor-maven-plugin 2.2.2

engine/src/main/java/org/hibernate/validator/internal/metadata/descriptor/ConstraintDescriptorImpl.java, engine/src/main/java/org/hibernate/validator/internal/util/CollectionHelper.java
[https://hibernate.atlassian.net/browse/HV-1884](https://hibernate.atlassian.net/browse/HV-1884)
=> HV-1884 Composing constraints order is unpredictable

engine/src/main/java/org/hibernate/validator/internal/metadata/descriptor/ConstraintDescriptorImpl.java, engine/src/main/java/org/hibernate/validator/internal/util/CollectionHelper.java
https://hibernate.atlassian.net/browse/HV-1884
=> HV-1884 Use LinkedHashSet to make composingConstraints order predictable/guaranteed by insertion order - 6.2

integration/src/test/resources/arquillian.xml, tck-runner/src/script/updateStandaloneXml.groovy, tck-runner/src/test/resources/arquillian.xml
https://hibernate.atlassian.net/browse/HV-1886
=> HV-1886 Fix tck-runner incontainer build for main

pom.xml, tck-runner/pom.xml
In passing, remove the Jakarta staging repository.
https://hibernate.atlassian.net/browse/HV-1887
=> HV-1887 Make Java 11 the base Java version

documentation/pom.xml
https://hibernate.atlassian.net/browse/HV-1889
=> HV-1889 Fix imagesdir in documentation

documentation/pom.xml, documentation/src/main/asciidoc/ch01.asciidoc, documentation/src/main/asciidoc/ch11.asciidoc, documentation/src/main/asciidoc/ch12.asciidoc, documentation/src/main/asciidoc/pr01.asciidoc, pom.xml
https://hibernate.atlassian.net/browse/HV-1890
https://hibernate.atlassian.net/browse/HV-1889
=> HV-1889 HV-1890 7.0

documentation/src/main/asciidoc/ch01.asciidoc, documentation/src/main/asciidoc/ch11.asciidoc, documentation/src/main/asciidoc/ch12.asciidoc, documentation/src/main/asciidoc/pr01.asciidoc, pom.xml
https://hibernate.atlassian.net/browse/HV-1890
=> HV-1890 Update versions in documentation

documentation/src/main/asciidoc/ch01.asciidoc
https://hibernate.atlassian.net/browse/HV-1892
=> HV-1892 Update Java 9 section in documentation

integration/pom.xml, pom.xml, tck-runner/pom.xml
https://hibernate.atlassian.net/browse/HV-1893
=> HV-1893 Make test suite locale independent

integration/pom.xml, pom.xml, tck-runner/pom.xml
https://hibernate.atlassian.net/browse/HV-1893
=> HV-1893 Make test suite locale independent - 7.0

integration/pom.xml, pom.xml, tck-runner/pom.xml
https://hibernate.atlassian.net/browse/HV-1893
=> HV-1893 Make test suite locale independent - 6.2

cdi/pom.xml, pom.xml
* https://hibernate.atlassian.net/browse/HV-1895
* Also updated several other properties to released artifacts
* Tested with GlassFish 7.0.0-SNAPSHOT
=> HV-1895 Updated maven-bundle-plugin to 5.1.4

pom.xml
https://hibernate.atlassian.net/browse/HV-1896
=> HV-1896 Upgrade Jackson Databind test dependency to 2.13.2.2

pom.xml
https://hibernate.atlassian.net/browse/HV-1904
=> HV-1904 Update Jakarta EE 10 dependencies to stable versions

engine/src/test/java17/org/hibernate/validator/test/constraints/records/RecordConstrainedTest.java
https://hibernate.atlassian.net/browse/HV-1905
- add composing constraints tests with correct/incorrect targets
- add cascading constraint test
While checking the reported issue I've added a couple more tests, and it probably wouldn't hurt to do a bit more testing - hence this PR 😄
=> HV-1905 Add more tests for record validation

pom.xml
https://hibernate.atlassian.net/browse/HV-1908
=> HV-1908 Update CDI API to 4.0.1 and Weld to 5.0.0.SP2

pom.xml
https://hibernate.atlassian.net/browse/HV-1906
=> HV-1906 Update Bean Validation API to 3.0.2 and TCK to 3.0.1

documentation/src/main/asciidoc/ch09.asciidoc, documentation/src/test/java/org/hibernate/validator/referenceguide/chapter09/LoggingConfigurationTest.java, documentation/src/test/java/org/hibernate/validator/referenceguide/chapter09/validation-ShowValidatedValueInLogs.xml, engine/src/main/java/org/hibernate/validator/BaseHibernateValidatorConfiguration.java, engine/src/main/java/org/hibernate/validator/HibernateValidatorContext.java, engine/src/main/java/org/hibernate/validator/internal/engine/AbstractConfigurationImpl.java, engine/src/main/java/org/hibernate/validator/internal/engine/PredefinedScopeValidatorContextImpl.java, engine/src/main/java/org/hibernate/validator/internal/engine/PredefinedScopeValidatorFactoryImpl.java, engine/src/main/java/org/hibernate/validator/internal/engine/ValidatorContextImpl.java, engine/src/main/java/org/hibernate/validator/internal/engine/ValidatorFactoryConfigurationHelper.java, engine/src/main/java/org/hibernate/validator/internal/engine/ValidatorFactoryImpl.java, engine/src/main/java/org/hibernate/validator/internal/engine/ValidatorFactoryScopedContext.java, engine/src/main/java/org/hibernate/validator/internal/engine/constraintvalidation/ComposingConstraintTree.java, engine/src/main/java/org/hibernate/validator/internal/engine/constraintvalidation/SimpleConstraintTree.java, engine/src/main/java/org/hibernate/validator/internal/engine/validationcontext/AbstractValidationContext.java, engine/src/main/java/org/hibernate/validator/internal/engine/validationcontext/ValidationContext.java, engine/src/main/java/org/hibernate/validator/internal/engine/validationcontext/ValidatorScopedContext.java, engine/src/main/java/org/hibernate/validator/internal/util/logging/Log.java, engine/src/test/java/org/hibernate/validator/test/internal/engine/constraintvalidation/LogValidatedValueConfigurationTest.java, engine/src/test/resources/log4j2.properties
https://hibernate.atlassian.net/browse/HV-1903
built on top of original PR https://github.com/hibernate/hibernate-validator/pull/1264 by OP
=> HV-1903 Make flexible log tracing in the ConstraintTree class

documentation/src/test/java/org/hibernate/validator/referenceguide/chapter12/getterselectionstrategy/FluentGetterPropertySelectionStrategy.java, engine/src/main/java/org/hibernate/validator/internal/properties/DefaultGetterPropertySelectionStrategy.java, engine/src/main/java/org/hibernate/validator/internal/util/privilegedactions/GetMethodFromGetterNameCandidates.java, engine/src/main/java/org/hibernate/validator/spi/properties/GetterPropertySelectionStrategy.java, engine/src/test/java/org/hibernate/validator/test/internal/xml/MultipleGetterCandidates.java, engine/src/test/java/org/hibernate/validator/test/internal/xml/XmlMappingTest.java, engine/src/test/java/org/hibernate/validator/test/properties/GetterPropertySelectionStrategyTest.java, engine/src/test/resources/org/hibernate/validator/test/internal/xml/hv-1853-mapping.xml
https://hibernate.atlassian.net/browse/HV-1853
=> HV-1853 Fix inconsistency of getter method detection in GetterPropertySelectionStrategy

Jenkinsfile, pom.xml
https://hibernate.atlassian.net/browse/HV-1914
=> HV-1914 Test against JDK 20 (early access)

pom.xml
https://hibernate.atlassian.net/browse/HV-1919
https://hibernate.atlassian.net/browse/HV-1920
=> HV-1919 HV-1920 - Various upgrades

engine/src/main/resources/org/hibernate/validator/ValidationMessages_fr.properties
Linked to https://hibernate.atlassian.net/browse/HV-1932
=> HV-1932 Incomplete @Positive annotation's default message in fr

engine/src/main/resources/org/hibernate/validator/ValidationMessages_fr.properties
(cherry picked from commit 566486b6388145e750c6c82db58f4c3dcf21e5aa)
https://hibernate.atlassian.net/browse/HV-1932
=> HV-1932 Incomplete @Positive annotation's default message in fr - 6.2

engine/src/main/resources/org/hibernate/validator/ValidationMessages_fr.properties
(cherry picked from commit 566486b6388145e750c6c82db58f4c3dcf21e5aa)
https://hibernate.atlassian.net/browse/HV-1932
=> HV-1932 Incomplete @Positive annotation's default message in fr - 7.0

documentation/pom.xml, pom.xml
https://hibernate.atlassian.net/browse/HV-1934
=> HV-1934 Move documentation to Google Analytics 4

documentation/pom.xml, pom.xml
https://hibernate.atlassian.net/browse/HV-1934
Backport of #1296
=> Backport HV-1934 to branch 7.0 - Move documentation to Google Analytics 4

documentation/pom.xml, pom.xml
https://hibernate.atlassian.net/browse/HV-1934
Backport of #1296
=> Backport HV-1934 to branch 6.2 - Move documentation to Google Analytics 4

documentation/pom.xml, pom.xml
https://hibernate.atlassian.net/browse/HV-1934
Backport of #1296
=> Backport HV-1934 to branch 6.1 - Move documentation to Google Analytics 4

Jenkinsfile, pom.xml
https://hibernate.atlassian.net/browse/HV-1954
=> HV-1954 Test Hibernate Validator against JDK 22

engine/src/main/java/org/hibernate/validator/internal/properties/javabean/JavaBeanExecutable.java, engine/src/main/java/org/hibernate/validator/internal/properties/javabean/JavaBeanParameter.java, engine/src/test/java/org/hibernate/validator/test/internal/engine/methodvalidation/MethodInnerClassConstructorValidationTest.java, engine/src/test/java/org/hibernate/validator/test/internal/metadata/descriptor/ConstructorDescriptorTest.java, pom.xml
https://hibernate.atlassian.net/browse/HV-1939
=> HV-1939 Annotations on constructors of named classes declared in method get ignored

engine/src/main/resources/org/hibernate/validator/ValidationMessages_pt.properties, engine/src/main/resources/org/hibernate/validator/ValidationMessages_pt_BR.properties, engine/src/main/resources/org/hibernate/validator/ValidationMessages_pt_PT.properties
https://hibernate.atlassian.net/browse/HV-1941
Added European Portuguese validation messages; I moved the existing Brazilian Portuguese messages to the common Portuguese locale where applicable.
=> HV-1941 european portuguese validation messages (version 6.2)

Jenkinsfile
https://hibernate.atlassian.net/browse/HV-1969
=> HV-1969 Test Hibernate Validator against JDK 23

Jenkinsfile, pom.xml
https://hibernate.atlassian.net/browse/HV-1990
=> HV-1990 Test Hibernate Validator against JDK 24

engine/src/main/java/org/hibernate/validator/internal/engine/constraintvalidation/ConstraintValidatorContextImpl.java, engine/src/main/java/org/hibernate/validator/internal/engine/constraintvalidation/CrossParameterConstraintValidatorContextImpl.java, engine/src/test/java/org/hibernate/validator/test/el/CustomViolationExpressionLanguageFeatureLevelTest.java
https://hibernate.atlassian.net/browse/HV-1978
=> HV-1978 Propagated EL level to iterable nodes

pom.xml
=> Followup on HV-1980 Bump gpg maven plugin to 3.2.4   -  6.2

pom.xml
=> Followup on HV-1980 Bump gpg maven plugin to 3.2.4   -  8.0

jenkins/release.groovy, pom.xml
=> Backport of HV-1980 to 7.0 -  Use env variable name instead of the passphrase in GPG config

engine/src/main/java/org/hibernate/validator/internal/engine/path/PathImpl.java, engine/src/main/java/org/hibernate/validator/internal/engine/validationcontext/AbstractValidationContext.java, engine/src/test/java/org/hibernate/validator/test/internal/engine/path/PathImplTest.java
https://hibernate.atlassian.net/browse/HV-1993
rebased and squashed version of https://github.com/hibernate/hibernate-validator/pull/1333
=> HV-1993 reduces calls to isSubPathOf/rework isSubPathOf logic

pom.xml, tck-runner/pom.xml
https://hibernate.atlassian.net/browse/HV-2011
besides Arquillian dependencies config update it also includes the other updates suggested by https://github.com/hibernate/hibernate-validator/pull/1381
=> HV-2011 Update Arquillian dependency management configuration

integration/pom.xml, jenkins/nightly/Jenkinsfile, pom.xml, tck-runner/pom.xml
https://hibernate.atlassian.net/browse/HV-2007
adds a build reproducibility check to the build
adds a profile to skip some steps, even though the validator build is already relatively fast, even with all the tests.
=> HV-2007 Add a nightly job to verify the build reproducibility

jenkins/release.groovy
https://hibernate.atlassian.net/browse/HV-1981
=> HV-1981 Bump minimum maven version for a release script

pom.xml
Thanks for noticing that @yrodiere 😄 🏆 
=> Update developer info for marko.bekhta

integrationtest/wildfly/pom.xml, pom.xml
https://hibernate.atlassian.net/browse/HV-2017
=> HV-2017 Use wildfly-preview-dist in integration tests to test against the Jakarta EE 11

.gitignore, Jenkinsfile, distribution/src/main/assembly/dist.xml, jenkins/release.groovy
=> Update release scripts

pom.xml
https://hibernate.atlassian.net/browse/WEBSITE-667
=> Keep the original URLs for project page and scm in sub-module flattened POMs

parents/public/pom.xml, test-utils/pom.xml
https://hibernate.atlassian.net/browse/HV-1997
=> HV-1997 Do not publish any parent POMs

MAINTAINERS.md, build/reports/pom.xml, pom.xml, relocation/annotation-processor/pom.xml, relocation/cdi/pom.xml, relocation/engine/pom.xml, relocation/pom.xml
This should also enable snapshot publishing.
=> Update nexus staging plugin configuration

README.md
aaand a few others while we are at it
=> Add Reproducible Builds badge

build/build-config/pom.xml, distribution/pom.xml, pom.xml
https://hibernate.atlassian.net/browse/HV-2022
=> HV-2022 Include assertj javadocs for test utils

parents/public/pom.xml
https://hibernate.atlassian.net/browse/HV-2022
=> HV-2022 Skip unpacking the element lists when javadocs are skipped

distribution/pom.xml, parents/internal/pom.xml, pom.xml
https://hibernate.atlassian.net/browse/HV-2022
=> HV-2022 Include javadocs generation in reproducibility-check profile

.github/dependabot.yml
- to include shrinkwrap resolver
=> Update dependabot rules

pom.xml
https://hibernate.atlassian.net/browse/HV-2033
https://github.com/hibernate/hibernate-validator/pull/1431
=> HV-2033 Test against wildfly-preview 33.0.1.Final

pom.xml
https://hibernate.atlassian.net/browse/HV-2041
=> HV-2041 Update to new versions of hibernate-infra extensions/theme that depend on AsciidoctorJ 3.0

.github/hibernate-github-bot.yml
to address new formats in which the title is generated
=> Update hibernate GitHub bot title pattern

engine/src/main/java/org/hibernate/validator/internal/metadata/aggregated/CascadingMetaDataBuilder.java, engine/src/main/java/org/hibernate/validator/internal/metadata/provider/AnnotationMetaDataProvider.java, engine/src/test/java/org/hibernate/validator/test/internal/engine/groups/conversion/AbstractGroupConversionTest.java
https://hibernate.atlassian.net/browse/HV-2029
=> HV-2029 Allow same group convert rules on the methods in class hierarchies

distribution/pom.xml, distribution/src/main/assembly/dist.xml
https://hibernate.atlassian.net/browse/HV-2044
=> HV-2044 Include rendered javadocs in the distribution package

.github/dependabot.yml
=> Add maven plugin dependency to the build dependency group in the dependabot rules

Jenkinsfile, pom.xml
https://hibernate.atlassian.net/browse/HV-2057
=> HV-2057 Add Sonar stage to the build

pom.xml
https://hibernate.atlassian.net/browse/HV-2051
=> HV-2051 Spotless: use a cache dir per module and not single in the root

engine/src/main/java/org/hibernate/validator/internal/constraintvalidators/bv/money/MaxValidatorForMonetaryAmount.java, engine/src/main/java/org/hibernate/validator/internal/constraintvalidators/bv/money/MinValidatorForMonetaryAmount.java, engine/src/main/java/org/hibernate/validator/internal/engine/messageinterpolation/el/BeanMethodsELContext.java, engine/src/main/java/org/hibernate/validator/internal/engine/messageinterpolation/el/BeanPropertiesElContext.java, engine/src/main/java/org/hibernate/validator/internal/engine/messageinterpolation/el/VariablesELContext.java, engine/src/main/java/org/hibernate/validator/internal/engine/path/PathImpl.java, engine/src/main/java/org/hibernate/validator/internal/util/DomainNameUtil.java, engine/src/main/java/org/hibernate/validator/overview.html
https://hibernate.atlassian.net/browse/HV-2057
=> HV-2057 Addressing more Sonar reports

.github/dependabot.yml
https://hibernate.atlassian.net/browse/HV-2059
=> HV-2059 Add develocity extensions to the build dependency group

pom.xml
https://hibernate.atlassian.net/browse/HV-2064
=> HV-2064 Upgrade jboss-logging-tools to 3.0.3.Final

performance/README.md
Commit 96f274ac276664f2c5b3d65c8aebb72e832b27ff moved bunch of files. This PR adjusts sources to changes.
=> Update broken references

documentation/src/main/asciidoc/ch03.asciidoc
(cherry picked from commit 4965992187f1caaffb1982c8df28329bf86af5e1)
https://hibernate.atlassian.net/browse/HV-2066
=> Backport of HV-2066 to 8.0 Update documentation section 3.1.1

engine/src/main/java/org/hibernate/validator/internal/constraintvalidators/bv/NotBlankValidator.java
https://hibernate.atlassian.net/browse/HV-1955
=> HV-1955 Use String#isBlank instead of trim in the NotBlankValidator

integrationtest/wildfly/src/test/java/org/hibernate/validator/integration/wildfly/ejb/EjbIT.java
https://hibernate.atlassian.net/browse/HV-1754
=> HV-1754 Re-enable EjbIT when all tested versions of WildFly have fixed WFL-11566

engine/src/main/java/org/hibernate/validator/overview.html
=> Make spec link in the javadoc overview clickable

documentation/src/main/asciidoc/ch12.asciidoc
https://hibernate.atlassian.net/browse/HV-1829
=> HV-1829 Remove mentions of the ConstraintDefinitionContributor from the docs

engine/pom.xml, engine/src/main/java/org/hibernate/validator/internal/util/Version.java, pom.xml
https://hibernate.atlassian.net/browse/HV-1931
https://hibernate.atlassian.net/browse/HV-2062
Let's use the same approach we have in Search (and recently in Tools) to set the version. 
=> HV-1931 Use maven-injection-plugin to set the version string

Jenkinsfile, pom.xml
https://hibernate.atlassian.net/browse/HV-2069
=> HV-2069 Test against JDK 25

distribution/src/main/assembly/dist.xml
=> Exclude more files from the dist package

documentation/pom.xml
to match what's done in the main branch
=> Specify an explicit plexus-utils dependency for `copy-maven-plugin`

Jenkinsfile
=> Stop publishing snapshots backport to 7.0

Jenkinsfile
=> Stop publishing snapshots backport to 6.1

Jenkinsfile
=> Stop publishing snapshots backport to 6.0

CONTRIBUTING.md, README.md, pom.xml
https://hibernate.atlassian.net/browse/HV-2077
=> HV-2077 Align content of CONTRIBUTING.md with what's in other projects

Jenkinsfile
=> Backport to 8.0 Check that the branch name follows a simple pattern / Require approval for Jenkins builds on PRs from external contributors

Jenkinsfile
=> Backport to 6.2 Check that the branch name follows a simple pattern / Require approval for Jenkins builds on PRs from external contributors

.github/dependabot.yml, .github/workflows/ci-report.yml, .github/workflows/ci.yml
=> Use SHA instead of versions in GH actions

pom.xml
https://hibernate.atlassian.net/browse/HV-2078
Bump version.org.apache.groovy from 4.0.24 to 4.0.25
Bumps `version.org.apache.groovy` from 4.0.24 to 4.0.25.
Updates `org.apache.groovy:groovy-jsr223` from 4.0.24 to 4.0.25
- [Commits](https://github.com/apache/groovy/commits)
Updates `org.apache.groovy:groovy` from 4.0.24 to 4.0.25
- [Commits](https://github.com/apache/groovy/commits)
Updates `org.apache.groovy:groovy-ant` from 4.0.24 to 4.0.25
- [Commits](https://github.com/apache/groovy/commits)
---
- dependency-name: org.apache.groovy:groovy-jsr223 dependency-type: direct:production update-type: version-update:semver-patch
- dependency-name: org.apache.groovy:groovy dependency-type: direct:production update-type: version-update:semver-patch
- dependency-name: …
=> HV-2078 Bump Apache Groovy to 4.0.25

jenkins/nightly/Jenkinsfile
=> Increase nightly job timeout and move it to a different timeslot

pom.xml
https://hibernate.atlassian.net/browse/HV-2084
and align corresponding version properties
=> HV-2084 Bump Jakarta EE BOM to 11.0.0-M5

pom.xml
https://hibernate.atlassian.net/browse/HV-2090
=> HV-2090 Update to OpenJFX to 17.0.14

.mvn/develocity.xml
=> Switch to the Commonhaus Develocity instance

CONTRIBUTING.md, Jenkinsfile, README.md, jenkins/nightly/Jenkinsfile
=> Update remaining Hibernate Develocity URLs to point to Commonhaus instance

.github/workflows/ci.yml, Jenkinsfile
=> Use a develocity url from the env variable if available

pom.xml
https://hibernate.atlassian.net/browse/HV-2095
=> HV-2095 Upgrade hibernate-asciidoctor-theme to 5.0.6.Final

documentation/pom.xml, pom.xml
https://hibernate.atlassian.net/browse/HV-2104 (HIB-155)
=> HV-2104 Remove Google Analytics

documentation/pom.xml, pom.xml
https://hibernate.atlassian.net/browse/HV-2107
=> HV-2107 Enable copytocliboard extension from hibernate-asciidoctor-extensions

pom.xml
https://hibernate.atlassian.net/browse/HV-2108
=> HV-2108 Test against wildfly-preview 36.0.1.Final

pom.xml
https://hibernate.atlassian.net/browse/HV-2096
=> HV-2096 Use altReleaseDeploymentRepository to keep the flattened poms clean

annotation-processor/pom.xml, bom/pom.xml, build/build-config/pom.xml, build/enforcer/pom.xml, build/reports/pom.xml, cdi/pom.xml, distribution/pom.xml, documentation/pom.xml, engine/pom.xml, integrationtest/java/modules/cdi/pom.xml, integrationtest/java/modules/no-el/pom.xml, integrationtest/java/modules/simple/pom.xml, integrationtest/java/modules/test-utils/pom.xml, integrationtest/wildfly/pom.xml, parents/internal/pom.xml, parents/public/pom.xml, performance/pom.xml, pom.xml, tck-runner/pom.xml, test-utils/pom.xml
=> Switch to 9.1.0-SNAPSHOT in the main branch

.mvn/wrapper/maven-wrapper.properties, pom.xml
https://hibernate.atlassian.net/browse/HV-2115
=> HV-2115 Use Maven 3.9.10 as a required minimum version for the build

engine/src/main/java/org/hibernate/validator/internal/engine/MessageInterpolatorContext.java, engine/src/main/java/org/hibernate/validator/internal/engine/ValidationContext.java, engine/src/main/java/org/hibernate/validator/internal/engine/ValidatorFactoryImpl.java, engine/src/main/java/org/hibernate/validator/internal/engine/constraintvalidation/ComposingConstraintTree.java, engine/src/main/java/org/hibernate/validator/internal/engine/constraintvalidation/ConstraintValidatorContextImpl.java, engine/src/main/java/org/hibernate/validator/internal/engine/constraintvalidation/ConstraintViolationCreationContext.java, engine/src/main/java/org/hibernate/validator/internal/engine/constraintvalidation/SimpleConstraintTree.java, engine/src/main/java/org/hibernate/validator/internal/util/logging/Log.java, engine/src/main/java/org/hibernate/validator/internal/util/privilegedactions/GetEnvOrSystemVariableValue.java, engine/src/main/java/org/hibernate/validator/messageinterpolation/AbstractMessageInterpolator.java, engine/src/test/java/org/hibernate/validator/test/constraints/ConstraintValidatorContextImplTest.java, engine/src/test/java/org/hibernate/validator/test/internal/engine/constraintvalidation/HibernateConstraintValidatorContextTest.java, engine/src/test/java/org/hibernate/validator/test/internal/engine/messageinterpolation/ExpressionLanguageMessageInterpolationTest.java, engine/src/test/java/org/hibernate/validator/test/internal/engine/messageinterpolation/MessageInterpolatorContextTest.java, engine/src/test/java/org/hibernate/validator/test/internal/engine/messageinterpolation/ResourceBundleMessageInterpolatorTest.java, engine/src/test/java/org/hibernate/validator/testutils/ValidatorUtil.java, tck-runner/src/test/resources/test.policy
=> HV-1816 Partial backport of internal changes only 

engine/src/main/java/org/hibernate/validator/internal/engine/resolver/JPATraversableResolver.java
https://hibernate.atlassian.net/browse/HV-2116
=> Backport to 9.0: HV-2116 Do not recreate PersistenceUtil in the built-in JPATraversableResolver

pom.xml
https://hibernate.atlassian.net/browse/HV-2125
=> HV-2125 Update Hibernate asciidoc theme to 5.1.2.Final

.github/workflows/ci-report.yml
=> Debug GitHub workflow: Log the pull request info from the workflow run triggering the ci-report

performance/pom.xml
=> HV-1831 Add more test profiles to perf modules/update some of the dependencies in the existing profiles

tck-runner/pom.xml
https://hibernate.atlassian.net/browse/HV-2131
=> HV-2131 Use a sig file from the TCK dist zip (instead of generating one on-the-fly)

.github/hibernate-github-bot.yml
=> Enable adding label/prefix to PRs opened for non-main branch

distribution/pom.xml, distribution/src/main/assembly/docs.xml, jenkins/release/Jenkinsfile
https://hibernate.atlassian.net/browse/HV-2142
=>   HV-2142 Stage documentation and javadocs to projectroot/target/staging-deploy/documentation

distribution/pom.xml, distribution/src/main/assembly/docs.xml, jenkins/release/Jenkinsfile
https://hibernate.atlassian.net/browse/HV-2142
=> [9.0]  HV-2142 Stage documentation and javadocs to projectroot/target/staging-deploy/documentation

distribution/pom.xml, distribution/src/main/assembly/docs.xml, jenkins/release/Jenkinsfile, performance/pom.xml, pom.xml
https://hibernate.atlassian.net/browse/HV-2142
=> [8.0] HV-2142 Stage documentation and javadocs to projectroot/target/staging-deploy/documentation

distribution/pom.xml, distribution/src/main/assembly/docs.xml, jenkins/release/Jenkinsfile, performance/pom.xml, pom.xml
https://hibernate.atlassian.net/browse/HV-2142
=> [6.2] HV-2142 Stage documentation and javadocs to projectroot/target/staging-deploy/documentation
