hibernate/hibernate-validator

engine/src/test/java/org/hibernate/validator/test/internal/constraintvalidators/hv/SafeHtmlValidatorTest.java
pom.xml

Through a security review we have discovered a problem related to Jsoup used by the SafeHtml validator. A fix has been submitted to Jsoup and the fix has now been released with version 1.8.3.
I have added a test for SafeHtmlValidator that exposes the problem and updated Jsoup to the currently latest version.
Please see the Jsoup pull request for details: https://github.com/jhy/jsoup/pull/582

HV-1012 Updated jsoup version from 1.8.1 to 1.8.3 in order to eliminate an unsafe XSS vector

---

engine/src/main/java/org/hibernate/validator/internal/engine/path/PathImpl.java

The org.hibernate.validator.internal.engine.path.PathImpl copy constructor sets the hashCode to -1, in order the hashCode to be computed on first attempt to use it.

HV-1019 PathImpl copy constructor fix

---

engine/src/main/java/org/hibernate/validator/internal/engine/ValidatorImpl.java
engine/src/main/java/org/hibernate/validator/internal/engine/groups/GroupWithInheritance.java
engine/src/main/java/org/hibernate/validator/internal/engine/groups/Sequence.java
engine/src/main/java/org/hibernate/validator/internal/engine/groups/ValidationOrder.java
engine/src/main/java/org/hibernate/validator/internal/engine/groups/ValidationOrderGenerator.java
engine/src/main/java/org/hibernate/validator/internal/metadata/BeanMetaDataManager.java
engine/src/main/java/org/hibernate/validator/internal/metadata/aggregated/BeanMetaData.java
engine/src/main/java/org/hibernate/validator/internal/metadata/aggregated/BeanMetaDataImpl.java
engine/src/main/java/org/hibernate/validator/internal/metadata/aggregated/UnconstrainedEntityMetaDataSingleton.java
engine/src/test/java/org/hibernate/validator/test/internal/engine/groups/defaultgroupwithinheritance/A.java
engine/src/test/java/org/hibernate/validator/test/internal/engine/groups/defaultgroupwithinheritance/B.java
engine/src/test/java/org/hibernate/validator/test/internal/engine/groups/defaultgroupwithinheritance/DefaultGroupWithInheritanceTest.java
engine/src/test/java/org/hibernate/validator/test/internal/engine/groups/defaultgroupwithinheritance/Max.java
engine/src/test/java/org/hibernate/validator/test/internal/engine/groups/defaultgroupwithinheritance/Min.java
engine/src/test/java/org/hibernate/validator/test/internal/engine/groups/inheritance/GroupInheritanceTest.java
engine/src/test/java/org/hibernate/validator/test/internal/engine/groups/sequence/SequenceOfSequencesTest.java
engine/src/test/java/org/hibernate/validator/test/internal/engine/groups/validationorder/ValidationOrderTest.java

Hey @hferentschik, could you take a look at this PR?
The handling of group sequences is quite painful, but I aimed at doing not more changes than needed to fix the issues at bay, as HV-1055 needs backporting to 4.3. In the long run I think we should do some changes, but the topic is complex and it's not quite clear yet to me how it could look eventually.
One thing I dislike specfically is the iteration in the case where the default group is not redefined. We could skip iteration there and just invoke the validation routine once for the default group. But I refrained from doing it for the sake of backportability for now.

HV-1055, HV-1057 Fixes around redeclared default group sequences

---

engine/src/main/java/org/hibernate/validator/internal/metadata/aggregated/BeanMetaDataImpl.java
pom.xml

Hey @hferentschik, a quick follow-up to HV-1055.
It avoids the repeated default group sequence retrieval when building the metamodel descriptors and also makes `BeanMetaDataImpl` fully immutable. WF 10 Final update as a bonus :)

HV-1058 Some optimizations around BeanMetaDataImpl

---

pom.xml

It allows to generate valid HTML5 output and fixes a bug where the user
was not brought to the right place when clicking on an anchor.

HV-1082 Upgrade maven-jdocbook-plugin and pressgang

---

engine/src/main/java/org/hibernate/validator/internal/engine/ValidatorImpl.java
engine/src/main/java/org/hibernate/validator/internal/metadata/aggregated/ParameterMetaData.java
engine/src/main/java/org/hibernate/validator/internal/metadata/aggregated/PropertyMetaData.java
engine/src/main/java/org/hibernate/validator/internal/metadata/aggregated/ReturnValueMetaData.java
engine/src/main/java/org/hibernate/validator/internal/metadata/facets/Cascadable.java
engine/src/test/java/org/hibernate/validator/test/internal/engine/valuehandling/CascadedOptionalTest.java

*Needs backporting to 5.3.*
@gsmet The actual fix is in https://github.com/hibernate/hibernate-validator/commit/3a9dbc073ecd71db339917e76b36218a2f186589. The other one is some preparation/clean-up work.

HV-1080 "Validation of Java 8 Optional throws Class cast exception"

---

documentation/src/main/asciidoc/ch11.asciidoc
engine/src/main/java/org/hibernate/validator/HibernateValidatorConfiguration.java
engine/src/main/java/org/hibernate/validator/internal/engine/ValidatorFactoryImpl.java
engine/src/main/java/org/hibernate/validator/internal/util/StringHelper.java
engine/src/test/java/org/hibernate/validator/test/cfg/ConstraintMappingContributorConfiguredInValidationXmlTest.java
engine/src/test/resources/org/hibernate/validator/test/cfg/constraint-mapping-contributor-validation.xml
integration/src/test/resources/constraint-mapping-contributor-validation.xml

* https://hibernate.atlassian.net/browse/HV-1065
The current hibernate.validator.constraint_mapping_contributor option
does not accept a comma separated list of contributors which is not in
line with the other options.
Deprecate hibernate.validator.constraint_mapping_contributor. Will be
removed in 6.

HV-1065 Add hibernate.validator.constraint_mapping_contributors option

---

pom.xml

Newer versions cause random failures in our OSGi integration tests.

HV-1117 Downgrade surefire and failsafe to 2.18.1

---

cdi/pom.xml
engine/pom.xml
pom.xml

Report can be created by running `mvn japicmp:cmp`. It's only enabled for _engine_ and _cdi_.
This is for 5.3, should be ported to master, too.

[5.3] HV-1123 Setting up japicmp instead of clirr for API/SPI change reporting

---

engine/pom.xml

This is a fix for this commit: https://github.com/hibernate/hibernate-validator/commit/09cdcccddfe3c1564076235269ad1183ca91a82a#diff-2648864198c6f1a9221ce8ac97fe85bc .
I missed updating the Java 9 generation.

HV-1114 Move the code generated by jaxb to its own package (JDK 9)

---

pom.xml

* https://hibernate.atlassian.net/browse/HV-1126
The maven-assembly-plugin uses a version which does not support JDK9.
See https://github.com/codehaus-plexus/plexus-archiver/pull/12

HV-1126 Upgrade the plexus-archiver dependency to support JDK9

---

engine/src/main/java/org/hibernate/validator/internal/engine/ConfigurationImpl.java
engine/src/main/java/org/hibernate/validator/internal/engine/ValidatorContextImpl.java
engine/src/main/java/org/hibernate/validator/internal/engine/messageinterpolation/ElTermResolver.java
engine/src/main/java/org/hibernate/validator/messageinterpolation/ResourceBundleMessageInterpolator.java
engine/src/test/java/org/hibernate/validator/test/internal/engine/ValidatorFactoryNoELBootstrapTest.java

@gsmet I've found an alternative approach for the EL issue. The idea is to defer the retrieval of the default message interpolator until it's actually needed (either by calling `getDefaultMessageInterpolator()` or when bootstrapping the VF and no other MI has been given). That way the instantiation of the expression factory can simply be done in the 'ctor of `ResourceBundleMessageInterpolator`, not requiring any synchronization.
I've also rewritten the test so it doesn't need reflection in the actual test routine. I've reworked your commit so it adds the new test and your fixes around the test class loader, but ommitted your original approach for fixing the issue for the sake of a clean history.

HV-1131 Deferring retrieval of default MI

---

engine/src/test/java/org/hibernate/validator/test/internal/engine/ValidatorFactoryNoELBootstrapTest.java

HV-1131 Add org.xml and jdk.internal to pass through packages

---

performance/pom.xml

* https://hibernate.atlassian.net/browse/HV-1163
Should be backported to 5.4.

HV-1163 Update performance tests to 5.3.3.Final

---

osgi/integrationtest/pom.xml

https://hibernate.atlassian.net/browse/HV-1161
Should be backported to 5.4.

HV-1161 Use the correct checkstyle conf for OSGi integration tests

---

documentation/src/main/asciidoc/ch01.asciidoc
pom.xml

* https://hibernate.atlassian.net/browse/HV-1182
To be backported to 5.4 before release.

HV-1182 Update WildFly patch name in the documentation

---

README.md
cdi/pom.xml
distribution/pom.xml
documentation/pom.xml
engine/src/main/java/org/hibernate/validator/internal/metadata/aggregated/BeanMetaDataImpl.java
engine/src/main/java/org/hibernate/validator/internal/metadata/aggregated/PropertyMetaData.java
engine/src/main/java/org/hibernate/validator/internal/metadata/location/PropertyConstraintLocation.java
engine/src/main/java/org/hibernate/validator/internal/metadata/provider/AnnotationMetaDataProvider.java
integration/pom.xml
integration/src/test/resources/arquillian.xml
modules/pom.xml
pom.xml
settings-example.xml
tck-runner/pom.xml
tck-runner/src/test/resources/arquillian.xml

* https://hibernate.atlassian.net/browse/HV-1187
Waiting for https://github.com/jbossas/patch-gen/pull/17 to be integrated and a new alpha released.
Uses Groovy 2.4.8-SNAPSHOT as it has important fixes regarding JDK9 ea+148 support.

HV-1187 Support JDK9 ea+148

---

engine/src/main/java/org/hibernate/validator/internal/util/CollectionHelper.java

* https://hibernate.atlassian.net/browse/HV-1193
Even if it's just to stop having this conversation over and over again, I think it's worth it. I expect the calculation to be inlined so it shouldn't cost a lot.
Having a systematic resizing when we provide a size is definitely something we should avoid.

HV-1193 Avoid systematic resizing of collections when we provide a size

---

engine-jdk8-tests/src/test/java/org/hibernate/validator/test/internal/engine/typeannotationconstraint/TypeAnnotationConstraintTest.java
engine/src/main/java/org/hibernate/validator/internal/constraintvalidators/bv/future/FutureValidatorForChronoZonedDateTime.java
engine/src/main/java/org/hibernate/validator/internal/constraintvalidators/bv/future/FutureValidatorForInstant.java
engine/src/main/java/org/hibernate/validator/internal/constraintvalidators/bv/future/FutureValidatorForOffsetDateTime.java
engine/src/main/java/org/hibernate/validator/internal/constraintvalidators/bv/past/PastValidatorForChronoZonedDateTime.java
engine/src/main/java/org/hibernate/validator/internal/constraintvalidators/bv/past/PastValidatorForInstant.java
engine/src/main/java/org/hibernate/validator/internal/constraintvalidators/bv/past/PastValidatorForOffsetDateTime.java
engine/src/test/java/org/hibernate/validator/test/internal/constraintvalidators/bv/future/FutureValidatorForChronoZonedDateTimeTest.java
engine/src/test/java/org/hibernate/validator/test/internal/constraintvalidators/bv/future/FutureValidatorForInstantTest.java
engine/src/test/java/org/hibernate/validator/test/internal/constraintvalidators/bv/future/FutureValidatorForOffsetDateTimeTest.java
engine/src/test/java/org/hibernate/validator/test/internal/constraintvalidators/bv/past/PastValidatorForChronoZonedDateTimeTest.java
engine/src/test/java/org/hibernate/validator/test/internal/constraintvalidators/bv/past/PastValidatorForInstantTest.java
engine/src/test/java/org/hibernate/validator/test/internal/constraintvalidators/bv/past/PastValidatorForOffsetDateTimeTest.java

* https://hibernate.atlassian.net/browse/HV-1198
This is for 5.4.
master is not concerned by this issue but I'll forward port the tests once we have merged this one.

HV-1198 Avoid epoch conversion overflow in @Past/@Future validators

---

pom.xml

It allows to have a consistent behavior across all browsers.
* https://hibernate.atlassian.net/browse/HV-1233
Let's backport it to 5.4 in case we do a bugfix release.

HV-1233 Convert tabs to space in rendered doc

---

engine/src/main/java/org/hibernate/validator/constraints/Currency.java
engine/src/main/java/org/hibernate/validator/constraints/EAN.java

As in the title. The others seems to be OK. 
I was just making the same 'typo' while copying an annotation for DurationMin :)

Fixing mentioning wrong annotations in JavaDoc for annotation Lists (EAN, Currency)

---

engine/src/main/java/org/hibernate/validator/internal/engine/ValidatorImpl.java
engine/src/main/java/org/hibernate/validator/internal/engine/cascading/MapKeyExtractor.java
engine/src/main/java/org/hibernate/validator/internal/engine/cascading/MapValueExtractor.java
engine/src/main/java/org/hibernate/validator/internal/engine/cascading/OptionalValueExtractor.java
engine/src/test/java/org/hibernate/validator/test/internal/engine/typeannotationconstraint/TypeAnnotationConstraintTest.java
engine/src/test/java/org/hibernate/validator/test/internal/engine/valuehandling/OptionalTypeAnnotationConstraintOnConstructorTest.java
engine/src/test/java/org/hibernate/validator/test/internal/engine/valuehandling/OptionalTypeAnnotationConstraintOnFieldTest.java
engine/src/test/java/org/hibernate/validator/test/internal/engine/valuehandling/OptionalTypeAnnotationConstraintOnGetterTest.java
engine/src/test/java/org/hibernate/validator/test/internal/engine/valuehandling/OptionalTypeAnnotationConstraintOnMethodTest.java
engine/src/test/java/org/hibernate/validator/test/internal/engine/valuehandling/OptionalTypeAnnotationConstraintUsingValidatePropertyTest.java

As a side effect, we only report 1 violation on Optionals when the
Optional is null and the wrapper and the wrapped value have a @NotNull
constraint.

HV-1240 Don't call ValueExtractors on null values anymore

---

.gitignore
distribution/src/main/assembly/dist.xml
documentation/src/main/asciidoc/ch01.asciidoc
engine/pom.xml
engine/src/main/java/org/hibernate/validator/internal/util/StringHelper.java
engine/src/main/java/org/hibernate/validator/internal/util/TypeHelper.java
engine/src/main/java/org/hibernate/validator/internal/util/privilegedactions/SetContextClassLoader.java
engine/src/main/java/org/hibernate/validator/internal/xml/ValidationXmlParser.java
engine/src/main/java/org/hibernate/validator/internal/xml/XmlMappingParser.java
engine/src/test/java/org/hibernate/validator/test/internal/util/ChildEntity.java
engine/src/test/java/org/hibernate/validator/test/internal/util/ParentEntity.java
engine/src/test/java/org/hibernate/validator/test/internal/util/StringHelperTest.java
engine/src/test/java/org/hibernate/validator/test/internal/util/TypeHelperTest.java
integration/src/test/java/org/hibernate/validator/integration/wildfly/xml/Camera.java
integration/src/test/java/org/hibernate/validator/integration/wildfly/xml/JaxpContainedInDeploymentIT.java
pom.xml
settings-example.xml
tck-runner/src/test/resources/test.policy

@gunnarmorling so here is the backport proposal for 5.2
I took the liberty to include HV-1140 as it really is a bugfix and I don't see how it could lead to a regression. If you feel strongly against it, I'll remove it.
I squashed HV-1280 to have only one commit for product review (I couldn't do it in 5.3 or 5.4 as I had already pushed the first commit).
I'll do the related work on JIRA once we agree on this.

Backports for 5.2.5

---

annotation-processor/src/main/java/org/hibernate/validator/ap/util/ConstraintHelper.java
annotation-processor/src/main/java/org/hibernate/validator/ap/util/TypeNames.java
annotation-processor/src/test/java/org/hibernate/validator/ap/ConstraintValidationProcessorTest.java
annotation-processor/src/test/java/org/hibernate/validator/ap/testmodel/customconstraints/BeanValidationConstraints.java

- https://hibernate.atlassian.net/browse/HV-1297
There seems to be no additional checks needed for these new annotations. So I've added them only to `ConstraintHelper` so AP will be happy to see them on allowed types.

HV-1297 Annotation processor support for @NotEmpty, @NotBlank, @Email, @Positive, @Negative

---

documentation/src/test/java/org/hibernate/validator/referenceguide/chapter02/typeargument/list/CarTest.java
engine/src/main/java/org/hibernate/validator/internal/engine/cascading/LegacyListValueExtractor.java
engine/src/main/java/org/hibernate/validator/internal/engine/cascading/ListPropertyValueExtractor.java
engine/src/main/java/org/hibernate/validator/internal/engine/cascading/ListValueExtractor.java
engine/src/main/java/org/hibernate/validator/internal/engine/cascading/ReadOnlyListPropertyValueExtractor.java
engine/src/main/java/org/hibernate/validator/internal/engine/path/NodeImpl.java
engine/src/test/java/org/hibernate/validator/test/internal/engine/cascaded/NestedCascadedConstraintsTest.java
engine/src/test/java/org/hibernate/validator/test/internal/engine/typeannotationconstraint/SameElementContainedSeveralTimesInCollectionTest.java
engine/src/test/java/org/hibernate/validator/test/internal/engine/typeannotationconstraint/TypeAnnotationConstraintTest.java
engine/src/test/java/org/hibernate/validator/test/internal/engine/valuehandling/JavaFXValueExtractorsTest.java
engine/src/test/java/org/hibernate/validator/test/internal/engine/valuehandling/NestedTypeArgumentsValueExtractorTest.java
engine/src/test/java/org/hibernate/validator/test/internal/engine/valuehandling/PropertyPathAndStringRepresentationTest.java

In passing, be consistent in the tests: when we test the property path,
we don't use the constants so that it is more readable and we have a
clear vision of the obtained property path.
* https://hibernate.atlassian.net/browse/HV-1320

HV-1320 Replace <iterable element> by <list element> in the node path of Lists

---

distribution/pom.xml
engine/src/main/java/org/hibernate/validator/internal/util/ConcurrentReferenceHashMap.java

- https://hibernate.atlassian.net/browse/HV-1305
Using HTML5 for JavaDoc generation with JDK 9. I've added `-html5` to parameters and also replaced a couple of `<tt>...</tt>` with `{@code}` or `{@link}` as otherwise it will give a next error:
```
error: tag not supported in the generated HTML version: tt
```
https://www.w3schools.com/tags/tag_tt.asp

HV-1305 Use HTML5 doclet when generating JavaDoc with Java 9

---

pom.xml
tck-runner/pom.xml
tck-runner/src/script/updateStandaloneXml.groovy
tck-runner/src/test/resources/arquillian.xml

Built on top of https://github.com/hibernate/hibernate-validator/pull/821 .
* https://hibernate.atlassian.net/browse/HV-1454
The javadoc error was already present with the previous version of the plugin so it's not blocking for the upgrade.

HV-1454 Support JDK 9 build 180

---

engine/pom.xml
pom.xml
tck-runner/pom.xml

@gunnarmorling here are 2 small commits to clear a Maven warning when we launch a build with Maven 3.5.0 (maybe it did exist before but it's more visible with the colors) and integrate the sigtest testing in a profile.
Note that I did not include the sigtest directly in the build as I thought we might not want to execute it  when working on new APIs and having the TCK lagging.
I'll create a CI job though once it's integrated so that we can be warned when there is an issue.
* https://hibernate.atlassian.net/browse/HV-1459
* https://hibernate.atlassian.net/browse/HV-1460

HV-1459 HV-1460 Build improvements

---

engine/src/main/java/org/hibernate/validator/internal/engine/ValidatorImpl.java
engine/src/main/java/org/hibernate/validator/internal/engine/valueextraction/LegacyCollectionSupportValueExtractors.java
engine/src/main/java/org/hibernate/validator/internal/engine/valueextraction/ListPropertyValueExtractor.java
engine/src/main/java/org/hibernate/validator/internal/engine/valueextraction/MapPropertyKeyExtractor.java
engine/src/main/java/org/hibernate/validator/internal/engine/valueextraction/MapPropertyValueExtractor.java
engine/src/main/java/org/hibernate/validator/internal/engine/valueextraction/ObservableValueValueExtractor.java
engine/src/main/java/org/hibernate/validator/internal/engine/valueextraction/OptionalDoubleValueExtractor.java
engine/src/main/java/org/hibernate/validator/internal/engine/valueextraction/OptionalIntValueExtractor.java
engine/src/main/java/org/hibernate/validator/internal/engine/valueextraction/OptionalLongValueExtractor.java
engine/src/main/java/org/hibernate/validator/internal/engine/valueextraction/OptionalValueExtractor.java
engine/src/main/java/org/hibernate/validator/internal/engine/valueextraction/ReadOnlyListPropertyValueExtractor.java
engine/src/main/java/org/hibernate/validator/internal/engine/valueextraction/ReadOnlyMapPropertyKeyExtractor.java
engine/src/main/java/org/hibernate/validator/internal/engine/valueextraction/ReadOnlyMapPropertyValueExtractor.java
engine/src/main/java/org/hibernate/validator/internal/engine/valueextraction/ReadOnlySetPropertyValueExtractor.java
engine/src/main/java/org/hibernate/validator/internal/engine/valueextraction/SetPropertyValueExtractor.java
engine/src/main/java/org/hibernate/validator/internal/metadata/aggregated/CascadingMetaData.java
engine/src/main/java/org/hibernate/validator/internal/metadata/aggregated/ContainerCascadingMetaData.java
engine/src/main/java/org/hibernate/validator/internal/metadata/aggregated/GroupConversionHelper.java
engine/src/main/java/org/hibernate/validator/internal/metadata/aggregated/NonContainerCascadingMetaData.java
engine/src/test/java/org/hibernate/validator/test/internal/engine/valueextraction/GenericModelLegacyCascadingTest.java

https://hibernate.atlassian.net/browse/HV-1481
https://hibernate.atlassian.net/browse/HV-1482
I kept the original approach of modifying the cascading metadata as it's faster if we can use it.
Note that this patch adds some overhead even when we have something like:
```
@Valid
private MyBean bean;
```
but I don't think we can avoid it, unfortunately...

HV-1481 Legacy cascading support broken when the collection/array type cannot be detected at runtime

---

engine/src/main/java/org/hibernate/validator/internal/engine/ValidationContext.java
engine/src/main/java/org/hibernate/validator/internal/engine/ValidatorImpl.java
engine/src/main/java/org/hibernate/validator/internal/engine/ValueContext.java
engine/src/main/java/org/hibernate/validator/internal/engine/constraintvalidation/ConstraintValidatorContextImpl.java
engine/src/main/java/org/hibernate/validator/internal/engine/groups/DefaultValidationOrder.java
engine/src/main/java/org/hibernate/validator/internal/engine/groups/ValidationOrder.java
engine/src/main/java/org/hibernate/validator/internal/engine/groups/ValidationOrderGenerator.java
engine/src/main/java/org/hibernate/validator/internal/engine/path/NodeImpl.java
engine/src/main/java/org/hibernate/validator/internal/engine/path/PathImpl.java
engine/src/main/java/org/hibernate/validator/internal/metadata/core/MetaConstraint.java
engine/src/test/java/org/hibernate/validator/test/internal/engine/groups/validation/GroupValidationTest.java
performance/README.md
performance/pom.xml
performance/src/main/java/org/hibernate/validator/performance/BenchmarkRunner.java
performance/src/main/java/org/hibernate/validator/performance/cascaded/CascadedValidation.java
performance/src/main/java/org/hibernate/validator/performance/cascaded/CascadedWithLotsOfItemsAndMoreConstraintsValidation.java
performance/src/main/java/org/hibernate/validator/performance/cascaded/CascadedWithLotsOfItemsValidation.java
performance/src/main/java/org/hibernate/validator/performance/simple/SimpleValidation.java

* https://hibernate.atlassian.net/browse/HV-1480
Note that, even if this patch improves the situation a bit, we are still allocating a lot of memory for the `PathImpl`/`NodeImpl` construction. It would be nice if we could improve the situation. Both the number of `NodeImpl` creations and the copy of the node list in `PathImpl` are really concerning.
Results for each version for the 3 benchmarks (~ a 20% speed up):
**HV 6.0.2.Final**
Result "org.hibernate.validator.performance.simple.SimpleValidation.testSimpleBeanValidation":
960.500 ±(99.9%) 10.939 ops/ms [Average]
(min, avg, max) = (945.886, 960.500, 989.234), stdev = 12.597
CI (99.9%): [949.561, 971.439] (assumes normal distribution)
Result "org.hibernate.validator.performance.cascaded.CascadedValidation.testCascadedValidation": …

HV-1480 Performance and memory allocation improvements

---

documentation/src/main/asciidoc/ch01.asciidoc
pom.xml

* https://hibernate.atlassian.net/browse/HV-1472
For now, we keep the 10.1 patch, waiting for the next development cycle
to start. Once it's started, we will switch to the next version.

HV-1472 Update our WildFly integration to 11.0.0.Final

---

engine/src/main/java/org/hibernate/validator/constraintvalidation/HibernateConstraintValidator.java
engine/src/main/java/org/hibernate/validator/internal/engine/constraintvalidation/ConstraintValidatorManager.java
engine/src/test/java/org/hibernate/validator/testutils/ConstraintValidatorInitializationHelper.java

We used to call only one and cascade to the other with a default method
but it's easier to call both.

HV-1497 Call both initialize() methods of HibernateConstraintValidator

---

engine/src/main/java/org/hibernate/validator/Incubating.java
engine/src/main/java/org/hibernate/validator/parameternameprovider/ReflectionParameterNameProvider.java
engine/src/test/java/org/hibernate/validator/test/parameternameprovider/ReflectionParameterNameProviderTest.java

* https://hibernate.atlassian.net/browse/HV-1537
* https://hibernate.atlassian.net/browse/HV-1538
I decided to mark it as deprecated so that we can imagine removing it at some point.

HV-1537 Reintroduce ReflectionParameterNameProvider to avoid API breakage

---

distribution/pom.xml
distribution/src/main/assembly/dist.xml
pom.xml

https://hibernate.atlassian.net//browse/HV-1558
See also https://github.com/hibernate/hibernate-noorm-release-scripts/pull/4 for more information about how this `dist` directory will be uploaded.
Note this also fixes an issue: the WildFly patch files were not being uploaded to Sourceforge. Now they will.

HV-1558 Put the distribution files to upload into distribution/target/dir so that release scripts find them

---

engine/src/test/java/org/hibernate/validator/test/internal/util/ExecutableHelperTest.java

- https://hibernate.atlassian.net/browse/HV-1461
As it turned out the upgrade of classmate in https://github.com/hibernate/hibernate-validator/commit/da94fc5c30960dd7296673bd62ba7dad66a15148 from 1.3.1 to 1.3.3 done the trick. So I've just added a test case similar to the one in the JIRA. In case of 1.3.1 version in `ExecutableHelper#instanceMethodParametersResolveToSameTypes` you would get:
```
resolvedMethods[0].getArgumentType( i ) = {ResolvedObjectType@1491} "java.lang.Long"
resolvedMethods[1].getArgumentType( i ) = {ResolvedObjectType@1493} "java.lang.Long<org.hibernate.validator.test.internal.util.ExecutableHelperTest$Bar>"
```
and in case of 1.3.3:
```
resolvedMethods[0].getArgumentType( i ) = {ResolvedObjectType@1468} "java.lang.Long"
resolvedMethods[1].getArgumentType( i ) = …
```

HV-1461 ExecutableHelper#overrides does not work correctly with the method containing generic and non generic parameters

---

engine/src/main/java/org/hibernate/validator/internal/engine/ValidationContext.java
engine/src/main/java/org/hibernate/validator/internal/engine/ValidatorImpl.java
engine/src/main/java/org/hibernate/validator/internal/metadata/aggregated/BeanMetaData.java
engine/src/main/java/org/hibernate/validator/internal/metadata/aggregated/BeanMetaDataImpl.java
engine/src/main/java/org/hibernate/validator/internal/metadata/aggregated/ExecutableMetaData.java
engine/src/main/java/org/hibernate/validator/internal/metadata/core/MetaConstraint.java
performance/pom.xml

* https://hibernate.atlassian.net/browse/HV-1587
@gunnarmorling @marko-bekhta I think these changes are safe but I'm really interested in your feedback on this one as it's a rather bold change.
Before commit:
```
Result "org.hibernate.validator.performance.simple.SimpleValidation.testSimpleBeanValidation":
1624.415 ±(99.9%) 21.333 ops/ms [Average]
(min, avg, max) = (1555.542, 1624.415, 1668.294), stdev = 24.567
CI (99.9%): [1603.082, 1645.748] (assumes normal distribution)
```
After commit:
```
Result "org.hibernate.validator.performance.simple.SimpleValidation.testSimpleBeanValidation":
2023.440 ±(99.9%) 26.463 ops/ms [Average]
(min, avg, max) = (1972.431, 2023.440, 2080.609), stdev = 30.475
CI (99.9%): [1996.977, 2049.903] (assumes normal distribution)
```

HV-1587 Reduce significantly the tracking of already validated beans and constraints

---

engine/src/main/java/org/hibernate/validator/internal/util/TypeVariableBindings.java
engine/src/test/java/org/hibernate/validator/test/internal/engine/valueextraction/ContainerInClassHierarchyTest.java

* https://hibernate.atlassian.net/browse/HV-1596
So this one is a pretty bad one. It has been there since the very first implementation of value extractors and has gone unnoticed since.
I plan to release 6.0.9.Final next week, probably on Tuesday.

HV-1596 Fix TypeVariableBindings when dealing with parent classes

---

osgi/integrationtest/src/test/java/org/hibernate/validator/osgi/integrationtest/JavaVersionUtil.java
osgi/integrationtest/src/test/java/org/hibernate/validator/osgi/integrationtest/KarafFeaturesAreInstallableTest.java
osgi/integrationtest/src/test/java/org/hibernate/validator/osgi/integrationtest/OsgiIntegrationTest.java
osgi/integrationtest/src/test/java/org/hibernate/validator/osgi/integrationtest/PaxExamOptions.java
pom.xml

!!! DO NOT MERGE YET !!!
Needs https://github.com/ops4j/org.ops4j.pax.exam2/pull/76 to be merged and released.
Once a new version of Pax Exam is released, the pom.xml needs to be updated reflect the newer version. I also updated Karaf to latest release.
Tested on JDK 8,9 and 10. Thanks!

HV-1610 make OSGI tests work on JDK 10

---

annotation-processor/src/main/java/org/hibernate/validator/ap/internal/checks/GroupSequenceProviderCheck.java
engine/src/main/java/org/hibernate/validator/internal/engine/ValidatorImpl.java
engine/src/main/java/org/hibernate/validator/internal/metadata/core/MetaConstraint.java
engine/src/main/java/org/hibernate/validator/internal/metadata/provider/AnnotationMetaDataProvider.java
engine/src/main/java/org/hibernate/validator/internal/metadata/provider/ProgrammaticMetaDataProvider.java
engine/src/test/java/org/hibernate/validator/test/cfg/ConfigurationFilePropertiesTest.java
engine/src/test/java/org/hibernate/validator/test/internal/engine/serialization/CustomConstraintSerializableTest.java
engine/src/test/java/org/hibernate/validator/test/internal/engine/valueextraction/OptionalTypeAnnotationConstraintUsingValidatePropertyTest.java
engine/src/test/java/org/hibernate/validator/test/internal/engine/valueextraction/UnwrapValidatedValueTest.java
engine/src/test/java/org/hibernate/validator/test/internal/util/privilegedactions/GetAnnotationsParameterTest.java
pom.xml

- https://hibernate.atlassian.net/browse/HV-1683
This one was caused by the ambiguity of the null exception that the 3.0.0 plugin could throw. And  this helped while I was trying to make the other pr to pass the distribution build. So I've changed the version and made a few updates to the javadoc here and there.

HV-1683 Upgrade javadoc plugin

---

engine/src/main/java/org/hibernate/validator/internal/engine/MessageInterpolatorContext.java
engine/src/main/java/org/hibernate/validator/internal/engine/validationcontext/AbstractValidationContext.java
engine/src/main/java/org/hibernate/validator/messageinterpolation/HibernateMessageInterpolatorContext.java
engine/src/test/java/org/hibernate/validator/test/internal/engine/messageinterpolation/ExpressionLanguageMessageInterpolationTest.java
engine/src/test/java/org/hibernate/validator/test/internal/engine/messageinterpolation/MessageInterpolatorContextTest.java
engine/src/test/java/org/hibernate/validator/test/internal/engine/messageinterpolation/ResourceBundleMessageInterpolatorTest.java

https://hibernate.atlassian.net/browse/HV-1657
See HV-1657 for more details. I did not add the `@Since` tag to the new method (which I probably should) since I don't know which version to indicate. I'm using Hibernate Validation in JBOSS EAP 7.1 (5.3.5Final) so I hope to get this available in some maintenance release.

HV-1657 “propertyPath” available via the HibernateMessageInterpolatorContext

---

engine/src/main/java/org/hibernate/validator/internal/engine/ValidatorImpl.java
engine/src/main/java/org/hibernate/validator/internal/engine/constraintvalidation/ConstraintValidatorContextImpl.java
engine/src/main/java/org/hibernate/validator/internal/engine/constraintvalidation/CrossParameterConstraintValidatorContextImpl.java
engine/src/main/java/org/hibernate/validator/internal/engine/path/PathImpl.java

* https://hibernate.atlassian.net/browse/HV-1691
So this won't solve the whole issue of `PathImpl` and `NodeImpl` not being serializable by Jackson but it will solve the immediate issue by making the `getPathWithoutLeafNode()` method purpose more clear and not suitable for serialization.

HV-1691 Rename PathImpl#getPathWithoutLeafNode to createCopyWithoutLeafNode

---

engine/src/main/java/org/hibernate/validator/internal/constraintvalidators/bv/number/bound/MaxValidatorForNumber.java
engine/src/main/java/org/hibernate/validator/internal/constraintvalidators/bv/number/bound/MinValidatorForNumber.java
engine/src/main/java/org/hibernate/validator/internal/constraintvalidators/bv/number/bound/NumberComparatorHelper.java
engine/src/test/java/org/hibernate/validator/test/internal/constraintvalidators/bv/BaseMinMaxValidatorForNumberTest.java
engine/src/test/java/org/hibernate/validator/test/internal/constraintvalidators/bv/MaxValidatorForNumberTest.java

- https://hibernate.atlassian.net/browse/HV-1699
If a `*Number*` validator was used it would convert any number to long hence some data might be lost. 
Change how numbers are compared in Max/Min validators
- for Min/Max `Number` validators check if actual numbers are not with floating point (float,double) and if they are direct them to correct number comparator helper method
- for big numbers (BigDecimal, BigInteger) check in number comparator helper before converting to long. If actual numbers are from the 'Big*' classes direct the call to corresponding overloaded versions of the method so that no data will be lost
- Compare floating point numbers using `Double#compare()`

HV-1699 Hibernate-validator 6: Weird behavior of the @Max annotation with a BigDecimal set on a Number field

---

engine/src/test/resources/META-INF/services/javax.validation.valueextraction.ValueExtractor

- https://hibernate.atlassian.net/browse/HV-1700
Remove ValueExtractor service file as not needed
- as the value extractors and tests for it from this file was moved to BVTCK the file became redundant and can be removed to prevent tests from logging messages about troubles with missing VE

HV-1700 Remove reference of absent valueextractor from test resources

---

engine/src/main/java/org/hibernate/validator/internal/engine/ValidatorImpl.java
engine/src/test/java/org/hibernate/validator/test/internal/engine/groups/conversion/AbstractGroupConversionTest.java

- https://hibernate.atlassian.net/browse/HV-1713
Convert current group before checking if the bean is processed:
- We need to convert the group before checking if the bean was processed or not as group defines the processed status.
Groups, processed beans .. all the things we like :smile: 
I think this test would be a good candidate for TCK.

HV-1713 Missing violation when a bean is validated with different groups

---

engine/pom.xml
engine/src/main/java/org/hibernate/validator/engine/HibernateValidatorEnhancedBean.java
engine/src/main/java/org/hibernate/validator/internal/properties/javabean/JavaBeanField.java
engine/src/main/java/org/hibernate/validator/internal/properties/javabean/JavaBeanGetter.java
engine/src/main/java/org/hibernate/validator/internal/util/TypeHelper.java
engine/src/test/java/org/hibernate/validator/test/internal/engine/EnhancedBeanAccessorTest.java
engine/src/test/java/org/hibernate/validator/test/internal/metadata/bytebuddy/ByteBuddyWrapperTest.java
engine/src/test/java/org/hibernate/validator/test/internal/util/TypeHelperTest.java
pom.xml

- https://hibernate.atlassian.net/browse/HV-1680
First commit just adds the interface and uses that interface when possible to get the values from the beans.
Second one adds a test with byte-buddy instrumentation. There are two cases one when the beans super class is object and the other one when it's a sublass of an enhanced bean. The difference is should we throw an exception when we reached the end of a method or call super method.
I'm also thinking that it might be a good idea to add another pair of methods to the interface which would give the list of "supported" properties (fields/getters). Having them in place would help us decide if we can use the enhanced bean interface or if we should fallback to regular reflection access for a particular property.
And a quick benchmark that …

HV-1680 Avoid reflection by using instrumentation - build the enhancer

---

engine/src/main/java/org/hibernate/validator/internal/properties/javabean/JavaBeanExecutable.java
engine/src/main/java/org/hibernate/validator/internal/util/logging/Log.java
engine/src/test/java/org/hibernate/validator/test/predefinedscope/PredefinedScopeValidatorFactoryTest.java

https://hibernate.atlassian.net/browse/HV-1730
Supersedes #1049 .
It turns out the problem is really caused by the lack of a `-parameters` flag when model classes are compiled. When the flag is missing, we don't have any information about which parameter is implicit/synthetic, and the existing code assumes we always have that information. As a result, it inspects all the parameters without finding the implicit/synthetic ones, and ends up triggering an `ArrayIndexOutOfBoundsException`.
The solution provided in #1049 solves the out-of bound exception, and goes a little further by trying to "guess" which type is implicit/synthetic or not based on type erasure. This will work in some cases, but will lead to incorrect results in other cases.
This PR just takes the fix from #1049, and adds the …

HV-1730 JavaBeanExecutable fails to initialize for enum type

---

documentation/src/main/asciidoc/ch02.asciidoc

Jurídica and Física was misspelled.

Fix Typo in @CNPJ and @CPF annotations doc.

---

engine/src/main/java/org/hibernate/validator/messageinterpolation/ResourceBundleMessageInterpolator.java

For Hadoop / Spark application that uses hibernate-validator, it's likely to load an older version of `ExpressionFactory` from the provided classpath (the exact dependency is javax.servlet.jsp:jsp-api from Hadoop). 
Since this older version doesn't have method `ExpressionFactory.newInstance()`, so when `ResourceBundleMessageInterpolator` tries to load the factory, it will throw a `NoSuchMethodError` and fail eventually.
But then this error is swallowed and no feedback is provided to developer. It would be better to log the error and developer could know it's time to shade the classes in the application.
I added a log to make it easier to debug and it looks like below
> 10:28:55,772 DEBUG ResourceBundleMessageInterpolator:173 - Failed to load expression factory via classloader …

Add debug log when expression factory has failed to load

---

documentation/src/main/asciidoc/ch12.asciidoc
documentation/src/test/java/org/hibernate/validator/referenceguide/chapter12/localization/LocalizationTest.java
engine/pom.xml
engine/src/main/java/org/hibernate/validator/BaseHibernateValidatorConfiguration.java
engine/src/main/java/org/hibernate/validator/PredefinedScopeHibernateValidatorConfiguration.java
engine/src/main/java/org/hibernate/validator/internal/engine/AbstractConfigurationImpl.java
engine/src/main/java/org/hibernate/validator/internal/engine/ConfigurationImpl.java
engine/src/main/java/org/hibernate/validator/internal/engine/PredefinedScopeConfigurationImpl.java
engine/src/main/java/org/hibernate/validator/internal/engine/PredefinedScopeValidatorContextImpl.java
engine/src/main/java/org/hibernate/validator/internal/engine/PredefinedScopeValidatorFactoryImpl.java
engine/src/main/java/org/hibernate/validator/internal/engine/ValidatorFactoryConfigurationHelper.java
engine/src/main/java/org/hibernate/validator/internal/engine/messageinterpolation/DefaultLocaleResolver.java
engine/src/main/java/org/hibernate/validator/internal/engine/messageinterpolation/DefaultLocaleResolverContext.java
engine/src/main/java/org/hibernate/validator/internal/util/logging/Log.java
engine/src/main/java/org/hibernate/validator/messageinterpolation/AbstractMessageInterpolator.java
engine/src/main/java/org/hibernate/validator/messageinterpolation/ParameterMessageInterpolator.java
engine/src/main/java/org/hibernate/validator/messageinterpolation/ResourceBundleMessageInterpolator.java
engine/src/main/java/org/hibernate/validator/resourceloading/AggregateResourceBundleLocator.java
engine/src/main/java/org/hibernate/validator/resourceloading/PlatformResourceBundleLocator.java
engine/src/main/java/org/hibernate/validator/spi/messageinterpolation/LocaleResolver.java
engine/src/main/java/org/hibernate/validator/spi/messageinterpolation/LocaleResolverContext.java
engine/src/test/java/org/hibernate/validator/test/internal/engine/messageinterpolation/DefaultLocaleMessageInterpolationTest.java
engine/src/test/java/org/hibernate/validator/test/internal/engine/messageinterpolation/LocaleResolverTest.java
engine/src/test/java/org/hibernate/validator/test/predefinedscope/LocaleResolverTest.java
engine/src/test/java/org/hibernate/validator/test/predefinedscope/PredefinedScopeValidatorFactoryTest.java
engine/src/test/resources/org/hibernate/validator/test/internal/engine/messageinterpolation/locale-resolver-validation.xml

* https://hibernate.atlassian.net/browse/HV-1747
* https://hibernate.atlassian.net/browse/HV-1748
* https://hibernate.atlassian.net/browse/HV-1749
@marko-bekhta if you're still with us (hi :) ), I'm interested in your feedback: the idea of this patch is to allow some more localization greatness for the `PredefinedScopeValidatorFactory`.
For now, the improvements are targeting this one as it's the only one with a proper list of locale. I have allowed to override the default locale for the good old `ValidatorFactory` too.
@irenakezic you can use this branch to finish your localization work on Quarkus. You now have a method to pass the ``LanguageRange``s to. Note that you need to check if the message interpolator is an `HibernateMessageInterpolator`, otherwise you need to default to the …

HV-1748 HV-1747 HV-1749 Improve localization support

---

cdi/src/main/java/org/hibernate/validator/cdi/internal/ValidatorFactoryBean.java
cdi/src/main/java/org/hibernate/validator/cdi/spi/BeanNames.java
cdi/src/test/java/org/hibernate/validator/test/cdi/internal/beanmetadataclassnormalizer/CustomProxy.java
cdi/src/test/java/org/hibernate/validator/test/cdi/internal/beanmetadataclassnormalizer/CustomProxyBeanMetaDataClassNormalizer.java
cdi/src/test/java/org/hibernate/validator/test/cdi/internal/beanmetadataclassnormalizer/CustomProxyBeanMetadataClassNormalizerCdiExtension.java
cdi/src/test/java/org/hibernate/validator/test/cdi/internal/beanmetadataclassnormalizer/ExtensionProvidedBeanMetadataClassNormalizerTest.java
engine/src/main/java/org/hibernate/validator/BaseHibernateValidatorConfiguration.java
engine/src/main/java/org/hibernate/validator/PredefinedScopeHibernateValidatorConfiguration.java
engine/src/main/java/org/hibernate/validator/internal/engine/AbstractConfigurationImpl.java
engine/src/main/java/org/hibernate/validator/internal/engine/PredefinedScopeConfigurationImpl.java
engine/src/main/java/org/hibernate/validator/internal/engine/ValidatorFactoryConfigurationHelper.java
engine/src/main/java/org/hibernate/validator/internal/engine/ValidatorFactoryImpl.java
engine/src/main/java/org/hibernate/validator/internal/metadata/BeanMetaDataManagerImpl.java
engine/src/main/java/org/hibernate/validator/internal/metadata/DefaultBeanMetaDataClassNormalizer.java
engine/src/main/java/org/hibernate/validator/metadata/BeanMetaDataClassNormalizer.java
engine/src/test/java/org/hibernate/validator/test/internal/engine/ValidatorFactoryBeanMetadataClassNormalizerTest.java
engine/src/test/java/org/hibernate/validator/test/internal/engine/path/PathImplTest.java
engine/src/test/java/org/hibernate/validator/test/internal/metadata/BeanMetaDataManagerTest.java
engine/src/test/java/org/hibernate/validator/test/internal/metadata/aggregated/ExecutableMetaDataTest.java
engine/src/test/java/org/hibernate/validator/test/internal/metadata/aggregated/ParameterMetaDataTest.java
engine/src/test/java/org/hibernate/validator/test/internal/metadata/aggregated/PropertyMetaDataTest.java
engine/src/test/java/org/hibernate/validator/test/predefinedscope/PredefinedScopeValidatorFactoryTest.java
integration/pom.xml
integration/src/test/java/org/hibernate/validator/integration/wildfly/ejb/EjbIT.java
integration/src/test/java/org/hibernate/validator/integration/wildfly/ejb/EjbJaxRsResource.java
integration/src/test/java/org/hibernate/validator/integration/wildfly/ejb/JaxRsApplication.java
pom.xml

https://hibernate.atlassian.net/browse/HV-1755
https://issues.jboss.org/browse/WFLY-11566
This does not solve the problem, but adds tests and a beginning of solution.
Essentially the problem is caused by WildFly creating proxies that extend user-constrained classes, but that override methods incorrectly (from the HV point of view). The overrides are incorrect because they change the constraints: constraint annotations are preserved, but the type of parameters is not (it is erased), and thus the constraint annotations have a different meaning, or at the very least become ambiguous.
For example `@Max(value = 2, payload = Unwrapping.Unwrap.class) List<Integer> param` would be executed differently than  `@Max(value = 2, payload = Unwrapping.Unwrap.class) List<String> param`. Thus, when …

[WIP] HV-1755 WFLY-11566 ConstraintDeclarationException on JAX-RS/EJB Methods with List/Set query parameter

---

engine/src/main/java/org/hibernate/validator/PredefinedScopeHibernateValidatorConfiguration.java
engine/src/main/java/org/hibernate/validator/internal/engine/AbstractConfigurationImpl.java
engine/src/main/java/org/hibernate/validator/internal/engine/PredefinedScopeConfigurationImpl.java
engine/src/main/java/org/hibernate/validator/internal/engine/PredefinedScopeValidatorFactoryImpl.java
engine/src/main/java/org/hibernate/validator/internal/engine/ValidatorFactoryImpl.java
engine/src/main/java/org/hibernate/validator/internal/engine/constraintvalidation/ClassBasedValidatorDescriptor.java
engine/src/main/java/org/hibernate/validator/internal/engine/constraintvalidation/ConstraintValidatorDescriptor.java
engine/src/main/java/org/hibernate/validator/internal/metadata/core/BuiltinConstraint.java
engine/src/main/java/org/hibernate/validator/internal/metadata/core/ConstraintHelper.java
engine/src/main/java/org/hibernate/validator/internal/util/privilegedactions/IsClassPresent.java
engine/src/test/java/org/hibernate/validator/test/internal/constraintvalidators/PredefinedScopeAllConstraintsTest.java
engine/src/test/java/org/hibernate/validator/test/internal/engine/messageinterpolation/ExpressionLanguageMessageInterpolationTest.java
engine/src/test/java/org/hibernate/validator/test/internal/engine/messageinterpolation/ResourceBundleMessageInterpolatorTest.java
engine/src/test/java/org/hibernate/validator/test/internal/metadata/core/ConstraintHelperTest.java
engine/src/test/java/org/hibernate/validator/test/internal/metadata/core/MetaConstraintTest.java
engine/src/test/java/org/hibernate/validator/test/predefinedscope/PredefinedScopeValidatorFactoryTest.java
engine/src/test/java/org/hibernate/validator/testutils/ConstraintValidatorInitializationHelper.java

https://hibernate.atlassian.net/browse/HV-1767

HV-1767 Reduce the overhead of ConstraintHelper initialization in the predefined scope case

---

engine/src/main/resources/org/hibernate/validator/ValidationMessages_de.properties

Vom Aufbau her sollten sich DecimalMin und DecimalMax-Message ähneln.
https://hibernate.atlassian.net/browse/HV-1771

HV-1771 Fix DecimalMin message German translation

---

documentation/src/main/asciidoc/ch06.asciidoc
documentation/src/test/java/org/hibernate/validator/referenceguide/chapter06/elinjection/SafeValidator.java
documentation/src/test/java/org/hibernate/validator/referenceguide/chapter06/elinjection/UnsafeValidator.java

https://hibernate.atlassian.net/browse/HV-1773

HV-1773 Be more explicit about issues with EL injection and how to avoid them

---

annotation-processor/src/main/java/org/hibernate/validator/ap/internal/util/ConstraintHelper.java
annotation-processor/src/main/java/org/hibernate/validator/ap/internal/util/TypeNames.java
annotation-processor/src/test/java/org/hibernate/validator/ap/ConstraintValidationProcessorTest.java
annotation-processor/src/test/java/org/hibernate/validator/ap/testmodel/ModelWithNormalizedConstraints.java
documentation/src/main/asciidoc/ch02.asciidoc
engine/src/main/java/org/hibernate/validator/cfg/defs/NormalizedDef.java
engine/src/main/java/org/hibernate/validator/constraints/Normalized.java
engine/src/main/java/org/hibernate/validator/internal/constraintvalidators/hv/NormalizedValidator.java
engine/src/main/java/org/hibernate/validator/internal/metadata/core/BuiltinConstraint.java
engine/src/main/java/org/hibernate/validator/internal/metadata/core/ConstraintHelper.java
engine/src/main/resources/org/hibernate/validator/ValidationMessages.properties
engine/src/test/java/org/hibernate/validator/test/internal/constraintvalidators/MessagePropertiesTest.java
engine/src/test/java/org/hibernate/validator/test/internal/constraintvalidators/PredefinedScopeAllConstraintsTest.java
engine/src/test/java/org/hibernate/validator/test/internal/constraintvalidators/hv/NormalizedValidatorTest.java

I propose the addition of `@Normalized` that validates that a character sequence is normalized to a given form.
It can be important to check normalization as part of validation to ensure that further validation works as expected.
References:
* https://docs.oracle.com/javase/7/docs/api/java/text/Normalizer.html#isNormalized(java.lang.CharSequence,%20java.text.Normalizer.Form)
* https://www.informit.com/articles/article.aspx?p=1751371&seqNum=4
* https://wiki.sei.cmu.edu/confluence/display/java/IDS01-J.+Normalize+strings+before+validating+them
https://hibernate.atlassian.net/browse/HV-1780

HV-1780 Add @Normalized contraint that validates unicode normalization form

---

engine/src/main/java/org/hibernate/validator/internal/engine/messageinterpolation/ParameterTermResolver.java
engine/src/test/java/org/hibernate/validator/test/internal/engine/messageinterpolation/ParameterTermResolverTest.java

https://hibernate.atlassian.net/browse/HV-1761
This is a fix for the 'HV-1328' bugs. The issue is that invoking `ParameterTermResolver.interpolate (context, expression)` throws the exception `java.lang.ClassCastException` if the value of the expression is a primitive array.
I can merge these changes into `6.1`, `6.2`, `master` brunches if needed.

HV-1761 fix interpolation of primitive arrays

---

distribution/pom.xml

https://hibernate.atlassian.net/browse/HV-1795

HV-1795 Remove link to JavaMoney javadoc - 6.1

---

distribution/pom.xml

https://hibernate.atlassian.net/browse/HV-1795

HV-1795 Remove link to JavaMoney javadoc - 6.0

---

engine/src/main/java/org/hibernate/validator/internal/engine/validationcontext/ParameterExecutableValidationContext.java
engine/src/test/java/org/hibernate/validator/test/internal/engine/methodvalidation/ParameterValidationCycleTest.java

We mistakenly used to consider the return value metadata even when
validating the parameters which was obviously incorrect.
This could lead to infinite loop when validating objects containing
bidirectional relationships.

HV-1797 Consider parameter metadata when enabling cycle detection - 6.1

---

engine/src/main/java/org/hibernate/validator/internal/engine/validationcontext/ParameterExecutableValidationContext.java
engine/src/test/java/org/hibernate/validator/test/internal/engine/methodvalidation/ParameterValidationCycleTest.java

We mistakenly used to consider the return value metadata even when
validating the parameters which was obviously incorrect.
This could lead to infinite loop when validating objects containing
bidirectional relationships.

HV-1797 Consider parameter metadata when enabling cycle detection

---

Jenkinsfile
engine/src/test/java/org/hibernate/validator/test/internal/engine/methodvalidation/AbstractMethodValidationTest.java
engine/src/test/java/org/hibernate/validator/test/internal/engine/methodvalidation/AnnotationBasedMethodValidationTest.java
osgi/felixtest/pom.xml
osgi/felixtest/src/test/java/org/hibernate/validator/osgi/felix/FelixCDIIT.java
osgi/integrationtest/pom.xml
osgi/integrationtest/src/test/java/org/hibernate/validator/osgi/integrationtest/KarafFeaturesAreInstallableTest.java
osgi/integrationtest/src/test/java/org/hibernate/validator/osgi/integrationtest/OsgiIntegrationTest.java
pom.xml
tck-runner/pom.xml
tck-runner/src/test/resources/test.policy

* [HV-1809](https://hibernate.atlassian.net/browse/HV-1809): Upgrade to TestNG 6.14.3
* [HV-1808](https://hibernate.atlassian.net/browse/HV-1808): Upgrade to Arquillian 1.7.0.Alpha4
* [HV-1807](https://hibernate.atlassian.net/browse/HV-1807): Add Maven profile to improve contributor experience on Intellij IDEA
* [HV-1806](https://hibernate.atlassian.net/browse/HV-1806): Use the local repository from the Maven build in OSGi/WildFly integration tests
* [HV-1805](https://hibernate.atlassian.net/browse/HV-1805): Add a Jenkinsfile to test multiple JDKs from a single job
Once this is merged, builds for branch master and PRs to this branch will appear [here](https://ci.hibernate.org/job/hibernate-validator/). We will be able to disable all other Jenkins jobs related to this branch, and exclude …

HV-1805 + HV-1806 + HV-1807 + HV-1808 + HV-1809 Jenkinsfile + various build improvements

---

Jenkinsfile

The fix for JDK-8253566 is in JDK 16 b20. Not in JDK 15 yet.

[7.0] Re-enable JDK16 testing in Jenkinsfile

---

Jenkinsfile

The fix for JDK-8253566 is in JDK 16 b20. Not in JDK 15 yet.

[6.1] Re-enable JDK16 testing in Jenkinsfile

---

engine/src/main/java/org/hibernate/validator/internal/engine/valueextraction/BooleanArrayValueExtractor.java
engine/src/main/java/org/hibernate/validator/internal/engine/valueextraction/ByteArrayValueExtractor.java
engine/src/main/java/org/hibernate/validator/internal/engine/valueextraction/CharArrayValueExtractor.java
engine/src/main/java/org/hibernate/validator/internal/engine/valueextraction/DoubleArrayValueExtractor.java
engine/src/main/java/org/hibernate/validator/internal/engine/valueextraction/FloatArrayValueExtractor.java
engine/src/main/java/org/hibernate/validator/internal/engine/valueextraction/IntArrayValueExtractor.java
engine/src/main/java/org/hibernate/validator/internal/engine/valueextraction/IterableValueExtractor.java
engine/src/main/java/org/hibernate/validator/internal/engine/valueextraction/ListPropertyValueExtractor.java
engine/src/main/java/org/hibernate/validator/internal/engine/valueextraction/ListValueExtractor.java
engine/src/main/java/org/hibernate/validator/internal/engine/valueextraction/LongArrayValueExtractor.java
engine/src/main/java/org/hibernate/validator/internal/engine/valueextraction/MapKeyExtractor.java
engine/src/main/java/org/hibernate/validator/internal/engine/valueextraction/MapPropertyKeyExtractor.java
engine/src/main/java/org/hibernate/validator/internal/engine/valueextraction/MapPropertyValueExtractor.java
engine/src/main/java/org/hibernate/validator/internal/engine/valueextraction/MapValueExtractor.java
engine/src/main/java/org/hibernate/validator/internal/engine/valueextraction/ObjectArrayValueExtractor.java
engine/src/main/java/org/hibernate/validator/internal/engine/valueextraction/ObservableValueValueExtractor.java
engine/src/main/java/org/hibernate/validator/internal/engine/valueextraction/OptionalDoubleValueExtractor.java
engine/src/main/java/org/hibernate/validator/internal/engine/valueextraction/OptionalIntValueExtractor.java
engine/src/main/java/org/hibernate/validator/internal/engine/valueextraction/OptionalLongValueExtractor.java
engine/src/main/java/org/hibernate/validator/internal/engine/valueextraction/OptionalValueExtractor.java
engine/src/main/java/org/hibernate/validator/internal/engine/valueextraction/ReadOnlyListPropertyValueExtractor.java
engine/src/main/java/org/hibernate/validator/internal/engine/valueextraction/ReadOnlyMapPropertyKeyExtractor.java
engine/src/main/java/org/hibernate/validator/internal/engine/valueextraction/ReadOnlyMapPropertyValueExtractor.java
engine/src/main/java/org/hibernate/validator/internal/engine/valueextraction/ReadOnlySetPropertyValueExtractor.java
engine/src/main/java/org/hibernate/validator/internal/engine/valueextraction/SetPropertyValueExtractor.java
engine/src/main/java/org/hibernate/validator/internal/engine/valueextraction/ShortArrayValueExtractor.java
engine/src/main/java/org/hibernate/validator/internal/engine/valueextraction/ValueExtractorDescriptor.java

https://hibernate.atlassian.net/browse/HV-1812
@yrodiere not the most exciting PR but I would appreciate a second pair of eyes.
The idea is to avoid calling a method not present in the Android JDK for the built-in value extractors.

HV-1812 Avoid reflection-based metadata extraction for built-in value extractors - 6.2

---

distribution/pom.xml
integration/pom.xml
integration/src/test/java/org/hibernate/validator/integration/wildfly/OptionalConstraintsIT.java
integration/src/test/resources/arquillian.xml
modules/pom.xml
modules/src/main/modules/wildfly-current-patch.xml
modules/src/main/modules/wildfly-secondary-patch.xml
modules/src/script/setupModules.groovy
pom.xml
tck-runner/pom.xml
tck-runner/src/script/updateStandaloneXml.groovy
tck-runner/src/test/modules/jdk11/javafx/api/main/module.xml

Also reintroduce WildFly integration tests.
To run the TCK with WildFly, run the build with `-Dincontainer`.
https://hibernate.atlassian.net/browse/HV-1826

HV-1826 Reintroduce TCK Runner in container tests

---

Jenkinsfile
pom.xml

* [HV-1836](https://hibernate.atlassian.net/browse/HV-1836): Restore CI for JDK 15
* [HV-1835](https://hibernate.atlassian.net/browse/HV-1835): Test Hibernate Validator against JDK17
Backport of #1160

Backport HV-1835 + HV-1836 to branch 6.1 - Test Hibernate Validator against JDK17

---

Jenkinsfile
pom.xml

* [HV-1836](https://hibernate.atlassian.net/browse/HV-1836): Restore CI for JDK 15
* [HV-1835](https://hibernate.atlassian.net/browse/HV-1835): Test Hibernate Validator against JDK17
Backport of #1160

Backport HV-1835 + HV-1836 to branch 6.2 - Test Hibernate Validator against JDK17

---

Jenkinsfile
pom.xml

* [HV-1836](https://hibernate.atlassian.net/browse/HV-1836): Restore CI for JDK 15
* [HV-1835](https://hibernate.atlassian.net/browse/HV-1835): Test Hibernate Validator against JDK17

HV-1835 + HV-1836 Test Hibernate Validator against JDK17

---

pom.xml

https://hibernate.atlassian.net/browse/HV-1838
Here's a build that passed on JDK17 thanks to this change: https://ci.hibernate.org/job/hibernate-validator-personal-yoann/job/HV-1838/

HV-1838 Skip forbiddenapis on JDK17+

---

pom.xml

https://hibernate.atlassian.net/browse/HV-1838
Backport of #1166
Here's a build that passed on JDK17 thanks to this change: https://ci.hibernate.org/job/hibernate-validator-personal-yoann/job/HV-1838-6.2/

Backport HV-1838 to branch 6.2 - Skip forbiddenapis on JDK17+

---

pom.xml

https://hibernate.atlassian.net/browse/HV-1838
Backport of #1166
Here's a build that passed on JDK17 thanks to this change: https://ci.hibernate.org/job/hibernate-validator-personal-yoann/job/HV-1838-6.1/

Backport HV-1838 to branch 6.1 - Skip forbiddenapis on JDK17+

---

cdi/src/main/java/org/hibernate/validator/cdi/internal/DestructibleBeanInstance.java
cdi/src/main/java/org/hibernate/validator/cdi/internal/ValidatorBean.java
cdi/src/main/java/org/hibernate/validator/cdi/internal/ValidatorFactoryBean.java
cdi/src/test/java/org/hibernate/validator/test/cdi/internal/InjectingConstraintValidatorFactoryTest.java
cdi/src/test/java/org/hibernate/validator/test/cdi/internal/beanmetadataclassnormalizer/CustomProxyBeanMetaDataClassNormalizer.java

I was testing WFLY with latest CDI API (4.0.0.Alpha1) where there was a number of removals of long deprecated methods.
See eclipse-ee4j/cdi#472
This causes hibernate validator to crash during TCK runs so I had to create a custom artifact and replace it within WFLY - this PR a sum of changes I needed to make it work.
Since you are bound to eventually bounce into the very same issue, I thought I might as well contribute. But whether you accept it or not is OFC completely up to you :-)
Oh and I should note - the current state of this PR will work with CDI 2/3 as well as CDI 4 so there should be no harm in having it applied right away.

HV-1840 Drop/replace deprecated CDI API usages

---

engine/src/main/java/org/hibernate/validator/internal/constraintvalidators/hv/pl/PESELValidator.java
engine/src/test/java/org/hibernate/validator/test/constraints/annotations/hv/pl/PESELValidatorTest.java

https://hibernate.atlassian.net/browse/HV-1854
With PESEL structure being YYMMDDZZZXQ only MM and DD parts make sense to have some additional checks applied. Year can be 00-99, ZZZ just "random digits", X - sex part is even/odd but ultimately 0-9 as well. 
Check digits in the new testcases would've allowed these numbers to be considered as valid without this additional date/month logic.
I'm actually glad that someone is using these specific validators and reported a problem with that more simple approach. 
But not as glad as being able to finally do some work here 😉

HV-1854 Improve PESEL validator conditions

---

pom.xml

This is only a test dependency so we are not affected by the CVE but
let's fix it anyway.
https://hibernate.atlassian.net/browse/HV-1859

HV-1859 Upgrade to Log4j 2 2.15.0

---

pom.xml

https://hibernate.atlassian.net/browse/HV-1862

HV-1862 Update Log4j 2 test dependency to 2.16.0

---

engine/src/main/java/org/hibernate/validator/internal/constraintvalidators/bv/time/future/FutureValidatorForDate.java
engine/src/main/java/org/hibernate/validator/internal/constraintvalidators/bv/time/futureorpresent/FutureOrPresentValidatorForDate.java
engine/src/main/java/org/hibernate/validator/internal/constraintvalidators/bv/time/past/PastValidatorForDate.java
engine/src/main/java/org/hibernate/validator/internal/constraintvalidators/bv/time/pastorpresent/PastOrPresentValidatorForDate.java
engine/src/test/java/org/hibernate/validator/test/internal/constraintvalidators/bv/time/ClockProviderFutureTest.java
engine/src/test/java/org/hibernate/validator/test/internal/constraintvalidators/bv/time/ClockProviderPastTest.java
engine/src/test/java/org/hibernate/validator/test/internal/constraintvalidators/bv/time/FixedClockProvider.java
engine/src/test/java/org/hibernate/validator/test/internal/constraintvalidators/bv/time/JavaSqlDateTest.java

https://hibernate.atlassian.net/browse/HV-1878

HV-1878 Bring back java.sql.Date support

---

Jenkinsfile
jenkins/release.groovy

https://hibernate.atlassian.net/browse/HV-1877
As explained in [HSEARCH-4472](https://hibernate.atlassian.net/browse/HSEARCH-4472), the main purpose of these changes is the third commit, which makes sure we abort previous builds when a new one starts, thereby saving on CI resources. 
However, I think it's also an improvement to separate the release job from the main one, because what happens on releases becomes more clear, and the main job becomes slightly simpler (there's more work there, but it's a start).
I created a pipeline job for this: https://ci.hibernate.org/view/Validator/job/hibernate-validator-release/
I moved the legacy job that we used in 5.x there: https://ci.hibernate.org/view/Validator/job/hibernate-validator-release-legacy/

HV-1877 Move the release job to a separate Jenkinsfile

---

integration/src/test/resources/arquillian.xml
osgi/felixtest/src/test/resources/arquillian.xml
pom.xml
tck-runner/src/test/resources/arquillian.xml

https://hibernate.atlassian.net/browse/HV-1882
Follows up on #1219
We already had a solution for WildFly (setting a property in `arquillian.xml`), but this one is more generic and will also work for Payara, once we re-enable those integration tests on the main branch (see #1227, where Payara tests run successfully on branch 6.2) .

HV-1882 Follow-up: Ensure Java programs launched in tests (Payara, WildFly) use the test Java home, not the Maven Java home

---

tck-runner/pom.xml

https://hibernate.atlassian.net/browse/HV-1882
Follows up on #1219, #1229
I made the mistake of removing this config in #1219, and did not notice it because we don't run the TCK in WildFly (yet) for branch `main`.

HV-1882 follow-up: Make sure to copy javafx.api modules to WildFly when running the TCK with JDK8

---

tck-runner/pom.xml

https://hibernate.atlassian.net/browse/HV-1882
Backport of #1230

Backport HV-1882 follow-up to branch 6.2: Make sure to copy javafx.api modules to WildFly when running the TCK with JDK8

---

Jenkinsfile
pom.xml

Note the goal is not to use those preview features; just to have them and their side-effects enabled, so as to increase the chance to detect JDK bugs.
See also https://github.com/hibernate/hibernate-search/pull/3094

Enable preview features when running tests against JDK 19

---

engine/src/main/java/org/hibernate/validator/internal/properties/javabean/JavaBeanExecutable.java
engine/src/main/java/org/hibernate/validator/internal/properties/javabean/JavaBeanParameter.java
engine/src/main/java/org/hibernate/validator/internal/util/logging/Log.java

getGenericParameterTypes() is problematic with synthetic and implicit parameters and we used to have ugly workarounds and warnings. Using getAnnotatedParameterTypes() solves the issue.
I was extremely conservative in the changes as I want to be able to backport it.
https://hibernate.atlassian.net/browse/HV-1927

HV-1927 Use Executable#getAnnotatedParameterTypes() instead of Executable#getGenericParameterTypes()

---

engine/src/main/java/org/hibernate/validator/internal/properties/javabean/JavaBeanExecutable.java
engine/src/main/java/org/hibernate/validator/internal/properties/javabean/JavaBeanParameter.java
engine/src/main/java/org/hibernate/validator/internal/util/logging/Log.java

getGenericParameterTypes() is problematic with synthetic and implicit parameters and we used to have ugly workarounds and warnings. Using getAnnotatedParameterTypes() solves the issue.
I was extremely conservative in the changes as I want to be able to backport it.
https://hibernate.atlassian.net/browse/HV-1927

HV-1927 Use Executable#getAnnotatedParameterTypes() instead of Executable#getGenericParameterTypes() - 7.0

---

documentation/pom.xml
documentation/src/main/asciidoc/index.asciidoc
pom.xml

* [HV-1934](https://hibernate.atlassian.net/browse/HV-1934): Upgrade to hibernate-asciidoctor-theme 1.0.6
* [HV-1744](https://hibernate.atlassian.net/browse/HV-1744): Use auto-expanding entries in the documentation TOC
Backport of #1296
I had to backport HV-1744 as well, otherwise tocbot (introduced in hibernate-asciidoctor-theme 1.0.3) wouldn't work correctly.
[HV-1934]: https://hibernate.atlassian.net/browse/HV-1934?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[HV-1744]: https://hibernate.atlassian.net/browse/HV-1744?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Backport HV-1744 + HV-1934 to branch 6.0 - Move documentation to Google Analytics 4

---

README.md

Please delete this text, and add a link to the Jira issue solved by this PR;
see https://hibernate.atlassian.net/browse/HV.
Remember to prepend the title of this PR, as well as all commit messages,
with the key of the Jira issue (`HV-<digits>`).

Update JDK version required for building HV and Expressly version

---

pom.xml

https://hibernate.atlassian.net/browse/HV-1938

HV-1938 Upgrade ByteBuddy test dependency to 1.13.0

---

engine/src/main/java/org/hibernate/validator/internal/engine/PredefinedScopeValidatorFactoryImpl.java
engine/src/main/java/org/hibernate/validator/internal/engine/ValidatorFactoryConfigurationHelper.java
engine/src/main/java/org/hibernate/validator/internal/engine/ValidatorFactoryImpl.java
engine/src/main/java/org/hibernate/validator/internal/metadata/provider/XmlMetaDataProvider.java
engine/src/main/java/org/hibernate/validator/internal/xml/mapping/ConstraintMappingsStaxBuilder.java
engine/src/main/java/org/hibernate/validator/internal/xml/mapping/MappingXmlParser.java
engine/src/test/java/org/hibernate/validator/test/internal/xml/XmlMappingMixedWithServiceLoaderAndProgrammaticDefinitionTest.java
engine/src/test/resources/org/hibernate/validator/test/internal/xml/hv-1949-constraint.xml
engine/src/test/resources/org/hibernate/validator/test/internal/xml/hv-1949-mapping.xml

https://hibernate.atlassian.net/browse/HV-1949
The problem was that we were building constrained elements for the XML provider only based on the info collected from XML itself + whatever was already a part of constraint helper. This was ignoring any info set by ServiceLoading or coming from programmatic definitions. As a result, constrained elements created from XML data were missing the validators. 
The idea for the fix is to process all constraint definitions from all sources, as those can override whatever was set by previous providers and only then start building the bean metadata.
If this makes sense and there's no suggestions for better names for new methods 🙈 🥲  I'll prepare a backport to 6.2 (assuming we'd want the fix to be included there too)

HV-1949 Delay building constraint bean info from XML until all sources contributed to available constraint validators

---

engine/src/main/resources/org/hibernate/validator/ValidationMessages_pt.properties
engine/src/main/resources/org/hibernate/validator/ValidationMessages_pt_BR.properties
engine/src/main/resources/org/hibernate/validator/ValidationMessages_pt_PT.properties

https://hibernate.atlassian.net/browse/HV-1941
Added European Portuguese validation messages; I moved the existing Brazilian Portuguese messages to the common Portuguese locale where applicable.

HV-1941 european portuguese validation messages (version 7.0)

---

engine/src/main/resources/org/hibernate/validator/ValidationMessages_pt.properties
engine/src/main/resources/org/hibernate/validator/ValidationMessages_pt_BR.properties
engine/src/main/resources/org/hibernate/validator/ValidationMessages_pt_PT.properties

https://hibernate.atlassian.net/browse/HV-1941
Added European Portuguese validation messages; I moved the existing Brazilian Portuguese messages to the common Portuguese locale where applicable.

HV-1941 european portuguese validation messages (version 8.0)

---

changelog.txt

The Jira issue wasn't properly marked as fixed before the release, even though the patch *was* merged before the release.
I checked, and this was the only issue we forgot to mark as fixed.

Add HV-1939 to changelog

---

engine/src/main/resources/org/hibernate/validator/ValidationMessages_fr.properties
engine/src/test/java/org/hibernate/validator/test/internal/engine/messageinterpolation/MessageInterpolationWithDefaultBundleTest.java

Hi,
I reworked french validation messages for Decimals, a white space is ok but two is too much ;)
Previous ticket about validation messages issues for french locale : https://hibernate.atlassian.net/browse/HV-1943

[HV-1943] Fix french validation messages for decimals (version 6)

---

engine/src/main/resources/org/hibernate/validator/ValidationMessages_fr.properties
engine/src/test/java/org/hibernate/validator/test/internal/engine/messageinterpolation/MessageInterpolationWithDefaultBundleTest.java

Hi,
I reworked french validation messages for Decimals, a white space is ok but two is too much ;)
Previous ticket about validation messages issues for french locale : https://hibernate.atlassian.net/browse/HV-1943

[HV-1943] Fix french validation messages for decimals (version 7)

---

engine/src/main/resources/org/hibernate/validator/ValidationMessages_fr.properties
engine/src/test/java/org/hibernate/validator/test/internal/engine/messageinterpolation/MessageInterpolationWithDefaultBundleTest.java

Hi,
I reworked french validation messages for Decimals, a white space is ok but two is too much ;)
Previous ticket about validation messages issues for french locale : https://hibernate.atlassian.net/browse/HV-1943

[HV-1943] Fix french validation messages for decimals

---

documentation/pom.xml
pom.xml

Since asciidoctor-pdf 1.5 is sooo outdated 😃 and 2.3 series seems to work for us fine, this PR upgrades the asciidoctor config similar to what we are doing in Search.

Update asciidoctor configuration and theme

---

documentation/pom.xml
engine/pom.xml
integration/pom.xml
pom.xml
tck-runner/pom.xml

… number formats
The CarTest uses an assertion expecting an US number format (decimal point). Running the build on a german locale, the CarTest fails

HV-1968 Force user.country for testing

---

Jenkinsfile
jenkins/release.groovy
pom.xml

https://hibernate.atlassian.net/browse/HV-1981

"backport" of HV-1980/HV-1981 to 8.0  - Update gpg plugin configuration / Use Maven 3.9.6 in CI builds and as a required minimum version for the build

---

jenkins/release.groovy
pom.xml

Backport of HV-1980 to 6.2 - Use env variable name instead of the passphrase in GPG configuration

---

engine/src/main/java/org/hibernate/validator/internal/constraintvalidators/hv/br/CNPJValidator.java
engine/src/test/java/org/hibernate/validator/test/constraints/annotations/hv/br/CNPJValidatorTest.java

https://hibernate.atlassian.net/browse/HV-1971

HV-1971 fix CNPJ validation when all digits are the same

---

engine/src/main/java/org/hibernate/validator/internal/engine/constraintvalidation/CrossParameterConstraintValidatorContextImpl.java

Typo found in assertion fail message in CrossParameterConstintValidatorContextImpl is fixed.
Jira issue: https://hibernate.atlassian.net/browse/HV-1965

HV-1965 Typo found in assertion fail message fixed

---

pom.xml

https://hibernate.atlassian.net/browse/HV-1998
the result of
```bash
mvn clean verify artifact:compare -DskipTests -Dbuildinfo.detect.skip=false -Dcompare.fail=false
```
is:
```
version=9.0.0-SNAPSHOT
ok=22
ko=1
ignored=0
okFiles="hibernate-validator-parent-9.0.0-SNAPSHOT.pom hibernate-validator-build-config-9.0.0-SNAPSHOT.pom hibernate-validator-build-config-9.0.0-SNAPSHOT.jar hibernate-validator-test-utils-9.0.0-SNAPSHOT.pom hibernate-validator-test-utils-9.0.0-SNAPSHOT.jar hibernate-validator-9.0.0-SNAPSHOT.pom hibernate-validator-9.0.0-SNAPSHOT.jar hibernate-validator-tck-runner-9.0.0-SNAPSHOT.pom hibernate-validator-tck-runner-9.0.0-SNAPSHOT.jar hibernate-validator-annotation-processor-9.0.0-SNAPSHOT.pom hibernate-validator-annotation-processor-9.0.0-SNAPSHOT.jar …
```

HV-1998 Use project.build.outputTimestamp

---

pom.xml

https://hibernate.atlassian.net/browse/HV-1988
Looks like logging now works with the latest WildFly 32.0.1. let's see if CI agrees.

HV-1988 Bump jboss-logging to 3.6.0.Final

---

build-config/pom.xml
osgi/felixtest/pom.xml
osgi/integrationtest/pom.xml
osgi/karaf-features/pom.xml
osgi/pom.xml
performance/pom.xml

- Removed relativePath entries.
https://hibernate.atlassian.net/browse/HV-1962

HV-1962 - Remove relativePath in pom because it's default

---

engine/src/main/java/org/hibernate/validator/constraints/br/TituloEleitoral.java
engine/src/test/java/org/hibernate/validator/test/cfg/ProgrammaticConstraintDefinitionsTest.java
engine/src/test/java/org/hibernate/validator/test/constraints/annotations/hv/br/TituloEleitoralValidatorTest.java

Fixing mod11 check to use '0' in case the rest of the division is 10, making the function to correct validate a Brazilian Titulo Eleitoral
(cherry picked from commit 0f0e8fed89cfcbf6f1883eebea556aebc3451cfc)
backport of https://github.com/hibernate/hibernate-validator/pull/1371

Bakcport of HV-2002 to 8.0 - Fixing mod11 check for Titulo Eleitoral

---

engine/src/main/java/org/hibernate/validator/constraints/br/TituloEleitoral.java
engine/src/test/java/org/hibernate/validator/test/cfg/ProgrammaticConstraintDefinitionsTest.java
engine/src/test/java/org/hibernate/validator/test/constraints/annotations/hv/br/TituloEleitoralValidatorTest.java

Fixing mod11 check to use '0' in case the rest of the division is 10, making the function to correct validate a Brazilian Titulo Eleitoral
(cherry picked from commit 0f0e8fed89cfcbf6f1883eebea556aebc3451cfc)
backport of https://github.com/hibernate/hibernate-validator/pull/1371

Backport of HV-2002 to 6.2 - Fixing mod11 check for Titulo Eleitoral

---

annotation-processor/pom.xml

The AP doesn't need to be multi-release jar anymore. There were some sources for jdk17, but now that we have 17 as a baseline ... we can simply remove this entry.

Followup on HV-1991 Remove the multi-release jar entry from AP

---

pom.xml

https://hibernate.atlassian.net/browse/HV-2012
https://github.com/hibernate/hibernate-validator/pull/1384
Bumps org.openjfx:javafx-base from 17.0.11 to 17.0.12.
---
- dependency-name: org.openjfx:javafx-base dependency-type: direct:production update-type: version-update:semver-patch ...

HV-2012 Bump org.openjfx:javafx-base from 17.0.11 to 17.0.12

---

.github/dependabot.yml
pom.xml
tck-runner/pom.xml

https://hibernate.atlassian.net/browse/HV-2008
Change the AssertJ dependency management to override the version for TCK run to the version required by the Jakarta Validation TCK and keep the version up to date for the rest of the project build. 
I'm also enabling the dependabot updates for assertj, I suspect that dependaobt may get a bit dizzy with multiple assertj dependencies, but let's see how it'll go.

HV-2008 Use latest AssertJ version for the main build and override it to Jakarta Validation TCK required for a TCK run

---

documentation/src/main/asciidoc/ch12.asciidoc
documentation/src/test/java/org/hibernate/validator/referenceguide/chapter12/failfastonpropertyviolation/Book.java
documentation/src/test/java/org/hibernate/validator/referenceguide/chapter12/failfastonpropertyviolation/FailFastOnPropertyViolationTest.java
documentation/src/test/java/org/hibernate/validator/referenceguide/chapter12/failfastonpropertyviolation/NonSelfPublishing.java
documentation/src/test/java/org/hibernate/validator/referenceguide/chapter12/failfastonpropertyviolation/Person.java
documentation/src/test/resources/org/hibernate/validator/referenceguide/chapter12/fail-fast-on-property-violation-validation.xml
engine/src/main/java/org/hibernate/validator/BaseHibernateValidatorConfiguration.java
engine/src/main/java/org/hibernate/validator/HibernateValidatorContext.java
engine/src/main/java/org/hibernate/validator/internal/engine/AbstractConfigurationImpl.java
engine/src/main/java/org/hibernate/validator/internal/engine/PredefinedScopeValidatorContextImpl.java
engine/src/main/java/org/hibernate/validator/internal/engine/PredefinedScopeValidatorFactoryImpl.java
engine/src/main/java/org/hibernate/validator/internal/engine/ValidatorContextImpl.java
engine/src/main/java/org/hibernate/validator/internal/engine/ValidatorFactoryConfigurationHelper.java
engine/src/main/java/org/hibernate/validator/internal/engine/ValidatorFactoryImpl.java
engine/src/main/java/org/hibernate/validator/internal/engine/ValidatorFactoryScopedContext.java
engine/src/main/java/org/hibernate/validator/internal/engine/ValidatorImpl.java
engine/src/main/java/org/hibernate/validator/internal/engine/validationcontext/AbstractValidationContext.java
engine/src/main/java/org/hibernate/validator/internal/engine/validationcontext/ValidationContext.java
engine/src/main/java/org/hibernate/validator/internal/engine/validationcontext/ValidatorScopedContext.java
engine/src/main/java/org/hibernate/validator/internal/metadata/PredefinedScopeBeanMetaDataManager.java
engine/src/main/java/org/hibernate/validator/internal/metadata/aggregated/BeanMetaData.java
engine/src/main/java/org/hibernate/validator/internal/metadata/aggregated/BeanMetaDataImpl.java
engine/src/main/java/org/hibernate/validator/internal/util/logging/Log.java
engine/src/test/java/org/hibernate/validator/test/internal/engine/failfastonpropertyviolation/FailFastOnPropertyViolationTest.java
performance/src/main/jakarta/org/hibernate/validator/performance/simple/SimpleClassPropertyValidation.java
performance/src/main/javax-bv2/org/hibernate/validator/performance/simple/SimpleClassPropertyValidation.java

- https://hibernate.atlassian.net/browse/HV-1328
First commit has a change for what looked like a strange behavior. the value only for the last group was considered....
Any ideas on naming of the "mode" is also welcomed. For now PR is missing the doc.

HV-1328 Add an option to validate class-level constraints only if all property constraints are valid

---

README.md
cdi/pom.xml
documentation/pom.xml
documentation/src/main/asciidoc/ch01.asciidoc
documentation/src/main/asciidoc/ch13.asciidoc

https://hibernate.atlassian.net/browse/HV-1989
backport of https://github.com/hibernate/hibernate-validator/pull/1362

Backport of HV-1989 to 8.0  -  Update documentation examples to use the min required Java version where applicable 

---

engine/src/main/java/org/hibernate/validator/internal/engine/ValidatorImpl.java
engine/src/main/java/org/hibernate/validator/internal/engine/path/PathImpl.java
engine/src/main/java/org/hibernate/validator/internal/engine/valuecontext/ValueContext.java
engine/src/main/java/org/hibernate/validator/internal/metadata/core/MetaConstraint.java
engine/src/test/java/org/hibernate/validator/test/internal/engine/path/NodeImplTest.java

https://hibernate.atlassian.net/browse/HV-1946

HV-1946 Add an empty path node for iterable/multivalued container elements

---

.github/hibernate-github-bot.yml

If there's a single dependency, the title is different, and the current pattern does not catch it 😕 

Update Hibernate GitHub bot dependebot title pattern

---

.git-blame-ignore-revs
CONTRIBUTING.md

https://hibernate.atlassian.net/browse/HV-1986

HV-1986 Add .git-blame-ignore-revs to skip revs related to auto-formatting

---

distribution/src/main/assembly/dist.xml

Was adding the same for Search (https://github.com/hibernate/hibernate-search/pull/4248) and noticed that I've missed the .cache for HV

Exclude .cache from the distribution package

---

pom.xml

https://hibernate.atlassian.net/browse/HV-1998
so that we are at 2.9+ to make sure that calling version:set also updates the `project.build.outputTimestamp`

HV-1998 Manage the versions plugin

---

documentation/pom.xml

The copy plugin that renames the pdf is missing the plexus-utils.

Add a missing dependency for a copy-maven-plugin

---

.github/dependabot.yml

as these are managed by the Jakarta EE BOM

Add Jakarta APIs to the dependabot ignore list

---

README.md

Now there's a JSON per-project that contains the repro-build information for the badge. see https://github.com/jvm-repo-rebuild/reproducible-central/pull/191

Update the reproducible badge in readme to use the dynamic data basedon the build results

---

cdi/src/main/java/org/hibernate/validator/cdi/internal/ValidationProviderHelper.java
engine/src/main/java/org/hibernate/validator/internal/metadata/PredefinedScopeBeanMetaDataManager.java
engine/src/main/java/org/hibernate/validator/internal/metadata/aggregated/BeanMetaDataImpl.java
engine/src/main/java/org/hibernate/validator/internal/util/classhierarchy/Filters.java
engine/src/test/java/org/hibernate/validator/test/internal/engine/ValidatorTest.java
engine/src/test/java/org/hibernate/validator/test/internal/util/classhierarchy/ClassHierarchyHelperTest.java

https://hibernate.atlassian.net/browse/HV-2018
I guess we never anticipated that the validation constraints will be only defined on an interface and that interface is passed to the `validateValue()`. 
What currently happens is that `beanMetaData.getClassHierarchy()` is empty and once we want to validate things we never get into this loop:
https://github.com/hibernate/hibernate-validator/blob/bb6129938a096d0928f64b7d34eb844a2d682419/engine/src/main/java/org/hibernate/validator/internal/engine/ValidatorImpl.java#L458-L462
Which means we actually do not evaluate any constraints... 
For more information on …

HV-2018 Keep the interface if it is the hierarchy root

---

engine/src/main/java/org/hibernate/validator/PredefinedScopeHibernateValidatorConfiguration.java
engine/src/main/java/org/hibernate/validator/internal/engine/PredefinedScopeConfigurationImpl.java
engine/src/main/java/org/hibernate/validator/internal/engine/PredefinedScopeValidatorFactoryImpl.java
engine/src/main/java/org/hibernate/validator/internal/metadata/core/ConstraintHelper.java
engine/src/main/java/org/hibernate/validator/internal/metadata/provider/XmlMetaDataProvider.java
engine/src/test/java/org/hibernate/validator/test/predefinedscope/PredefinedScopeValidatorFactoryTest.java
engine/src/test/java/org/hibernate/validator/test/predefinedscope/SimpleXmlBean.java
engine/src/test/resources/org/hibernate/validator/test/predefinedscope/constraints-simplexmlbean.xml

https://hibernate.atlassian.net/browse/HV-2031
we have to:
- add the beans that are defined only in the XML (that's where `beanClassesToInitialize.addAll( xmlMetaDataProvider.configuredBeanClasses() )` helps)
- make sure that the constraint helper has all the constraints we need. Initially it'll have the built-in ones for the ones requested by the config. But if the XML is trying to apply any other constraint, we will be in trouble, as the helper will not have the info. So to make it work the predefined factory is using a "dynamic" version of the helper that goes back to looking up the built-in constraints. 
By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 …

HV-2031 Make PredefinedScopeHibernateValidatorFactory aware of constraint mappings defined purely in XML

---

pom.xml

…
why would the plugin even go check something in the target?! I'll leave that investigation for the future ... 

Ignore the license check on a javadoc options xml generated in a target dir

---

pom.xml

https://hibernate.atlassian.net/browse/HV-2045
https://github.com/hibernate/hibernate-validator/pull/1445
Bump org.jboss.logging:jboss-logging from 3.6.0.Final to 3.6.1.Final
Bumps [org.jboss.logging:jboss-logging](https://github.com/jboss-logging/jboss-logging) from 3.6.0.Final to 3.6.1.Final.
- [Release notes](https://github.com/jboss-logging/jboss-logging/releases)
- [Commits](https://github.com/jboss-logging/jboss-logging/compare/3.6.0.Final...3.6.1.Final)
---
- dependency-name: org.jboss.logging:jboss-logging dependency-type: direct:production update-type: version-update:semver-patch ...
By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache …

HV-2045 Upgrade to JBoss logging 3.6.1.Final

---

pom.xml

https://hibernate.atlassian.net/browse/HV-2049
https://hibernate.atlassian.net/browse/HV-2048
https://hibernate.atlassian.net/browse/HV-2047

HV-2049 Bump Apache Groovy to 4.0.23 / HV-2048 Bump joda-time to 2.13.0 / HV-2047 Test against wildfly-preview 33.0.2.Final

---

annotation-processor/src/test/java/org/hibernate/validator/ap/testmodel/groupsequenceprovider/BazDefaultGroupSequenceProvider.java
annotation-processor/src/test/java/org/hibernate/validator/ap/testmodel/groupsequenceprovider/FooBarBazDefaultGroupSequenceProvider.java
annotation-processor/src/test/java/org/hibernate/validator/ap/testmodel/groupsequenceprovider/FooBarDefaultGroupSequenceProvider.java
annotation-processor/src/test/java/org/hibernate/validator/ap/testmodel/groupsequenceprovider/FooDefaultGroupSequenceProvider.java
annotation-processor/src/test/java/org/hibernate/validator/ap/testmodel/groupsequenceprovider/QuxDefaultGroupSequenceProvider.java
annotation-processor/src/test/java/org/hibernate/validator/ap/testmodel/groupsequenceprovider/SampleDefaultGroupSequenceProvider.java
documentation/src/test/java/org/hibernate/validator/referenceguide/chapter05/groupsequenceprovider/RentalCarGroupSequenceProvider.java
documentation/src/test/java/org/hibernate/validator/referenceguide/chapter12/constraintapi/RentalCarGroupSequenceProvider.java
engine/src/main/java/org/hibernate/validator/internal/metadata/aggregated/BeanMetaDataImpl.java
engine/src/main/java/org/hibernate/validator/internal/metadata/provider/AnnotationMetaDataProvider.java
engine/src/main/java/org/hibernate/validator/internal/util/logging/Log.java
engine/src/main/java/org/hibernate/validator/spi/group/DefaultGroupSequenceProvider.java
engine/src/test/java/org/hibernate/validator/test/cfg/ConstraintMappingTest.java
engine/src/test/java/org/hibernate/validator/test/cfg/MultipleConstraintMappingsTest.java
engine/src/test/java/org/hibernate/validator/test/internal/engine/groups/defaultgroupsequenceprovider/DefaultGroupSequenceProviderTest.java
engine/src/test/java/org/hibernate/validator/test/internal/engine/groups/defaultgroupsequenceprovider/DeprecatedDynamicGroupSequenceProvider.java
engine/src/test/java/org/hibernate/validator/test/internal/engine/groups/defaultgroupsequenceprovider/DeprecatedUser.java

https://hibernate.atlassian.net/browse/HV-1942
Since the existing assumption is that the provider is specific to a single type and cannot be placed on multiple types

HV-1942 Allow a single impl of a DefaultGroupSequenceProvider to be used on a wider range of types

---

pom.xml

https://hibernate.atlassian.net/browse/HV-2055
https://hibernate.atlassian.net/browse/HV-2056

HV-2056 Update to OpenJFX from 17.0.12 to 17.0.13 / HV-2055 Update version.org.jboss.logging.jboss-logging-tools from 3.0.1.Final to 3.0.2.Final

---

engine/src/main/resources/org/hibernate/validator/ValidationMessages_az.properties

[Jira issue HV-2053](https://hibernate.atlassian.net/browse/HV-2053)
- Unicode encoding applied for Azerbaijani-specific characters (e.g., `ə`, `ç`, `ş`, `ü`, `ö`, `ğ`, `ı`).
- Implemented custom EL syntax logic to handle Azerbaijani suffixes (`-dan` and `-dən`) accurately.

HV-2053: Add Azerbaijani (az) locale support to validation messages

---

Jenkinsfile
annotation-processor/src/main/java/org/hibernate/validator/ap/internal/checks/annotationparameters/AnnotationMessageCheck.java
engine/src/main/java/org/hibernate/validator/internal/engine/groups/Group.java
engine/src/main/java/org/hibernate/validator/internal/engine/valuecontext/ValueContext.java
engine/src/main/java/org/hibernate/validator/internal/metadata/aggregated/BeanMetaDataImpl.java
engine/src/main/java/org/hibernate/validator/internal/util/TypeHelper.java
engine/src/main/java/org/hibernate/validator/internal/xml/AbstractStaxBuilder.java
engine/src/main/java/org/hibernate/validator/internal/xml/config/ValidationConfigStaxBuilder.java
engine/src/main/java/org/hibernate/validator/internal/xml/mapping/AbstractConstrainedElementStaxBuilder.java
engine/src/main/java/org/hibernate/validator/internal/xml/mapping/AbstractConstrainedExecutableElementStaxBuilder.java
engine/src/main/java/org/hibernate/validator/internal/xml/mapping/BeanStaxBuilder.java
engine/src/main/java/org/hibernate/validator/internal/xml/mapping/ConstraintDefinitionStaxBuilder.java
engine/src/main/java/org/hibernate/validator/internal/xml/mapping/ConstraintTypeStaxBuilder.java
engine/src/main/java/org/hibernate/validator/internal/xml/mapping/GroupConversionStaxBuilder.java
engine/src/test/java/org/hibernate/validator/test/internal/util/privilegedactions/GetAnnotationsParameterTest.java

https://hibernate.atlassian.net/browse/HV-2057
A follow-up to address some of the more-or-less valid concerns that Sonar raised 😃 

HV-2057 Address some of the things Sonar reported

---

pom.xml

https://hibernate.atlassian.net/browse/HV-2058
Bumps org.wildfly:wildfly-preview-dist from 33.0.2.Final to 34.0.0.Final.
---
- dependency-name: org.wildfly:wildfly-preview-dist dependency-type: direct:production update-type: version-update:semver-major ...

HV-2058 Test against wildfly-preview 34.0.0.Final

---

pom.xml

- since it is not available and causing issues with Dependabot (most likely)
- there's a log4j-core-test now if we'd ever need it ...

Drop log4j-core test-jar from dependency management

---

performance/pom.xml

- as now it can match the one managed in the root for tests

Remove additional management of log4j in the perf module

---

.github/hibernate-github-bot.yml
.github/workflows/ci-report.yml
.github/workflows/ci.yml
.gitignore
.mvn/develocity.xml
.mvn/extensions.xml
Jenkinsfile
engine/pom.xml
jenkins/nightly/Jenkinsfile
pom.xml

https://hibernate.atlassian.net/browse/HV-2059

HV-2059 Integrate with Develocity build scans/build cache

---

Jenkinsfile
README.md

https://hibernate.atlassian.net/browse/HV-2059
Add more badges to the readme for:
- sonar
- coverage
- develocity

HV-2059 Add more badges to readme

---

engine/pom.xml
engine/src/main/java/org/hibernate/validator/messageinterpolation/ResourceBundleMessageInterpolator.java

https://hibernate.atlassian.net/browse/HV-2020
Use OSGi framework utils to get a classloader, and do not rely on a dependency to expressly.
Based on the change from https://github.com/hibernate/hibernate-validator/pull/1493 that targets 7.0 where we still could run OSGi tests

HV-2020 Use OSGi framework utils to get a classloader

---

Jenkinsfile
jenkins/nightly/Jenkinsfile
jenkins/release.groovy

Upgrade to 1.18 to avoid buggy notifications.
See https://hibernate.zulipchat.com/#narrow/channel/132096-hibernate-user/topic/Jenkins.20Notifications
Full changeset: https://github.com/hibernate/hibernate-jenkins-pipeline-helpers/compare/1.17..1.18
Don't configure the version in Jenkinsfile so that it's easier to upgrade next time.
See https://ci.hibernate.org/manage/configure#global-untrusted-pipeline-libraries to change the (default) version globally for all projects.
For more information on licensing, please check [here](https://github.com/hibernate/hibernate-validator/blob/main/CONTRIBUTING.md#legal) …

Upgrade to hibernate-jenkins-pipeline-helpers 1.18 -- and configure the version on CI instead of in Jenkinsfile

---

pom.xml

Since we now have all the dependencies we need at Maven Central

Don't use Jakarta Staging repository

---

documentation/src/main/asciidoc/ch12.asciidoc

https://hibernate.atlassian.net/browse/HV-1829
https://github.com/hibernate/hibernate-validator/pull/1514

Backport of HV-1829 to 8.0 Remove mentions of the ConstraintDefinitionContributor from the docs

---

engine/src/main/java/org/hibernate/validator/constraints/UUID.java
engine/src/main/java/org/hibernate/validator/internal/constraintvalidators/hv/UUIDValidator.java
engine/src/test/java/org/hibernate/validator/test/internal/constraintvalidators/hv/UUIDValidatorTest.java

https://hibernate.atlassian.net/browse/HV-2067

HV-2067 Adjust UUID's version/variant validation

---

.github/workflows/ci.yml
Jenkinsfile
README.md
jenkins/nightly/Jenkinsfile
jenkins/release/Jenkinsfile
jenkins/snapshot-publish/Jenkinsfile
pom.xml

https://hibernate.atlassian.net/browse/HV-2071

HV-2071 Build with JDK 21

---

integrationtest/wildfly/pom.xml

https://hibernate.atlassian.net/browse/HV-2072
so that they are not included as part of the build on JDKs 24+

HV-2072 Move WildFly integration tests to a profile

---

distribution/src/main/assembly/dist.xml
documentation/pom.xml
documentation/src/main/assembly/dist.xml
documentation/src/main/assembly/pdf.xml

https://hibernate.atlassian.net/browse/HV-2070

HV-2070 Use `maven-assembly-plugin` instead of `copy-maven-plugin` to rename the pdf documents

---

jenkins/nightly/Jenkinsfile

https://hibernate.atlassian.net/browse/HV-2023

HV-2023 Add a step to build pdf documentation to the nightly CI job

---

tck-runner/pom.xml

https://hibernate.atlassian.net/browse/HV-2072

HV-2072 Run TCK tests without the SM on JDK 24 (8.0)

---

distribution/src/main/assembly/dist.xml
documentation/pom.xml
documentation/src/main/assembly/dist.xml
documentation/src/main/assembly/pdf.xml
jenkins/nightly/Jenkinsfile

https://hibernate.atlassian.net/browse/HV-2070
https://hibernate.atlassian.net/browse/HV-2023

Backport to 8.0 HV-2070 Use maven-assembly-plugin / HV-2023 Add a step to build pdf documentation to the nightly CI job

---

distribution/src/main/assembly/dist.xml
documentation/pom.xml
documentation/src/main/assembly/dist.xml
documentation/src/main/assembly/pdf.xml
jenkins/nightly/Jenkinsfile

https://hibernate.atlassian.net/browse/HV-2070
https://hibernate.atlassian.net/browse/HV-2023

Backport to 6.2 HV-2070 Use maven-assembly-plugin / HV-2023 Add a step to build pdf documentation to the nightly CI job

---

pom.xml

https://hibernate.atlassian.net/browse/HV-2076
Bump org.wildfly:wildfly-preview-dist from 34.0.1.Final to 35.0.0.Final
Bumps org.wildfly:wildfly-preview-dist from 34.0.1.Final to 35.0.0.Final.
---
- dependency-name: org.wildfly:wildfly-preview-dist dependency-type: direct:production update-type: version-update:semver-major ...

HV-2076 Test against wildfly-preview 35.0.0.Final

---

engine/src/main/java/org/hibernate/validator/internal/engine/AbstractConfigurationImpl.java
engine/src/test/java/org/hibernate/validator/test/spi/nodenameprovider/PropertyNodeNameProviderTest.java

https://hibernate.atlassian.net/browse/HV-2074

HV-2074 Use a custom property node name provider (if available) in the programmatic mapping

---

Jenkinsfile

Check that the branch name follows a simple pattern / Require approval for Jenkins builds on PRs from external contributors

---

.github/dependabot.yml
.github/hibernate-github-bot.yml

To match the Search configuration.

Enable license check on PRs / Group GH actions updates

---

pom.xml

https://hibernate.atlassian.net/browse/HV-2079
Bump joda-time:joda-time from 2.13.0 to 2.13.1
Bumps [joda-time:joda-time](https://github.com/JodaOrg/joda-time) from 2.13.0 to 2.13.1.
- [Release notes](https://github.com/JodaOrg/joda-time/releases)
- [Changelog](https://github.com/JodaOrg/joda-time/blob/main/RELEASE-NOTES.txt)
- [Commits](https://github.com/JodaOrg/joda-time/commits)
---
- dependency-name: joda-time:joda-time dependency-type: direct:production update-type: version-update:semver-patch ...
For more information on licensing, please check …

HV-2079 Bump joda-time to 2.13.1

---

pom.xml

https://hibernate.atlassian.net/browse/HV-2081
Bump org.wildfly:wildfly-preview-dist from 35.0.0.Final to 35.0.1.Final
Bumps org.wildfly:wildfly-preview-dist from 35.0.0.Final to 35.0.1.Final.
---
- dependency-name: org.wildfly:wildfly-preview-dist dependency-type: direct:production update-type: version-update:semver-patch ...

HV-2081 Test against wildfly-preview 35.0.1.Final

---

pom.xml

https://hibernate.atlassian.net/browse/HV-2085
Bump com.thoughtworks.paranamer:paranamer from 2.8 to 2.8.1
Bumps [com.thoughtworks.paranamer:paranamer](https://github.com/paul-hammant/paranamer) from 2.8 to 2.8.1.
- [Commits](https://github.com/paul-hammant/paranamer/compare/paranamer-parent-2.8...paranamer-parent-2.8.1)
---
- dependency-name: com.thoughtworks.paranamer:paranamer dependency-type: direct:production update-type: version-update:semver-patch ...
For more information on licensing, please check [here](https://github.com/hibernate/hibernate-validator/blob/main/CONTRIBUTING …

HV-2085 Upgrade paranamer from to 2.8.1

---

cdi/pom.xml
pom.xml

https://hibernate.atlassian.net/browse/HV-2086
https://hibernate.atlassian.net/browse/HV-2087
https://hibernate.atlassian.net/browse/HV-2088

HV-2088 Bump Jakarta EE BOM to 11.0.0-RC1 / HV-2087 Upgrade jboss-logging-tools to 3.0.4.Final / HV-2086 Bump Apache Groovy to 4.0.26

---

pom.xml

https://hibernate.atlassian.net/browse/HV-2089
Bump com.thoughtworks.paranamer:paranamer from 2.8.1 to 2.8.2
Bumps [com.thoughtworks.paranamer:paranamer](https://github.com/paul-hammant/paranamer) from 2.8.1 to 2.8.2.
- [Commits](https://github.com/paul-hammant/paranamer/compare/paranamer-parent-2.8.1...paranamer-parent-2.8.2)
---
- dependency-name: com.thoughtworks.paranamer:paranamer dependency-type: direct:production update-type: version-update:semver-patch ...
For more information on licensing, please check …

HV-2089 Upgrade paranamer from to 2.8.2

---

pom.xml

https://hibernate.atlassian.net/browse/HV-2091
Bump com.thoughtworks.paranamer:paranamer from 2.8.2 to 2.8.3
Bumps [com.thoughtworks.paranamer:paranamer](https://github.com/paul-hammant/paranamer) from 2.8.2 to 2.8.3.
- [Commits](https://github.com/paul-hammant/paranamer/compare/paranamer-parent-2.8.2...paranamer-parent-2.8.3)
---
- dependency-name: com.thoughtworks.paranamer:paranamer dependency-type: direct:production update-type: version-update:semver-patch ...
For more information on licensing, please check [here](https://github.com/hibernate/hibernate-validator/blob/main/CONTRI …

HV-2091 Upgrade paranamer to 2.8.3

---

.release/.gitignore
build/enforcer/pom.xml
build/reports/pom.xml
distribution/pom.xml
documentation/pom.xml
jenkins/release/Jenkinsfile
jenkins/snapshot-publish/Jenkinsfile
parents/public/pom.xml
pom.xml

https://hibernate.atlassian.net/browse/HSEARCH-2096

HV-2096 Use JReleaser to publish hibernate artifacts

---

README.md
engine/src/test/java/org/hibernate/validator/test/internal/engine/ValidatorFactoryNoELBootstrapTest.java
pom.xml

https://hibernate.atlassian.net/browse/HV-2109

HV-2109 Bump Expressly version to 6.0.0

---

README.md
engine/src/test/java/org/hibernate/validator/test/internal/engine/ValidatorFactoryNoELBootstrapTest.java
pom.xml

https://hibernate.atlassian.net/browse/HV-2109

Backport of HV-2109 to 9.0  -  Bump Expressly version to 6.0.0

---

engine/src/main/java/org/hibernate/validator/internal/engine/resolver/JPATraversableResolver.java

https://hibernate.atlassian.net/browse/HV-2116

HV-2116 Do not recreate PersistenceUtil in the built-in JPATraversableResolver

---

documentation/src/test/java/org/hibernate/validator/referenceguide/chapter12/propertypath/PropertyPathTest.java
engine/src/main/java/org/hibernate/validator/internal/engine/path/MaterializedNode.java
engine/src/main/java/org/hibernate/validator/internal/engine/path/MaterializedPath.java
engine/src/main/java/org/hibernate/validator/internal/engine/path/MutableNode.java
engine/src/main/java/org/hibernate/validator/internal/engine/path/MutablePath.java
engine/src/main/java/org/hibernate/validator/path/Path.java

https://hibernate.atlassian.net/browse/HV-2128

HV-2128 Add HV-specific Path and expose the leaf node through it

---

.github/workflows/ci-tck-report.yml
tck-runner/pom.xml

https://hibernate.atlassian.net/browse/HV-2130
This workflow generates the artifacts that can later be pushed to the wiki to create a following page: https://github.com/marko-bekhta/hibernate-validator/wiki/Hibernate-Validator-9.0.2.Alpha-Jakarta-Validation-TCK-Results

HV-2130 Add a GitHub workflow to prepare TCK results (for certification)

---

.github/workflows/ci-tck-report.yml

https://hibernate.atlassian.net/browse/HV-2130
as these aren't published so the build won't find them...

HV-2130 Build enforcer plugin and build config before running tck

---

engine/src/main/java/org/hibernate/validator/internal/engine/valuecontext/BeanValueContext.java
engine/src/main/java/org/hibernate/validator/internal/engine/valuecontext/ValueContext.java

https://hibernate.atlassian.net/browse/HV-2135

HV-2135 Do not initialize the alreadyProcessedGroups unless necessary in BeanValueContext

---

engine/src/main/java/org/hibernate/validator/internal/engine/MessageInterpolatorContext.java
engine/src/main/java/org/hibernate/validator/internal/engine/ValidatorImpl.java
engine/src/main/java/org/hibernate/validator/internal/engine/constraintvalidation/ConstraintValidatorContextImpl.java
engine/src/main/java/org/hibernate/validator/internal/engine/constraintvalidation/ConstraintViolationCreationContext.java
engine/src/main/java/org/hibernate/validator/internal/engine/path/MutableNode.java
engine/src/main/java/org/hibernate/validator/internal/engine/path/MutablePath.java
engine/src/main/java/org/hibernate/validator/internal/engine/valuecontext/BeanValueContext.java
engine/src/main/java/org/hibernate/validator/internal/engine/valuecontext/ValueContext.java
engine/src/main/java/org/hibernate/validator/internal/engine/valueextraction/ValueExtractorResolver.java
engine/src/main/java/org/hibernate/validator/internal/metadata/location/AbstractPropertyConstraintLocation.java
engine/src/main/java/org/hibernate/validator/internal/metadata/location/BeanConstraintLocation.java
engine/src/main/java/org/hibernate/validator/internal/metadata/location/ConstraintLocation.java
engine/src/main/java/org/hibernate/validator/internal/metadata/location/CrossParameterConstraintLocation.java
engine/src/main/java/org/hibernate/validator/internal/metadata/location/ParameterConstraintLocation.java
engine/src/main/java/org/hibernate/validator/internal/metadata/location/ReturnValueConstraintLocation.java
engine/src/main/java/org/hibernate/validator/internal/metadata/location/TypeArgumentConstraintLocation.java
engine/src/main/java/org/hibernate/validator/internal/util/CollectionHelper.java

https://hibernate.atlassian.net/browse/HV-2135

HV-2135 Better leverage the node/path mutability

---

engine/src/main/java/org/hibernate/validator/internal/engine/path/MaterializedPath.java
engine/src/main/java/org/hibernate/validator/internal/util/logging/Log.java
engine/src/main/java/org/hibernate/validator/path/Path.java
engine/src/main/java/org/hibernate/validator/path/RandomAccessPath.java
engine/src/test/java/org/hibernate/validator/test/internal/engine/path/RandomAccessPathTest.java

https://hibernate.atlassian.net/browse/HV-2139

HV-2139 Introduce an IndexedPath as an extension of the org.hibernate.validator.path.Path
